/**
 * Gestirne der Tageszeit-Scheibe über der Minimap (M3-28, §26 „Tageszeit-Scheibe (Sonne/Mond)“, §10 Mond):
 *
 * - `ui_himmel_sonne`: Sonnenscheibe (7 px, Kontur), oben hell, unten glutorange.
 * - `ui_himmel_mond`: acht Frames = Mondphasen 0–7 (`Calendar.moonPhase`): 0 Finstermond (dunkle Scheibe
 *   mit violettem Rand – die Farbfamilie der Schattenbrut, die in dieser Nacht stärker kommt, docs/ART.md
 *   §8), 1–3 zunehmend (Licht rechts), 4 Vollmond, 5–7 abnehmend (Licht links).
 *
 * Beide Motive sind 9×9 mit Kontur und stehen mittig in der Zelle (Anker [7, 7] = Scheibenmitte), damit die
 * Scheibe sie auf ganzen Pixeln entlang ihres Bogens setzen kann.
 */
import { uiSymbol } from './_ui';

export default [
  uiSymbol('ui_himmel_sonne', [
    `................
     ................
     ................
     ......kkk.......
     .....kVVVk......
     ....kVvvvVk.....
     ...kVvvvvvVk....
     ...kvvvvvvvk....
     ...kUvvvvvUk....
     ....kUvvvUk.....
     .....kUUUk......
     ......kkk.......
     ................
     ................
     ................
     ................`,
  ]),
  uiSymbol('ui_himmel_mond', [
    // 0 Finstermond
    `................
     ................
     ................
     ......[[[.......
     .....[NNN[......
     ....[NnnnN[.....
     ...[NnnnnnN[....
     ...[nnnnnnn[....
     ...[nnnnnnn[....
     ....[nnnnn[.....
     .....[nnn[......
     ......[[[.......
     ................
     ................
     ................
     ................`,
    // 1 zunehmende Sichel
    `................
     ................
     ................
     ......kkk.......
     .....kNNNk......
     ....kNnnn#k.....
     ...kNnnnn0#k....
     ...knnnnn00k....
     ...knnnnn09k....
     ....knnnn9k.....
     .....knnnk......
     ......kkk.......
     ................
     ................
     ................
     ................`,
    // 2 erstes Viertel
    `................
     ................
     ................
     ......kkk.......
     .....kN##k......
     ....kNn00#k.....
     ...kNnn000#k....
     ...knnn0000k....
     ...knnn0009k....
     ....knn009k.....
     .....kn99k......
     ......kkk.......
     ................
     ................
     ................
     ................`,
    // 3 zunehmend
    `................
     ................
     ................
     ......kkk.......
     .....k###k......
     ....kN000#k.....
     ...kNn0000#k....
     ...knn00000k....
     ...knn00009k....
     ....kn0009k.....
     .....k999k......
     ......kkk.......
     ................
     ................
     ................
     ................`,
    // 4 Vollmond
    `................
     ................
     ................
     ......kkk.......
     .....k###k......
     ....k#000#k.....
     ...k#00000#k....
     ...k0000000k....
     ...k9000009k....
     ....k90009k.....
     .....k999k......
     ......kkk.......
     ................
     ................
     ................
     ................`,
    // 5 abnehmend
    `................
     ................
     ................
     ......kkk.......
     .....k###k......
     ....k#000Nk.....
     ...k#0000nNk....
     ...k00000nnk....
     ...k90000nnk....
     ....k9000nk.....
     .....k999k......
     ......kkk.......
     ................
     ................
     ................
     ................`,
    // 6 letztes Viertel
    `................
     ................
     ................
     ......kkk.......
     .....k##Nk......
     ....k#00nNk.....
     ...k#000nnNk....
     ...k0000nnnk....
     ...k9000nnnk....
     ....k900nnk.....
     .....k99nk......
     ......kkk.......
     ................
     ................
     ................
     ................`,
    // 7 abnehmende Sichel
    `................
     ................
     ................
     ......kkk.......
     .....kNNNk......
     ....k#nnnNk.....
     ...k#0nnnnNk....
     ...k00nnnnnk....
     ...k90nnnnnk....
     ....k9nnnnk.....
     .....knnnk......
     ......kkk.......
     ................
     ................
     ................
     ................`,
  ]),
];
