/**
 * Kartensymbole der Ortstypen `karte_ort_<ortstyp>` (M7-08, M7-09; docs/SPIEL.md §18 "Kartensymbol", §25): je Ortstyp ein
 * Motiv, das auf Pergament, im Nebel und auf der Minimap lesbar bleibt – Feuerschale auf der Säule (Leuchtfeuer-Stätte),
 * Turm mit Dach (Aussichtsturm), Haus mit Tür (Gehöft), Stele mit Sonne auf Stufen (Schrein), Baumkrone
 * (Naturwunder), rotes Kreuz der Schatzkarte (Buddelstelle), Hütte mit Rauch (Eremitenhütte), gebrochener Bogen über Wasser
 * (Brückenruine), Steinkreuz hinter Eisenzaun (Friedhof), Meteor mit Schweif über dem Krater (Meteoritenkrater), gehörnter
 * Schädel (Bossarena, Strang F – das Symbol gehört zur Karte, M7-49). Motive mittig
 * um [7, 7], Kontur `nacht.1` (wie `ui_karte_*`, M3-28).
 */
import { uiSymbol } from './_ui';

export default [
  uiSymbol('karte_ort_leuchtfeuer', [
    `................
     .......kk.......
     ......kVvk......
     .....kvVUvk.....
     .....kUvUUk.....
     ....kkkkkkkk....
     ....k554455k....
     .....k5443k.....
     .....k4432k.....
     .....k4332k.....
     .....k3322k.....
     ....k443322k....
     ....k332222k....
     ....kkkkkkkk....
     ................
     ................`,
  ]),
  uiSymbol('karte_ort_aussichtsturm', [
    `................
     ......kkkk......
     .....kmMMmk.....
     ....kmMMMMmk....
     ...kllllllllk...
     ....kcbbbbck....
     ....k554435k....
     ....k5443k3k....
     ....k443343k....
     ....k4K3433k....
     ....k433432k....
     ....k43K332k....
     ....k332322k....
     ...kkkkkkkkkk...
     ................
     ................`,
  ]),
  uiSymbol('karte_ort_gehoeft', [
    `................
     ................
     .......kk..kk...
     ......kmMk.k3k..
     .....kmMMMkk3k..
     ....kmMMMMMmkk..
     ...kmmmmmmmmmk..
     ...kllllllllllk.
     ....kdcdckdcdk..
     ....kccckKkcck..
     ....kdcdkKkdck..
     ....kbbbkKkbbk..
     ....kkkkkkkkkk..
     ................
     ................
     ................`,
  ]),
  uiSymbol('karte_ort_schrein', [
    `................
     .......kk.......
     ......k55k......
     .....k5445k.....
     .....k4DE4k.....
     .....kDVED3k....
     .....k4ED43k....
     .....k4443k.....
     ...kkkkkkkkkk...
     ...k55555544k...
     ....k443332k....
     ...kkkkkkkkkk...
     ...k55444332k...
     ...kkkkkkkkkk...
     ................
     ................`,
  ], { einzelpixel: 'heller Kern der Erbauer-Sonne' }),
  uiSymbol('karte_ort_naturwunder', [
    `................
     .....kkkkkk.....
     ...kkiiJjjikk...
     ..kiJJjiiijiik..
     ..kijjiihiiihk..
     .kiihiiiihhihhk.
     .khiiihhiihhhgk.
     ..kghhhgghhggk..
     ...kkgggggkkk...
     .....kcdbk......
     .....kcdbk......
     ....kccdbbk.....
     ...kccbkdbbk....
     ...kkkk.kkkk....
     ................
     ................`,
  ]),
  uiSymbol('karte_ort_buddelstelle', [
    `................
     ................
     ...kk......kk...
     ..kFuk....kuFk..
     ...kuuk..kuuk...
     ....kuuk.kuuk...
     .....kuukuuk....
     ......kuUuk.....
     .....kuukuuk....
     ....kuuk.kuuk...
     ...kuuk..kuuk...
     ..kFuk....kuFk..
     ...kk......kk...
     ................
     ................
     ................`,
  ], { einzelpixel: 'Glanz im Kreuzungspunkt des Kreuzes' }),
  uiSymbol('karte_ort_eremitenhuette', [
    `................
     .........kk.....
     ....kk..k33k....
     ...k~~k.k33k....
     ....kk.kk33kk...
     .....kCDDDDDCk..
     ....kCDDDDDDDCk.
     ...kBBBBBBBBBBk.
     ....kdcdkKkdck..
     ....kccckKkcck..
     ....kbbbkKkbbk..
     ....kkkkkkkkkk..
     ................
     ................
     ................
     ................`,
  ]),
  uiSymbol('karte_ort_brueckenruine', [
    `................
     ................
     ................
     .kkkkkk..kkkkkk.
     .k55554k.k4555k.
     .k44444k.k4444k.
     .k43kk3k..k343k.
     .k43k.kk...kk3k.
     .k43k.......k3k.
     .k32k.......k2k.
     .k32k.......k2k.
     kkzzkkkkkkkkkzzk
     kyzzyyzzyyzzyyzk
     kkxxwwxxwwxxwxxk
     .kkkkkkkkkkkkkk.
     ................`,
  ]),
  uiSymbol('karte_ort_friedhof', [
    `................
     .......kk.......
     ......k55k......
     ....kkk54kkk....
     ....k555444k....
     ....kkk43kkk....
     ......k43k......
     ......k43k......
     ..k.k.k43k.k.k..
     .kNkNkk32kkNkNk.
     .kNkNk3222kNkNk.
     .knknkqqqqkknkn.
     .kkkkkkkkkkkkkk.
     ................
     ................
     ................`,
  ]),
  uiSymbol('karte_ort_meteoritenkrater', [
    `................
     ..k.............
     .k0k............
     ..k9k...........
     ...k9k..........
     ....k8kkkk......
     .....kn~NNk.....
     ....kN~ZNYnk....
     ....kNNY#Znk....
     ....knNZYnnk....
     .....knnnnk.....
     ....kqqkkkkqk...
     ...kqrrqqqrrqk..
     ....kkkkkkkkk...
     ................
     ................`,
  ], { einzelpixel: 'Glanzpunkt des Sternensplitters' }),
  uiSymbol('karte_ort_bossarena', [
    `................
     .k............k.
     .kNk........kNk.
     .kN~k.kkkk.k~Nk.
     ..kN~kk55kk~Nk..
     ...kkk5555kkk...
     ....k555555k....
     ...k5KKK5KKK4k..
     ...k5KKK5KKK4k..
     ...k45555554k...
     ....k45KK54k....
     .....k5454k.....
     .....k4k4k4k....
     ......kkkkk.....
     ................
     ................`,
  ]),
];
