/**
 * Die abgeleiteten und eigenen Kartenmarker (M7-49; MASTERPROMPT §25 "Marker automatisch (Orte, Leuchtfeuer, Grab, Basen,
 * Händlerin) und eigene (Symbol + Name)"; docs/SPIEL.md §29 "Kartensymbole `karte_leuchtfeuer`, `karte_grab`, `karte_basis`,
 * `karte_aufgabe`, eigene `karte_eigen_1…8`"):
 *
 * - `karte_leuchtfeuer`: das entzündete Leuchtfeuer – die Säule der Stätte (`karte_ort_leuchtfeuer`) mit hoher Flamme und
 *   Strahlen; `karte_grab`: Grabstein auf dem Erdhügel (wie `ui_karte_grab` der Minimap); `karte_basis`: das Herdfeuer unter
 *   seinem Giebel auf dem Steinsockel; `karte_aufgabe`: das goldene Fragezeichen des Aufgabenziels.
 * - Eigene: Fahne, Zelt (Lager), Höhleneingang, Erz mit Glitzer, Truhe (Fundstück), Schädel (Gefahr), Wassertropfen, Stern –
 *   acht Motive mit verschiedener Silhouette, auf Pergament und im Nebel lesbar.
 *
 * Alle Motive mittig um [7, 7], Kontur `nacht.1` (wie `ui_karte_*`, M3-28, und `karte_ort_*`).
 */
import { uiSymbol } from './_ui';

export default [
  uiSymbol('karte_leuchtfeuer', [
    `......k..k......
     ...k..kVVk..k...
     ....k.kvVk.k....
     .....kvVVvk.....
     ....kUvVVvUk....
     ....kuUvvUuk....
     ...kkkkkkkkkk...
     ....k554455k....
     .....k5443k.....
     .....k4432k.....
     .....k4332k.....
     ....k443322k....
     ....k332222k....
     ....kkkkkkkk....
     ................
     ................`,
  ]),
  uiSymbol('karte_grab', [
    `................
     ................
     ......kkk.......
     .....k555k......
     ....k55255k.....
     ....k42224k.....
     ....k44244k.....
     ....k44244k.....
     ....k33333k.....
     ...ksqqqqqsk....
     ....kqqqqqk.....
     .....kkkkk......
     ................
     ................
     ................
     ................`,
  ]),
  uiSymbol('karte_basis', [
    `.......kk.......
     ......kcck......
     .....kcddck.....
     ....kcdkkdck....
     ...kcdk..kdck...
     ..kkkk.vV.kkkk..
     ....k.vVVv.k....
     ....k.UvvU.k....
     ....k.uUUu.k....
     ...k4kkkkkk4k...
     ..k45433335433k.
     ...kkkkkkkkkkk..
     ................
     ................
     ................
     ................`,
  ]),
  uiSymbol('karte_aufgabe', [
    `......kkkk......
     .....kvVVvk.....
     ....kvVkkVvk....
     ....kVk..kVk....
     .....k..kVvk....
     .......kVvk.....
     ......kVvk......
     ......kvUk......
     ......kkkk......
     ................
     ......kkkk......
     ......kvVk......
     ......kUvk......
     ......kkkk......
     ................
     ................`,
  ]),
  uiSymbol('karte_eigen_1', [
    `................
     ....kk..........
     ....kdkkkkkk....
     ....kdkuuuuuk...
     ....kdkuFFFuuk..
     ....kdkFFFFFk...
     ....kdkFFFFk....
     ....kdkkkkk.....
     ....kdk.........
     ....kdk.........
     ....kdk.........
     ...kkdkk........
     ..kqqqqqk.......
     ...kkkkk........
     ................
     ................`,
  ]),
  uiSymbol('karte_eigen_2', [
    `................
     ................
     .......kk.......
     ......kedk......
     .....kedcck.....
     .....kdcKck.....
     ....kdcKKcck....
     ....kdcKKKcck...
     ...kdccKKKccck..
     ...kkkkkkkkkkk..
     ..kssssssssssk..
     ...kkkkkkkkkk...
     ................
     ................
     ................
     ................`,
  ]),
  uiSymbol('karte_eigen_3', [
    `................
     ................
     .....kkkkkk.....
     ....k544445k....
     ...k54kkkk45k...
     ..k54kKKKKk45k..
     ..k4kKKKKKKk4k..
     ..k4kKKKKKKk3k..
     ..k3kKKKKKKk3k..
     ..k3kKKKKKKk2k..
     .kk2kKKKKKKk2kk.
     .k22kkkkkkkk22k.
     ..kkkkkkkkkkkk..
     ................
     ................
     ................`,
  ]),
  uiSymbol('karte_eigen_4', [
    `................
     .........k......
     ........kYk.....
     .....kkkkk......
     ....k5543kk.....
     ...k5542Z3k.....
     ...k542YZ32k....
     ...k43ZY322k....
     ..k4322Z3221k...
     ..k3322322211k..
     ..k2221221111k..
     ...kk111111kk...
     .....kkkkkk.....
     ................
     ................
     ................`,
  ]),
  uiSymbol('karte_eigen_5', [
    `................
     ................
     ....kkkkkkkk....
     ...kddeeeeddk...
     ..kdccccccccdk..
     ..kkkkkvvkkkkk..
     ..kcbbkVVkbbck..
     ..kcbbbkkbbbck..
     ..kcbbbbbbbbck..
     ..kbaaaaaaaabk..
     ..kkkkkkkkkkkk..
     ................
     ................
     ................
     ................
     ................`,
  ]),
  uiSymbol('karte_eigen_6', [
    `................
     .....kkkkkk.....
     ....k666665k....
     ...k66666655k...
     ...k6KK66KK5k...
     ...k6KK66KK4k...
     ...k66655554k...
     ....k654454k....
     .....k6k5k4k....
     .....kk5k4k.....
     ......kkkk......
     ................
     ................
     ................
     ................
     ................`,
  ]),
  uiSymbol('karte_eigen_7', [
    `................
     .......kk.......
     ......kYZk......
     ......kYZk......
     .....kYZZzk.....
     ....kYZZzzzk....
     ....kYZzzzyk....
     ...kZYZzzzyyk...
     ...kZZzzzyyyk...
     ...kzZzzyyyxk...
     ....kzzyyyxk....
     .....kyyxxk.....
     ......kkkk......
     ................
     ................
     ................`,
  ]),
  uiSymbol('karte_eigen_8', [
    `................
     .......kk.......
     .......kVk......
     ......kvVk......
     ......kvVvk.....
     .kkkkkkvVvkkkkk.
     ..kVVVvvvvvvUk..
     ...kvVvvvvvUk...
     ....kvvvvvUk....
     ....kvvUkvUk....
     ...kvvUkkkvUk...
     ...kvUk...kUk...
     ...kkk.....kk...
     ................
     ................
     ................`,
  ]),
];
