/**
 * Symbole der Benachrichtigungen (M3-29, §26 „Entdeckungen, Warnungen (Dunkelheit naht, Kälte, Hunger)“).
 * Warnungen zu Überlebenswerten zeigen das Icon ihres Zustands (`zustand_<stufe>`, docs/SPIEL.md §6) –
 * dieselbe Formsprache wie in der Zustandsleiste. Eigene Symbole brauchen nur Meldungen ohne Zustand:
 *
 * - `ui_meldung_dunkelheit`: Die Sonne sinkt glutrot hinter den dunklen Horizont, darüber erscheinen
 *   Sterne („Die Dunkelheit naht“).
 * - `ui_meldung_entdeckung`: goldene Windrose mit Lichtfacetten oben/links (Entdeckung eines Ortes oder
 *   Gebiets).
 * - `ui_meldung_taschen_voll`: prall gefüllter Lederbeutel, aus dem Stock und Stein ragen (Taschen voll,
 *   §11.4 „klarer Hinweis bei vollen Taschen“).
 * - `ui_meldung_hinweis`: dunkles Ausrufezeichen auf einer bernsteinfarbenen Scheibe, oben hell, unten
 *   glutrot (ein abgelehnter Befehl mit Grund und Lösung, §26 „Fehlermeldungen sagen, was fehlt“).
 */
import { uiSymbol } from './_ui';

export default [
  uiSymbol(
    'ui_meldung_dunkelheit',
    [
      `................
       ............0...
       ...0.......0#0..
       ..0#0.......0...
       ...0............
       .....kkkkk......
       ....kUUUUUk.....
       ...kUuuuuuUk....
       ..kUuuuuuuuUk...
       ..kFFFFFFFFFk...
       .kNNNNNNNNNNNNk.
       .knnnnnnnnnnnnk.
       ..kkkkkkkkkkkk..
       ................
       ................
       ................`,
    ],
    { einzelpixel: 'Sternmitte als heller Einzelpunkt im Kreuz aus Strahlen' },
  ),
  uiSymbol('ui_meldung_entdeckung', [
    `................
     .......k........
     ......kvk.......
     ......kvk.......
     .....kVvUk......
     ....kkVvUkk.....
     ..kkVVVvUvvkk...
     .kvvvvvvvvvvvk..
     ..kkUUvvuuukk...
     ....kkvvukk.....
     .....kvvuk......
     ......kvk.......
     ......kvk.......
     .......k........
     ................
     ................`,
  ]),
  uiSymbol('ui_meldung_taschen_voll', [
    `................
     ......k..kk.....
     .....kdkk55k....
     ....kkdkk44k....
     ...kssdsrrrsk...
     ....kkaaaakk....
     ....kssssssk....
     ...ksrrrrrrsk...
     ..ksrrrrrrrrsk..
     ..krrrrrrrrrrk..
     ..kqrrrrrrrrqk..
     ...kqqqqqqqqk...
     ....kppppppk....
     .....kkkkkk.....
     ................
     ................`,
  ]),
  uiSymbol('ui_meldung_hinweis', [
    `................
     .....kkkkkk.....
     ...kkvvvvvvkk...
     ..kvVVVkkVVVvk..
     ..kvVVVkkVVVvk..
     .kUvVVVkkVVVvUk.
     .kUvvVVkkVVvvUk.
     .kUUvvvkkvvvUUk.
     .kuUUvvkkvvUUuk.
     .kuuUUvvvvUUuuk.
     .kuuUUUkkUUUuuk.
     ..kuuuukkuuuuk..
     ..kFuuuuuuuuFk..
     ...kkFFFFFFkk...
     .....kkkkkk.....
     ................`,
  ]),
];
