/**
 * Wetter-Symbole der Minimap (M3-28, §26 „oben rechts Minimap mit Tageszeit-Scheibe, Tag, Jahreszeit,
 * Wetter“): je Wetterzustand aus `src/content/weather.ts` ein Symbol `ui_wetter_<zustand>`, dazu
 * `ui_wetter_klar_nacht` (klarer Himmel nach Sonnenuntergang: Mondsichel statt Sonne).
 *
 * Formsprache: Wolken als weiche Dreibogen-Silhouette mit flachem Boden (hell `eis` bei leichtem Wetter,
 * `stein` bei Regen, dunkel bei Gewitter und Ascheregen), Niederschlag darunter als kleine, eigene Cluster
 * (schräge Regenstriche, Schneeflocken als Kreuz, Asche und Glut als Pärchen). Die Symbole stehen im HUD auf
 * dunklem Grund; Kontur `nacht.1` trennt die Hauptform, Niederschlag bleibt ohne Kontur, damit das Symbol
 * nicht zuläuft.
 */
import { uiSymbol } from './_ui';

/** Regenwolke (oben, Zeilen 1–9): `H` Oberkante, `M` Körper, `S` vorletzte, `B` unterste Zeile. */
const REGENWOLKE = [
  '................',
  '.......kkkk.....',
  '......kHHHHk....',
  '...kkkHMMMMHk...',
  '..kHHHMMMMMMHk..',
  '.kHMMMMMMMMMMHk.',
  '.kMMMMMMMMMMMMk.',
  '.kBSSSSSSSSSSBk.',
  '..kBBBBBBBBBBk..',
  '...kkkkkkkkkk...',
];

/** Regenwolke in den Farben `h`, `m`, `s`, `b` über den Zeilen 10–15 `unten`. */
function wolke(h: string, m: string, s: string, b: string, unten: readonly string[]): string {
  const oben = REGENWOLKE.map((z) => z.replaceAll('H', h).replaceAll('M', m).replaceAll('S', s).replaceAll('B', b));
  return [...oben, ...unten].join('\n');
}

export default [
  uiSymbol('ui_wetter_klar', [
    `................
     .......UU.......
     ..UU...UU...UU..
     ..UU........UU..
     ......kkkk......
     .....kVVVVk.....
     ....kVvvvvVk....
     .UU.kvvvvvvk.UU.
     .UU.kvvvvvvk.UU.
     ....kUvvvvUk....
     .....kUUUUk.....
     ......kkkk......
     ..UU........UU..
     ..UU...UU...UU..
     .......UU.......
     ................`,
  ]),
  uiSymbol(
    'ui_wetter_klar_nacht',
    [
      `................
       ................
       ......kkk..k....
       ....kk###kkDk...
       ...k##0kkkDEDk..
       ..k#00k...kDk...
       .k#00k.....k....
       .k#00k..........
       .k#00k..........
       .k#09k....k.....
       .k#09k...kDk....
       ..k#09k.kDEDk...
       ...k909kkkDk....
       ....kk999kk.....
       ......kkk.......
       ................`,
    ],
    { einzelpixel: 'Sternmitte als heller Einzelpunkt im Kreuz aus Strahlen' },
  ),
  uiSymbol('ui_wetter_bewoelkt', [
    `................
     ...kkk..........
     ..k555k.........
     .k54445kkkk.....
     .k4333k####k....
     .k3kkk#0000#k...
     ..k###000000#k..
     .k#0000000000#k.
     .k000000000000k.
     .k899999999998k.
     ..k8888888888k..
     ...kkkkkkkkkk...
     ................
     ................
     ................
     ................`,
  ]),
  uiSymbol('ui_wetter_nebel', [
    `................
     ................
     ...kkkkkkkkk....
     ..k000000000k...
     ..k999999999k...
     ..kkkkkkkkkkkk..
     .k00000000k000k.
     .k99999999k999k.
     ..kkkkkkkkkkkk..
     ...k0000000000k.
     ...k9999999999k.
     ..kkkkkkkkkkkk..
     .k000000000k....
     .k999999999k....
     ..kkkkkkkkk.....
     ................`,
  ]),
  uiSymbol('ui_wetter_niesel', [
    wolke('#', '0', '9', '8', [
      '................',
      '....Z......Z....',
      '....Z...Z..Z....',
      '........Z.......',
      '................',
      '................',
    ]),
  ]),
  uiSymbol('ui_wetter_regen', [
    wolke('5', '4', '3', '2', [
      '.......Z.....Z..',
      '....Z..Z..Z..Z..',
      '....Z.Z...Z.Z...',
      '...Z.....Z......',
      '................',
      '................',
    ]),
  ]),
  uiSymbol('ui_wetter_gewitter', [
    `................
     .......kkkk.....
     ......k4444k....
     ...kkk433334k...
     ..k4443333334k..
     .k433333333334k.
     .k3333333kk333k.
     .k122222kVvk21k.
     ..k1111kVvk11k..
     ...kkkkVVkkkk...
     .....kVVVvk.Z...
     ...Z..kVvk..Z...
     ...Z.kVvk..Z....
     ..Z..kvk........
     ......k.........
     ................`,
  ]),
  uiSymbol('ui_wetter_schnee', [
    wolke('#', '0', '9', '8', [
      '....0.......0...',
      '...0#0.....0#0..',
      '....0...0...0...',
      '.......0#0......',
      '........0.......',
      '................',
    ]),
  ]),
  uiSymbol('ui_wetter_schneesturm', [
    wolke('5', '4', '3', '2', [
      '..........0.....',
      '.99999...0#0....',
      '....0.....0.....',
      '...0#0..999999..',
      '....0...........',
      '................',
    ]),
  ]),
  uiSymbol('ui_wetter_hitzewelle', [
    `................
     ......kkk.......
     .....kVVVk......
     ....kVvvvVk.....
     ...kVvvvvvVk....
     ...kvvvvvvvk....
     ...kUvvvvvUk....
     ....kUvvvUk.....
     .....kUUUk......
     ......kkk.......
     ................
     ..UU..UU..UU....
     ....UU..UU..UU..
     ..uu..uu..uu....
     ....uu..uu..uu..
     ................`,
  ]),
  uiSymbol('ui_wetter_sandsturm', [
    `................
     ................
     ........DD...EE.
     .......D..D.....
     ..........D.....
     .DDDDDDDDD......
     ................
     ..CCCCCCCCCC....
     ............C...
     ........C...C...
     .........CCC....
     ................
     ...BBBBBB..EE...
     ................
     .EE......EE.....
     ................`,
  ]),
  uiSymbol('ui_wetter_ascheregen', [
    wolke('3', '2', '1', 'n', [
      '..55...U....U...',
      '.......U....U...',
      '....U.....55....',
      '....U..55.......',
      '...........55...',
      '................',
    ]),
  ]),
  uiSymbol(
    'ui_wetter_sternschnuppennacht',
    [
      `................
       ...........k....
       ..0.......kvk...
       .0#0.....kkVkk..
       ..0.....kvVVVvk.
       .........kkVkk..
       ........EEkvk...
       .......EE..k....
       ......00........
       .....00.........
       ....99......0...
       ...99......0#0..
       ............0...
       ................
       ................
       ................`,
    ],
    { einzelpixel: 'Sternmitte als heller Einzelpunkt im Kreuz aus Strahlen' },
  ),
];
