/**
 * Gerbrahmen (M6-31; Verarbeitungsstation `gerbrahmen`, src/content/stations.ts; MASTERPROMPT §15.1 „Gerbrahmen“):
 * `obj_gerbrahmen` und `icon_gerbrahmen`. Stellfläche 2×1 (Zelle 32×36, Anker = Mitte der Vorderkante, Zeile 34).
 *
 * Aufrechter Holzrahmen aus zwei Pfosten und zwei Querbalken; darunter ein Trog mit Rindenlohe. Zustände (Clips wie die
 * anderen Verarbeitungsstationen, src/render/game/stations.ts):
 * - `leer`: lose Schnüre hängen im leeren Rahmen;
 * - `belegt`: ein rohes Fell ist rundum eingeschnürt (Haarstrich in dunklem `erde`);
 * - `arbeitet` (4 fps): dasselbe Fell, von dem Lohe in den Trog tropft;
 * - `fertig`: glattes, helles gegerbtes Leder im Rahmen.
 */
import { icon } from "../icons/_icon";
import { station } from "./_stationen";

const LEER = `................................
  ................................
  ................................
  .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
  .kddddddddddddddddddddddddddddk.
  .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
  ...kdk...D....D...D...D...kdk...
  ...kdk...D....D...D...D...kdk...
  ...kdk...D....D...D...D...kdk...
  ...kdk...D....D...D...D...kdk...
  ...kdk....................kdk...
  ...kdk....................kdk...
  ...kdkDDD.................kdk...
  ...kdk....................kdk...
  ...kdk....................kdk...
  ...kdk....................kdk...
  ...kdk....................kdk...
  ...kdkDDD.................kdk...
  ...kdk....................kdk...
  ...kdk....................kdk...
  ...kdk....................kdk...
  ...kdk....................kdk...
  ...kdk....................kdk...
  ...kdk....................kdk...
  .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
  .kddddddddddddddddddddddddddddk.
  .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
  ...kdk....kkkkkkkkkkkk....kdk...
  ...kdk....kppppppppppk....kdk...
  ...kdk....kccbccccccck....kdk...
  ...kdk....kcccccccbcck....kdk...
  ...kdk....kkkkkkkkkkkk....kdk...
  .kkkkkkk................kkkkkkk.
  .kccccck................kccccck.
  .kkkkkkk................kkkkkkk.
  ................................`;

const FELL = `................................
  ................................
  ................................
  .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
  .kddddddddddddddddddddddddddddk.
  .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
  ...kdk....D....D....D.....kdk...
  ...kdk..kkkkkkkkkkkkkkkk..kdk...
  ...kdk.krqrrsrqrrrrqrsrrk.kdk...
  ...kdkDqrsrrqrrrrqsrrrqrrDkdk...
  ...kdkkrrrqrrrrqrrrrqrrrskkdk...
  ...kdk.kqrrrsqrrrrqrrsrqk.kdk...
  ...kdk.krsrqrrrrqrsrrqrrk.kdk...
  ...kdkDrrqrrrrqsrrrqrrrrqDkdk...
  ...kdkkqrrrrqrrrrqrrrsqrrkkdk...
  ...kdk.krsqrrrrqrrsrqrrrk.kdk...
  ...kdk.kqrrrrqrsrrqrrrrqk.kdk...
  ...kdkDrrrrqsrrrqrrrrqrrrDkdk...
  ...kdk.krqrrrrqrrrsqrrrrk.kdk...
  ...kdk..krrrqrrsrqrrrrqk..kdk...
  ...kdk...kqrsrrqrrrrqsk...kdk...
  ...kdk....kkkkkkkkkkkk....kdk...
  ...kdk....................kdk...
  ...kdk....................kdk...
  .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
  .kddddddddddddddddddddddddddddk.
  .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
  ...kdk....kkkkkkkkkkkk....kdk...
  ...kdk....kppppppppppk....kdk...
  ...kdk....kccbccccccck....kdk...
  ...kdk....kcccccccbcck....kdk...
  ...kdk....kkkkkkkkkkkk....kdk...
  .kkkkkkk................kkkkkkk.
  .kccccck................kccccck.
  .kkkkkkk................kkkkkkk.
  ................................`;

const TROPFEN_1 = `................................
  ................................
  ................................
  .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
  .kddddddddddddddddddddddddddddk.
  .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
  ...kdk....D....D....D.....kdk...
  ...kdk..kkkkkkkkkkkkkkkk..kdk...
  ...kdk.krqrrsrqrrrrqrsrrk.kdk...
  ...kdkDqrsrrqrrrrqsrrrqrrDkdk...
  ...kdkkrrrqrrrrqrrrrqrrrskkdk...
  ...kdk.kqrrrsqrrrrqrrsrqk.kdk...
  ...kdk.krsrqrrrrqrsrrqrrk.kdk...
  ...kdkDrrqrrrrqsrrrqrrrrqDkdk...
  ...kdkkqrrrrqrrrrqrrrsqrrkkdk...
  ...kdk.krsqrrrrqrrsrqrrrk.kdk...
  ...kdk.kqrrrrqrsrrqrrrrqk.kdk...
  ...kdkDrrrrqsrrrqrrrrqrrrDkdk...
  ...kdk.krqrrrrqrrrsqrrrrk.kdk...
  ...kdk..krrrqrrsrqrrrrqk..kdk...
  ...kdk...kqrsrrqrrrrqsk...kdk...
  ...kdk....kkkkkkkkkkkk....kdk...
  ...kdk....................kdk...
  ...kdk.........q..........kdk...
  .kkkkkkkkkkkkkkpkkkkkkkkkkkkkkk.
  .kddddddddddddddddddddddddddddk.
  .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
  ...kdk....kkkkkkkkkkkk....kdk...
  ...kdk....kppppppppppk....kdk...
  ...kdk....kccbccccccck....kdk...
  ...kdk....kcccccccbcck....kdk...
  ...kdk....kkkkkkkkkkkk....kdk...
  .kkkkkkk................kkkkkkk.
  .kccccck................kccccck.
  .kkkkkkk................kkkkkkk.
  ................................`;

const TROPFEN_2 = `................................
  ................................
  ................................
  .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
  .kddddddddddddddddddddddddddddk.
  .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
  ...kdk....D....D....D.....kdk...
  ...kdk..kkkkkkkkkkkkkkkk..kdk...
  ...kdk.krqrrsrqrrrrqrsrrk.kdk...
  ...kdkDqrsrrqrrrrqsrrrqrrDkdk...
  ...kdkkrrrqrrrrqrrrrqrrrskkdk...
  ...kdk.kqrrrsqrrrrqrrsrqk.kdk...
  ...kdk.krsrqrrrrqrsrrqrrk.kdk...
  ...kdkDrrqrrrrqsrrrqrrrrqDkdk...
  ...kdkkqrrrrqrrrrqrrrsqrrkkdk...
  ...kdk.krsqrrrrqrrsrqrrrk.kdk...
  ...kdk.kqrrrrqrsrrqrrrrqk.kdk...
  ...kdkDrrrrqsrrrqrrrrqrrrDkdk...
  ...kdk.krqrrrrqrrrsqrrrrk.kdk...
  ...kdk..krrrqrrsrqrrrrqk..kdk...
  ...kdk...kqrsrrqrrrrqsk...kdk...
  ...kdk....kkkkkkkkkkkk....kdk...
  ...kdk....................kdk...
  ...kdk....................kdk...
  .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
  .kdddddddddddddqddddddddddddddk.
  .kkkkkkkkkkkkkkpkkkkkkkkkkkkkkk.
  ...kdk....kkkkkkkkkkkk....kdk...
  ...kdk....kppppppppppk....kdk...
  ...kdk....kccbccccccck....kdk...
  ...kdk....kcccccccbcck....kdk...
  ...kdk....kkkkkkkkkkkk....kdk...
  .kkkkkkk................kkkkkkk.
  .kccccck................kccccck.
  .kkkkkkk................kkkkkkk.
  ................................`;

const LEDER = `................................
  ................................
  ................................
  .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
  .kddddddddddddddddddddddddddddk.
  .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
  ...kdk....D....D....D.....kdk...
  ...kdk..kkkkkkkkkkkkkkkk..kdk...
  ...kdk.ksssstsssssssstssk.kdk...
  ...kdkDsstsssssssstssssssDkdk...
  ...kdkksssssssstsssssssstkkdk...
  ...kdk.ksssstsssssssstssk.kdk...
  ...kdk.kstsssssssstsssssk.kdk...
  ...kdkDsssssssstsssssssstDkdk...
  ...kdkkssssstsssssssstssskkdk...
  ...kdk.kstsssssssstsssssk.kdk...
  ...kdk.kssssssstssssssssk.kdk...
  ...kdkDssssstsssssssstsssDkdk...
  ...kdk.kstsssssssstsssssk.kdk...
  ...kdk..ksssssstsssssssk..kdk...
  ...kdk...ksstsssssssstk...kdk...
  ...kdk....kkkkkkkkkkkk....kdk...
  ...kdk....................kdk...
  ...kdk....................kdk...
  .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
  .kddddddddddddddddddddddddddddk.
  .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
  ...kdk....kkkkkkkkkkkk....kdk...
  ...kdk....kppppppppppk....kdk...
  ...kdk....kccbccccccck....kdk...
  ...kdk....kcccccccbcck....kdk...
  ...kdk....kkkkkkkkkkkk....kdk...
  .kkkkkkk................kkkkkkk.
  .kccccck................kccccck.
  .kkkkkkk................kkkkkkk.
  ................................`;

export default [
  station({
    item: "gerbrahmen",
    size: [32, 36],
    anchor: [16, 34],
    hoehe: "block",
    frames: [LEER, FELL, TROPFEN_1, TROPFEN_2, LEDER],
    clips: {
      leer: { frames: [0], fps: 1, loop: true },
      belegt: { frames: [1], fps: 1, loop: true },
      arbeitet: { frames: [1, 2, 3, 1], fps: 4, loop: true },
      fertig: { frames: [4], fps: 1, loop: true },
    },
    sockets: { arbeit: [[16, 14]] },
    hitbox: [0, 2, 32, 32],
    occluder: { kind: "rect", x: 2, y: 22, w: 28, h: 12 },
  }),
  icon(
    "gerbrahmen",
    `................
     .kk..........kk.
     .kdkkkkkkkkkkdk.
     .kckDkkkkkkDkck.
     .kdkkrssssrkkdk.
     .kckDrsttsrDkck.
     .kdkkrsttssrkdk.
     .kckDrssstsDkck.
     .kdkkrssssrkkdk.
     .kckDkkkkkkDkck.
     .kdkkkkkkkkkkdk.
     .kck........kck.
     .kbk.kkkkkk.kbk.
     .kkk.kbccbk.kkk.
     .....kkkkkk.....
     ................`,
  ),
];
