/**
 * Stationen T0 (M4-05, docs/SPIEL.md §8, MASTERPROMPT §15): `obj_lagerfeuer`, `obj_werkbank`,
 * `obj_saegebock`, `obj_steinmetzbank`, `obj_trockengestell`, `obj_koehlermeiler`, `obj_lehmofen`.
 * Stellflächen (Vorschlag für die Stationsdaten, Anker = Mitte der Vorderkante): Lagerfeuer 2×2,
 * Werkbank 2×1, Sägebock 2×1, Steinmetzbank 2×1, Trockengestell 2×1, Köhlermeiler 2×2, Lehmofen 2×2.
 *
 * - **Lagerfeuer als Station:** dasselbe Feuer wie das platzierte Lagerfeuer (`lagerfeuer`, alle Clips),
 *   dazu `arbeitet`: ein Bratspieß auf zwei Astgabeln über den Flammen (Kochen, §18).
 * - **Werkbank I:** die Werkbank aus M3-16 (Bohlenplatte, Steinamboss, Steinhammer).
 * - **Sägebock:** zwei Kreuzböcke, darauf ein Stamm mit Sägeschnitt und steckender Bügelsäge, darunter
 *   Sägemehl.
 * - **Steinmetzbank:** schwere Bank, darauf ein Werkblock – links schon glatt gespitzt, rechts noch
 *   bruchrau – und ein Holzklüpfel; Steinsplitter am Boden.
 * - **Trockengestell:** zwei Pfosten mit zwei Stangen; `leer`, `belegt` (Kräuterbünde, Fasern,
 *   Fleischstreifen), `arbeitet` = belegt, die Bünde pendeln im Wind (Materialflag `wind`).
 * - **Köhlermeiler:** mit Soden gedeckter Erdhügel; `aus` kalt, `brennt` glimmt aus Fußlöchern und
 *   Rauchloch (emissiv, langsamer Puls), `fertig` aufgebrochen, Holzkohle liegt frei.
 * - **Lehmofen:** Bienenkorb-Kuppel aus Lehm auf einem Feldsteinsockel, Schürloch mit Rundbogen,
 *   Abzug oben; `brennt` mit Flammen im Schürloch (10 fps) und Glut im Abzug.
 */
import { spriteMeta } from '../../lib/recolor';
import { resolveColor, spriteFromPixels, type PixelFrameInput, type Sprite, type SpriteFrame } from '../../lib/sprite';
import lagerfeuer from '../platzierbar/lagerfeuer';
import werkbank from '../platzierbar/werkbank';
import { OBJ_PRAEFIX, STATIONEN_GRUPPE, station, ueber } from './_stationen';

// ---------------------------------------------------------------------------------------------
// Lagerfeuer und Werkbank I (aus M3-16)
// ---------------------------------------------------------------------------------------------

/** Legt ein Raster (`.` = Grundbild bleibt) mit eigener Legende über einen Frame. */
function ueberlagert(f: SpriteFrame, w: number, raster: string, legende: Readonly<Record<string, string>>): PixelFrameInput {
  const index = Uint8Array.from(f.index);
  const emissive = Uint8Array.from(f.emissive);
  const material = Uint8Array.from(f.material);
  raster
    .split('\n')
    .map((z) => z.trim())
    .filter((z) => z.length > 0)
    .forEach((z, y) => {
      for (let x = 0; x < z.length; x++) {
        const ref = legende[z.charAt(x)];
        if (ref === undefined) continue;
        const r = resolveColor(ref);
        if ('error' in r) throw new Error(`Überlagerung: ${r.error}`);
        const p = y * w + x;
        index[p] = r.index;
        emissive[p] = r.emissive ? 1 : 0;
        material[p] = 0;
      }
    });
  return { index, emissive, material };
}

/** Bratspieß auf zwei Astgabeln, mittig ein Braten (Farben des Lagerfeuers: nur Holz und Kontur). */
const SPIESS = `................................
                ................................
                ................................
                ................................
                ...kk...................kk......
                ...kdk.kk..........kk..kdk......
                ....kdkdk..........kdkkdk.......
                ....kkdkkkkkkkkkkkkkkkdkk.......
                ....kddcccccckkkkccccccddk......
                .....kdkkkkkkbbbbkkkkkkdk.......
                .....kdk....kbccdbk....kdk......
                .....kdk....kbcdcbk....kdk......
                .....kdk.....kbbbk.....kdk......
                .....kdk......kkk......kdk......
                .....kdk...............kdk......
                .....kdk...............kdk......
                .....kbk...............kbk......
                .....kbk...............kbk......
                ......k.................k.......
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................`;
const SPIESS_LEGENDE = { k: 'nacht.1', b: 'holz.1', c: 'holz.2', d: 'holz.3' } as const;

/** Zusatzframes einer Station: je Frame das Bild und der Quellframe, dessen Sockel er übernimmt. */
interface Zusatz {
  readonly bild: PixelFrameInput;
  readonly quelle: number;
}

/** Kopie eines M3-Sprites als Station `obj_<id>` in der Gruppe `stationen`, optional mit Zusatzframes. */
function alsStation(s: Sprite, zusatz: readonly Zusatz[] = [], zusatzClips: Readonly<Record<string, { frames: number[]; fps: number; loop: boolean }>> = {}): Sprite {
  const meta = spriteMeta(s, `${OBJ_PRAEFIX}${s.id}`);
  const frames: PixelFrameInput[] = [...s.frames.map((f) => ({ index: f.index, emissive: f.emissive, material: f.material, heightOverride: f.heightOverride })), ...zusatz.map((z) => z.bild)];
  const sockets = Object.fromEntries(Object.entries(s.sockets).map(([k, pts]) => [k, [...pts, ...zusatz.map((z) => pts[z.quelle] ?? pts[0] ?? [0, 0])].map((p) => [p[0], p[1]] as [number, number])]));
  // A station may stand mirrored (the build mode's F), like every station of `station()` (_stationen.ts).
  return spriteFromPixels({ ...meta, spiegelbar: true, group: STATIONEN_GRUPPE, clips: { ...meta.clips, ...zusatzClips }, sockets }, frames);
}

const brennt = lagerfeuer.clips.brennt?.frames ?? [];
const obj_lagerfeuer = alsStation(
  lagerfeuer,
  brennt.map((i) => {
    const f = lagerfeuer.frames[i];
    if (f === undefined) throw new Error(`lagerfeuer: Frame ${i} fehlt`);
    return { bild: ueberlagert(f, lagerfeuer.w, SPIESS, SPIESS_LEGENDE), quelle: i };
  }),
  { arbeitet: { frames: brennt.map((_, i) => lagerfeuer.frames.length + i), fps: 12, loop: true } },
);

const obj_werkbank = alsStation(werkbank);

// ---------------------------------------------------------------------------------------------
// Sägebock
// ---------------------------------------------------------------------------------------------

const saegebock = station({
  item: 'saegebock',
  size: [32, 32],
  anchor: [16, 30],
  hoehe: 'block',
  frames: [
    `................................
     ................................
     ............kkkkkkkk............
     ............kdCDDCdk............
     ............kdkkkkdk............
     ............kdk..kdk............
     ............kdkkkkdk............
     .kk......kk.kcddddck.kk......kk.
     kdck....kcdkkck..kckkdck....kcdk
     .kkkkkkkkkkkk455554kkkkkkkkkkkk.
     kddcdddeddcddcdaadcddeddcdddcddk
     kcdcccdcccdccdcaacdcccdcccdcccdk
     kccbcccccbcccccaaccbcccccbccccbk
     kbcccbccbcccbccabbcccbcccbccbcbk
     kbbbabbbbbabbbbbbbbbbbabbbbbabbk
     .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
     ...kcbbck..............kcbbck...
     ...kcbbck..............kcbbck...
     ...kcbbck..............kcbbck...
     ..kcbkkbck............kcbkkbck..
     ..kcbkkbck............kcbkkbck..
     ..kcbkkbck............kcbkkbck..
     .kcbk..kbck..........kcbk..kbck.
     .kcbk..kbck..........kcbk..kbck.
     .kcbk..kbck..........kcbk..kbck.
     kcbk....kbck........kcbk....kbck
     kcbk....kbck..kkkk..kcbk....kbck
     kcbk....kbck.keeddk.kcbk....kbck
     cbk......kbckdeeddekcbk......kbc
     cbk......kbckdcddcdkcbk......kbc
     kk........kkkkkkkkkkkk........kk
     ................................`,
  ],
  sockets: { arbeit: [[16, 9]] },
  hitbox: [1, 8, 30, 23],
  occluder: { kind: 'rect', x: 2, y: 22, w: 28, h: 8 },
});

// ---------------------------------------------------------------------------------------------
// Steinmetzbank
// ---------------------------------------------------------------------------------------------

const steinmetzbank = station({
  item: 'steinmetzbank',
  size: [32, 32],
  anchor: [16, 30],
  hoehe: 'block',
  frames: [
    `................................
     ................................
     ................................
     ................................
     .......kkkkkkkkkkkkkkk..........
     .......k5566555665565k..........
     .......k5655565556555k..........
     .......k4555555455554k..........
     .......k4444343443343k..........
     .......k4444334343433k.kkkkk....
     .......k4454343334434kkddcddk...
     .......k4444433434343kkcccbckkkk
     .......k3333323333232kkbbbbbkcbk
     .kkkkkkk2222222222222kkkkkkkkkkk
     .kddeedddddeeddddddeedddddedddk.
     .kcddddcdddddddcddddddcddddddck.
     .kcccbcccccbccccccccbcccccbccck.
     .kbbbbbbbbbbbbbbbbbbbbbbbbbbbbk.
     .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
     ...kcdcbk..............kcdcbk...
     ...kcdcbk..............kcdcbk...
     ...kcdcbk..............kcdcbk...
     ...kcdcbk..............kcdcbk...
     ...kcdcbkkkkkkkkkkkkkkkkcdcbk...
     ...kcdcbkdddcddddddcdddkcdcbk...
     ...kcdcbkbbbbbbbbbbbbbbkcdcbk...
     ...kcdcbkkkkkkkkkkkkkkkkcdcbk...
     ...kcdcbk...kkk....kk..kcdcbk...
     ...kcdcbk..k454k..k43k.kcdcbk...
     ...kbbbak..k3333kk332k.kbbbak...
     ...kkkkkk...kkkkkkkkk..kkkkkk...
     ................................`,
  ],
  sockets: { arbeit: [[14, 6]] },
  hitbox: [1, 4, 30, 27],
  occluder: { kind: 'rect', x: 2, y: 18, w: 28, h: 12 },
});

// ---------------------------------------------------------------------------------------------
// Trockengestell
// ---------------------------------------------------------------------------------------------

const GESTELL = `................................
                 ................................
                 ................................
                 ................................
                 ..kkkk....................kkkk..
                 ..kdck....................kdck..
                 ..kdckkkkkkkkkkkkkkkkkkkkkkdck..
                 ..kdcdddeddddddddeddddddddkdck..
                 ..kdcbbbbbbcbbbbbbbbbcbbbbkdck..
                 ..kdckkkkkkkkkkkkkkkkkkkkkkdck..
                 ..kdck....................kdck..
                 ..kdck....................kdck..
                 ..kdck....................kdck..
                 ..kdck....................kdck..
                 ..kdck....................kdck..
                 ..kdckkkkkkkkkkkkkkkkkkkkkkdck..
                 ..kdcddddddddedddddddddeddkdck..
                 ..kdcbbbbcbbbbbbbbbbcbbbbbkdck..
                 ..kdckkkkkkkkkkkkkkkkkkkkkkdck..
                 ..kdck....................kdck..
                 ..kdck....................kdck..
                 ..kdck....................kdck..
                 ..kdck....................kdck..
                 ..kdck....................kdck..
                 ..kdck....................kdck..
                 ..kdck....................kdck..
                 ..kdck....................kdck..
                 ..kdck....................kdck..
                 .kbdck....................kdcbk.
                 kbbdcbk..................kbdcbbk
                 kkkkkkk..................kkkkkkk
                 ................................`;

/** Bünde an beiden Stangen (Kräuter grün, Fasern hell, Fleischstreifen rot). */
const BUENDE = `................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ......kDDk....kDDk....klk.klk...
                .....khihk...kDEDDk...kmk.kmk...
                .....kiijhk..kDDEDk...kmkkmmk...
                ....khijiihk.kDEDDk...kmkkmk....
                ....khiijihk.kDDEDk...kmkkmk....
                .....khhihk..kkDEDk...kmk.kk....
                ......kkkk.....kkk.....k........
                ................................
                ................................
                ..........kDDk......kDDk........
                .........khihk.....kDEDk........
                ........khiijhk....kDDEDk.......
                ........khjiihk....kDEDDk.......
                .........khihk.....kDDEDk.......
                ..........kkk......kkDDk........
                ....................kkk.........
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................`;

/** Dieselben Bünde, unten 1 px nach rechts gependelt. */
const BUENDE_WIND = `................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ......kDDk....kDDk....klk.klk...
                     .....khihk....kDEDk...kmk.kmk...
                     .....kiijhk...kDDEDk..kmkkmmk...
                     .....khijiihk.kDEDDk...kmkkmk...
                     .....khiijihk.kDDEDk...kmkkmk...
                     ......khhihk...kDEDk...kmk.kk...
                     .......kkkk.....kkk.....k.......
                     ................................
                     ................................
                     ..........kDDk......kDDk........
                     ..........khihk.....kDEDk.......
                     .........khiijhk....kDDEDk......
                     .........khjiihk....kDEDDk......
                     ..........khihk.....kDDEDk......
                     ...........kkk......kkDDk.......
                     .....................kkk........
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................`;

const trockengestell = station({
  item: 'trockengestell',
  size: [32, 32],
  anchor: [16, 30],
  hoehe: 'block',
  frames: [GESTELL, ueber(GESTELL, BUENDE), ueber(GESTELL, BUENDE_WIND)],
  clips: {
    leer: { frames: [0], fps: 1, loop: true },
    belegt: { frames: [1], fps: 1, loop: true },
    arbeitet: { frames: [1, 1, 2, 2], fps: 3, loop: true },
  },
  material: { wind: 'hijDElm' },
  sockets: { arbeit: [[16, 15]] },
  hitbox: [1, 6, 30, 25],
  occluder: { kind: 'rect', x: 2, y: 26, w: 28, h: 4 },
});

// ---------------------------------------------------------------------------------------------
// Köhlermeiler
// ---------------------------------------------------------------------------------------------

const MEILER = `................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................
                ............kkkkkkkk............
                ..........kkthhiktttkk..........
                ........kkttthikkktsttkk........
                .......ktsttthhhitsttstsk.......
                ......ktsstshihhsstsstsssk......
                .....ktssshiihsststssshisrk.....
                ....ktsssshhissssstssshiisrk....
                ....ktsssssssrsssssssssshsrk....
                ...ktssrsssssssssrssssssssrrk...
                ...ksssrsshhissssssssrsssrrrk...
                ...ksrssshiihsssssssssssrsrrk...
                ..ksssrssssssssrsssshhisssrrrk..
                ..ksrssssrssssssssshiihssrsrrk..
                ..kssssssssssrsssssssssssrsrrk..
                ..krsssrssssssssssrsssssrsrrqk..
                ..krrssssssrssssssssssrssrrrqk..
                ..krrrsssssssssssrsssssssrrqqk..
                ..krrrrssrsssssssssssrssrrrqqk..
                ..kqrrkkrrrrsskkrsrrrrkkrrqqqk..
                ..kqqrkkrrrrrrkkrrrrrrkkrrqqqk..
                ..kqqrrrqrrrrrrrrrrqrrrrrqqqqk..
                ..kqqqqqqqqqrrqqqqqqqqqqqqqqqk..
                ...kqqqqqqqqqqqqqqqqqqqqqqqqk...
                ....kkkkkkkkkkkkkkkkkkkkkkkk....
                ................................`;

/** Glut aus Rauch- und Fußlöchern (zwei Helligkeiten für den Puls). */
const MEILER_GLUT_HELL = `................................
                          ................................
                          ................................
                          ................................
                          ................................
                          ................................
                          ................................
                          ................................
                          ...............+................
                          ..............+==+..............
                          ................................
                          ................................
                          ................................
                          ................................
                          ................................
                          ................................
                          ................................
                          ................................
                          ................................
                          ................................
                          ................................
                          ................................
                          ................................
                          ................................
                          ................................
                          ......}+.......+=.......}+......
                          ......+=.......==.......+=......
                          ................................
                          ................................
                          ................................
                          ................................
                          ................................`;

/** Dunklerer Puls: jede Glutstufe eine Stufe tiefer. */
const TIEFER: Readonly<Record<string, string>> = { '=': '+', '+': '}' };
const MEILER_GLUT_MATT = [...MEILER_GLUT_HELL].map((c) => TIEFER[c] ?? c).join('');

/** Aufgebrochen: die Soden sind oben abgeräumt, die fertige Holzkohle liegt frei. */
const MEILER_FERTIG = `................................
                      ................................
                      ................................
                      ................................
                      ................................
                      ................................
                      ................................
                      ................................
                      ................................
                      ................................
                      ................................
                      ...........kkk..kkkk............
                      .........kkNnkkkNNnnkk..........
                      ........kNnnkNNkknnnNkkk........
                      .......knnkNNnnkNnkknnNnk.......
                      ......kNnkNnnkknnnkNNnknnk......
                      .....knnkkNnkNNkknkNnnkNnnk.....
                      ....kNNnkNnnkNnnkkNnkNnkNnnk....
                      ...kssknnkkNnnkNNnkknnkNnksrk...
                      ..ksrssknkNnkkNnnkNNnkkknssrrk..
                      ..kssrsskkkkNnnkknnkkkkssrsrrk..
                      ..krsssssrskkkkkkkkssssssrrrqk..
                      ..krrssssssrsssssssssrssrrrrqk..
                      ..krrrsssssssssssrsssssssrrqqk..
                      ..krrrrssrsssssssssssrssrrrqqk..
                      ..kqrrkkrrrrsskkrsrrrrkkrrqqqk..
                      ..kqqrkkrrrrrrkkrrrrrrkkrrqqqk..
                      ..kqqrrrqrrrrrrrrrrqrrrrrqqqqk..
                      ..kqqqqqqqqqrrqqqqqqqqqqqqqqqk..
                      ...kqqqqqqqqqqqqqqqqqqqqqqqqk...
                      ....kkkkkkkkkkkkkkkkkkkkkkkk....
                      ................................`;

const koehlermeiler = station({
  item: 'koehlermeiler',
  size: [32, 32],
  anchor: [16, 30],
  hoehe: 'kugel',
  frames: [MEILER, ueber(MEILER, MEILER_GLUT_MATT), ueber(MEILER, MEILER_GLUT_HELL), MEILER_FERTIG],
  clips: {
    aus: { frames: [0], fps: 1, loop: true },
    brennt: { frames: [1, 1, 2, 2, 2, 1], fps: 4, loop: true },
    fertig: { frames: [3], fps: 1, loop: true },
  },
  sockets: { licht: [[16, 9]], arbeit: [[16, 21]] },
  einzelpixel: 'Glutpunkte in Rauch- und Fußlöchern sind einzelne leuchtende Pixel',
  hitbox: [2, 6, 28, 24],
  occluder: { kind: 'ellipse', x: 16, y: 26, rx: 13, ry: 4 },
});

// ---------------------------------------------------------------------------------------------
// Lehmofen
// ---------------------------------------------------------------------------------------------

const OFEN = `................................
               ................................
               ................................
               .............kkkkkk.............
               ............kqkkkkqk............
               ..........kkDqkkkkqDkk..........
               .........kDDDEqqqqEDDDk.........
               ........kDDDEEDDDDEEDDDk........
               .......kDDEEDDDDDDDDEDDDk.......
               ......kDDEEDDDDDCDDDDDDDCk......
               .....kCDDEDDDDDDCCDDDDDDDCk.....
               .....kCDDDDDDDDDDCDDDDDDDCk.....
               ....kCDDDDqDDDDDDDDDDDDDDDCk....
               ....kCDDDDDqqDDDDDDDDDDDDDCk....
               ....kCCDDDDDDqDDDDDDDDDCDDCk....
               ...kCCDDDDDDDDDDDDDDDDDDCDCCk...
               ...kCCDDDDDDDDDDDDDDDDDDDDCCk...
               ...kCCCDDDDDDDDDDDDDDDDDDDCCk...
               ...kBCCDDDDDDDDDDDDDDqDDDCCBk...
               ...kBCCCDDDDDDDDDDDDDDqqDCCBk...
               ...kBBCCDDDDDkkkkkkDDDDDCCBBk...
               ...kBBCCCDDDkBCCCCBkDDDCCCBBk...
               ...kBBCCCDDkBCkkkkCBkDCCCCBBk...
               ...kBBBCCCDkCkkkkkkCkCCCCBBBk...
               ...kqBBCCCCkCkkkkkkCkCCCBBBqk...
               ...kqqBBBCCkCkkkkkkCkCCBBBqqk...
               ...kkqqBBBBkCkkkkkkCkBBBBqqkk...
               ..k44444kkkkCkkkkkkCkkkk44444k..
               ..k3434434k4CkkkkkkC4k4344334k..
               ..k3333433k3kkkkkkkk3k3343333k..
               ..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..
               ................................`;

/** Flammen im Schürloch (vier Formen) und Glut im Abzug. */
function ofenFeuer(flammen: readonly string[]): string {
  const leer = '................................';
  const zeilen = Array.from({ length: 32 }, () => leer);
  zeilen[4] = '..............}}}}..............';
  flammen.forEach((z, i) => {
    zeilen[22 + i] = `............${z}............`;
  });
  return zeilen.join('\n');
}

const FEUER = [
  ofenFeuer(['........', '..}.}...', '.}+}+}..', '.+=+=+}.', '.+=@@=+.', '.=@@@@=.', '........']),
  ofenFeuer(['........', '...}.}..', '..}+}+}.', '.}+=+=+.', '.+=@@=+.', '.=@@@@=.', '........']),
  ofenFeuer(['........', '..}..}..', '.}+}}+}.', '.+=++=+.', '.+=@@=+.', '.=@@@@=.', '........']),
  ofenFeuer(['........', '........', '.}}+}}..', '.}+=+=}.', '.+=@@=+.', '.=@@@@=.', '........']),
];

const lehmofen = station({
  item: 'lehmofen',
  size: [32, 32],
  anchor: [16, 30],
  hoehe: 'kugel',
  frames: [OFEN, ...FEUER.map((f) => ueber(OFEN, f))],
  clips: {
    aus: { frames: [0], fps: 1, loop: true },
    brennt: { frames: [1, 2, 3, 4, 2, 3], fps: 10, loop: true },
  },
  sockets: { licht: [[15, 26]], arbeit: [[16, 24]] },
  hitbox: [2, 3, 28, 28],
  occluder: { kind: 'ellipse', x: 16, y: 26, rx: 13, ry: 4 },
});

export default [obj_lagerfeuer, obj_werkbank, saegebock, steinmetzbank, trockengestell, koehlermeiler, lehmofen];
