/**
 * Stationen T1 (M4-06, docs/SPIEL.md §8, MASTERPROMPT §15): `obj_werkbank_2`, `obj_schmelzofen`,
 * `obj_amboss_bronze`, `obj_schleifstein`, `obj_spinnrad`. Stellflächen (Vorschlag für die
 * Stationsdaten, Anker = Mitte der Vorderkante): Werkbank II 2×1, Schmelzofen 2×2, Amboss 1×1,
 * Schleifstein 2×1, Spinnrad 1×1.
 *
 * - **Werkbank II** (Werkzeugwand/Hobelbank): Hobelbank mit Bronze-Vorderzange und Hobel, dahinter
 *   eine Werkzeugwand aus Brettern mit Bügelsäge, Hammer, zwei Stechbeiteln und Winkel.
 * - **Schmelzofen I:** Rennofen – Lehmschacht mit Bindringen auf einem Feldsteinsockel, links ein
 *   Blasebalg mit Düse, vorn der Abstich mit Rundbogen, rechts Schlacke; `brennt`: Flammen an der
 *   Gicht (oben) und glühender Abstich (emissiv, 10 fps), dazu feine Glutrisse.
 * - **Amboss (Bronze):** Bronzeamboss mit Horn auf einem Hackklotz (Materialflag `metall`).
 * - **Schleifstein:** Sandsteinscheibe im Holzbock über einem Wassertrog (Glanzflag `nass`), Kurbel
 *   rechts; `arbeitet`: Kurbel und Scheibenmaserung drehen sich (3 Frames, 10 fps).
 * - **Spinnrad:** großes Rad mit Speichen auf drei Beinen, Spinnrocken mit Wolle, Tretbrett;
 *   `arbeitet`: die Speichen drehen sich (2 Frames, 8 fps).
 */
import { BRONZE, station, ueber } from './_stationen';

// ---------------------------------------------------------------------------------------------
// Werkbank II
// ---------------------------------------------------------------------------------------------

/** Bretter der Werkzeugwand (Fugen bei x 9, 15, 21), vier Zeilenfassungen. */
const BRETTER = ['ccdccbcccdcbcdcccbccccdc', 'cccccbcdcccbccccdbcdcccc', 'cdcccbccccdbccdccbccccdc', 'ccccdbccdccbcccdcbcdcccc'];

function werkzeugwand(): string {
  const leer = '................................';
  const z: string[] = [leer, '...kkkkkkkkkkkkkkkkkkkkkkkkkk...'];
  for (let y = 2; y < 18; y++) z.push(`...k${BRETTER[y % BRETTER.length] ?? ''}k...`);
  for (let y = 18; y < 40; y++) z.push(leer);
  return z.join('\n');
}

const HOBELBANK = `................................
                   ................................
                   ................................
                   ................................
                   ................................
                   ................................
                   ................................
                   ................................
                   ................................
                   ................................
                   ................................
                   ................................
                   ................................
                   ................................
                   ................................
                   ................................
                   ................................
                   ................................
                   ..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..
                   ..keeeeeeeeeeeeceeeeeeeeeeceek..
                   ..kdddddccdddddddddddddededddk..
                   ..kcccddddcccccdddddcccccddddk..
                   ..kdddccccdddddcccccdddddcccck..
                   ..kddddddddddccdddddcccddddddk..
                   ..kddddddddddddddddddddddddddk..
                   ..kcccccccccccccccccccccccccck..
                   ..kbbbbbbbbbbbbbbbbbbbbbbbbbbk..
                   ..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..
                   ...kdcbkk.............kbkdcbk...
                   ...kdcbkk.............kbkdcbk...
                   ...kdcbkkkkkkkkkkkkkkkkbkdcbk...
                   ...kdcbkbbbbbbbbbbbbbbbbkdcbk...
                   ...kdcbkkkkkkkkkkkkkkkkkkdcbk...
                   ...kdcbkcccccccccccccccckdcbk...
                   ...kdcbkbbbbbbbbbbbbbbbbkdcbk...
                   ...kdcbkkkkkkkkkkkkkkkkkkdcbk...
                   ...kdcbk................kdcbk...
                   ...kbbak................kbbak...
                   ...kkkkk................kkkkk...
                   ................................`;

/** Bügelsäge (Griff mit Loch, Blatt). */
const SAEGE = `.kkkk........
               kddddkkkkkkkk
               kdkkd5555554k
               kddddk444444k
               .kkkkkkkkkkk.`;

/** Hammer mit Bronzekopf. */
const HAMMER = `kkkkk
                kTTWk
                kWWQk
                kkdkk
                .kdk.
                .kck.
                .kdk.
                .kdk.
                .kck.
                .kbk.
                ..k..`;

/** Stechbeitel: Heft, Bronzezwinge, Klinge. */
const BEITEL = `kkk
                kdk
                kdk
                kck
                kPk
                k5k
                k5k
                k4k
                .k.`;

/** Anschlagwinkel aus Bronze. */
const WINKEL = `kk.....
                kPk....
                kPk....
                kTk....
                kTkkkkk
                kWPPTTk
                kkkkkkk`;

/** Vorderzange (Bronze) an der linken Vorderkante, Hobel und Späne auf der Platte. */
const ZANGE_HOBEL = `................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     .....kkkkk.........kkkkkk.......
                     .....kTTWk........kdeedck.......
                     .....kTWWk.......kkddddcbkkk....
                     .....kWWQk.......kcccccccbekek..
                     .....kWWQk........kkkkkkkk.kk...
                     .....kQQQk......................
                     ...kkkkPkkkk....................
                     ...kPPPPPPPk....................
                     ...kkkkkkkkk....................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................
                     ................................`;

function werkbank2(): string {
  let r = werkzeugwand();
  r = ueber(r, SAEGE, 5, 4);
  r = ueber(r, HAMMER, 18, 3);
  r = ueber(r, BEITEL, 23, 4);
  r = ueber(r, BEITEL, 25, 5);
  r = ueber(r, WINKEL, 6, 10);
  r = ueber(r, HOBELBANK);
  return ueber(r, ZANGE_HOBEL);
}

const werkbank_2 = station({
  item: 'werkbank_2',
  size: [32, 40],
  anchor: [16, 38],
  hoehe: 'block',
  frames: [werkbank2()],
  material: { metall: BRONZE },
  sockets: { arbeit: [[16, 20]] },
  hitbox: [2, 1, 28, 38],
  occluder: { kind: 'rect', x: 3, y: 28, w: 26, h: 10 },
});

// ---------------------------------------------------------------------------------------------
// Schmelzofen I (Rennofen)
// ---------------------------------------------------------------------------------------------

const OFEN = `................................
               ................................
               ................................
               ................................
               ................................
               ................................
               ...........kkkkkkkkkk...........
               ..........ktqkkkkkkqtk..........
               ..........krrqqqqqqrrk..........
               ..........kttssssssttk..........
               ..........ksssrssssssk..........
               .........kssrsssssssrsk.........
               .........ksssssssrssssk.........
               .........kqqqqqqqqqqqqk.........
               .........ktttttttttttrk.........
               .........ksssssrssssssk.........
               ........kssssssssssrsssk........
               ........kssrssssssssssrk........
               ........ksssssssrssssssk........
               ........ksssssssssssrssk........
               ........kqqqqqqqqqqqqqqk........
               .......ktttttttttttttttrk.......
               .......ksssssrsssssssssrk.......
               .......kssrssssssssrsssrk.......
               .......ksssssssssssssssrk.......
               .......ksssrsssssssrsssrk.......
               ......ksssssssssssssrssssk......
               ......kssrssssssssssssssrk......
               ......kqqqqqqqqqqqqqqqqqqk......
               ......ktttttttttttttttttrk......
               ......ksssssrsssssssssssrk......
               kkkk..kssssssssrssssssssrk......
               kcrrkkksssssssssssssrssrrk......
               krsrrrkkssrssskkkkkssssrrk......
               krrsrqccksssskqqqqkssrsrrk......
               kqrrqkkksssskqkkkkqkssrrrk......
               kkqqk..ksssskqkkkkqksrrrqk......
               .kkk...ksrrrkqkkkkqkrrrqqk......
               ..kkkkkkkkkkkkkkkkkkkkkkkkkkk...
               ..k4443434434344343434344434k...
               ..k3434343343433434343433433k.kk
               ..k3333433333343333433333343kkqk
               ..k3334333343333334333334333kqqk
               ..kkkkkkkkkkkkkkkkkkkkkkkkkkkqqk
               ..k4343443434434434434344343kkkk
               ..k3333333433333333433333333k...
               ..kkkkkkkkkkkkkkkkkkkkkkkkkkk...
               ................................`;

/** Gichtflammen und Abstichglut, vier Formen. */
function schmelzGlut(gicht: readonly string[], abstich: readonly string[]): string {
  const leer = '................................';
  const z = Array.from({ length: 48 }, () => leer);
  gicht.forEach((g, i) => {
    z[2 + i] = `...........${g}...........`;
  });
  abstich.forEach((a, i) => {
    z[33 + i] = `.............${a}.............`;
  });
  return z.join('\n');
}

const ABSTICH = [
  ['......', '.....', '.}++}.', '.+==+.', '.=@@=.'].map((s) => s.padEnd(6, '.')),
  ['......', '......', '.}+}+.', '.+=@+.', '.=@@=.'],
];

const GLUT = [
  schmelzGlut(['..........', '....}.....', '...}+}.}..', '...+=+}+..', '...}+=+}..', '...}==@=}.'.slice(0, 10)], ABSTICH[0] ?? []),
  schmelzGlut(['..........', '.....}....', '..}.}+}...', '..}+=+=}..', '...+==+}..', '..}=@@=}..'], ABSTICH[1] ?? []),
  schmelzGlut(['......}...', '...}.}+...', '...}+=}}..', '...+=+=}..', '..}+=@+}..', '..}=@@=}..'], ABSTICH[0] ?? []),
  schmelzGlut(['..........', '...}......', '..}+}.}...', '..+==+}...', '..}+=@+}..', '..}=@=@}..'], ABSTICH[1] ?? []),
];

const schmelzofen = station({
  item: 'schmelzofen',
  size: [32, 48],
  anchor: [16, 46],
  hoehe: 'block',
  frames: [OFEN, ...GLUT.map((g) => ueber(OFEN, g))],
  clips: {
    aus: { frames: [0], fps: 1, loop: true },
    brennt: { frames: [1, 2, 3, 4, 2, 3], fps: 10, loop: true },
  },
  sockets: { licht: [[16, 5]], arbeit: [[16, 36]] },
  einzelpixel: 'Funken über der Gicht sind einzelne leuchtende Pixel',
  hitbox: [2, 3, 28, 42],
  occluder: { kind: 'rect', x: 3, y: 36, w: 25, h: 8 },
});

// ---------------------------------------------------------------------------------------------
// Amboss (Bronze)
// ---------------------------------------------------------------------------------------------

const amboss_bronze = station({
  item: 'amboss_bronze',
  size: [16, 24],
  anchor: [8, 22],
  hoehe: 'block',
  frames: [
    `................
     ................
     ................
     ................
     ....kkkkkkkkkk..
     .kkkTTPPTTTTTTk.
     kWTTTTTTTTTTTTk.
     .kkWWWWWWWWWWWk.
     ...kkkWWWWQkkk..
     .....kWWWWQk....
     ....kWWWWWWQk...
     ...kQQQQQQQQQk..
     ...kkkkkkkkkkk..
     ...kddeedddeek..
     ...kcdddcddddk..
     ...kbcccccbcck..
     ...kcbccccccbk..
     ...kcccbccccck..
     ...kbcccccbcck..
     ...kccbcccccbk..
     ...kbcccccccck..
     ...kbbbbbbbbbk..
     ....kkkkkkkkk...
     ................`,
  ],
  material: { metall: BRONZE },
  sockets: { arbeit: [[9, 5]] },
  hitbox: [1, 4, 14, 19],
  occluder: { kind: 'rect', x: 3, y: 13, w: 11, h: 9 },
});

// ---------------------------------------------------------------------------------------------
// Schleifstein
// ---------------------------------------------------------------------------------------------

/** Holzbock mit Trog; die Scheibe und die Kurbel setzt `schleifstein()` je Frame ein. */
const BOCK = `................................
              ................................
              ................................
              ................................
              ................................
              ................................
              ................................
              ................................
              ................................
              ................................
              ................................
              .....kkk..............kkk.......
              .....kdk..............kdk.......
              .....kdk..............kdk.......
              .....kck..............kck.......
              .....kdk..............kdk.......
              .....kdk..............kdk.......
              .....kck..............kck.......
              .....kdk..............kdk.......
              .....kdkkkkkkkkkkkkkkkkdk.......
              .....kdkYzzYzzzYzzzzYzkdk.......
              .....kdkyyzyyyyzyyyzyykdk.......
              ....kkkkkkkkkkkkkkkkkkkkkkk.....
              ....kddddddddddddddddddddddk....
              ....kcccccccccccccccccccccck....
              ....kbbbbbbbbbbbbbbbbbbbbbbk....
              ....kkkkkkkkkkkkkkkkkkkkkkkk....
              ....kdck................kdck....
              ....kdck................kdck....
              ....kbbk................kbbk....
              ....kkkk................kkkk....
              ................................`;

/** Scheibe (Sandstein) mit Maserung in drei Drehlagen. */
const SCHEIBE = [
  `......kkkkkk......
   ....kk455554kk....
   ...k4555445554k...
   ..k455555555554k..
   ..k455553555554k..
   .k45555555555554k.
   .k45555kkk555554k.
   .k45555kbk555554k.
   .k45555kkk555554k.
   .k44555555555544k.
   ..k445555555344k..
   ..k344555555443k..
   ...k3444444443k...
   ....kk333333kk....
   ......kkkkkk......`,
  `......kkkkkk......
   ....kk455554kk....
   ...k4555555554k...
   ..k455555553554k..
   ..k455555555554k..
   .k45555555555554k.
   .k45555kkk555554k.
   .k45555kbk555554k.
   .k45555kkk555554k.
   .k44535555555544k.
   ..k445555555544k..
   ..k344555555443k..
   ...k3444444443k...
   ....kk333333kk....
   ......kkkkkk......`,
  `......kkkkkk......
   ....kk455554kk....
   ...k4555555554k...
   ..k455555555554k..
   ..k455555555554k..
   .k45555555555554k.
   .k45535kkk555554k.
   .k45555kbk555554k.
   .k45555kkk555554k.
   .k44555555555544k.
   ..k445555555544k..
   ..k344555553443k..
   ...k3444444443k...
   ....kk333333kk....
   ......kkkkkk......`,
];

/** Kurbel rechts an der Achse (Zeile 11) in drei Lagen: oben, vorn, unten. */
const KURBEL = [
  `.kkk..
   kdck..
   kdk...
   kdk...
   kddkkk
   kbbbbk
   .kkkkk`,
  `......
   ......
   ......
   ......
   kkkkkk
   kbbbdk
   kkkkdk
   ...kdk
   ...kck
   ...kkk`,
  `......
   ......
   ......
   ......
   kkkkkk
   kbbbbk
   kkkdkk
   ..kdk.
   ..kdk.
   ..kdck
   ..kkkk`,
];

function schleifstein(i: 0 | 1 | 2): string {
  let r = BOCK;
  r = ueber(r, SCHEIBE[i] ?? '', 7, 5);
  return ueber(r, KURBEL[i] ?? '', 25, 8);
}

const schleifstein_ = station({
  item: 'schleifstein',
  size: [32, 32],
  anchor: [16, 30],
  hoehe: 'block',
  frames: [schleifstein(0), schleifstein(1), schleifstein(2)],
  clips: {
    aus: { frames: [0], fps: 1, loop: true },
    arbeitet: { frames: [0, 1, 2], fps: 10, loop: true },
  },
  material: { nass: 'yzY' },
  sockets: { arbeit: [[16, 7]] },
  hitbox: [4, 5, 24, 26],
  occluder: { kind: 'rect', x: 5, y: 22, w: 22, h: 8 },
});

// ---------------------------------------------------------------------------------------------
// Spinnrad
// ---------------------------------------------------------------------------------------------

const GESTELL = `................
                 .kkk............
                 kEDEk...........
                 kDEEDk..........
                 kEDDEk..........
                 .kDEk...........
                 ..kbk...........
                 ..kck...........
                 ..kbk...........
                 ..kck...........
                 ..kbk...........
                 ..kck...........
                 ..kbk...........
                 ..kck...........
                 ..kbk...........
                 ..kck...........
                 ..kbk...........
                 .kkkkkkkkkkkkkk.
                 .kdddddddedddddk
                 .kccccccccccccck
                 .kkkkkkkkkkkkkkk
                 ..kdk......kdk..
                 ..kdk......kdk..
                 ..kck......kck..
                 ...kdk....kdk...
                 ...kdk....kdk...
                 ...kckkkkkkck...
                 ...kcdddeddck...
                 ...kbbbbbbbbk...
                 ...kkkkkkkkkk...
                 ....kk....kk....
                 ................`;

const RAD = [
  `.....kkkkk.....
   ...kkdddddkk...
   ..kdk..k..kdk..
   .kdk...k...kdk.
   .kd....k....dk.
   kd.....k.....dk
   kd.....k.....dk
   kdkkkkkbkkkkkdk
   kd.....k.....dk
   kd.....k.....dk
   .kd....k....dk.
   .kdk...k...kdk.
   ..kdk..k..kdk..
   ...kkcccccck...
   .....kkkkk.....`,
  `.....kkkkk.....
   ...kkdddddkk...
   ..kdkk...kkdk..
   .kdk.kk.kk.kdk.
   .kd...kkk...dk.
   kd.....k.....dk
   kd....kbk....dk
   kd...kkbkk...dk
   kd....kbk....dk
   kd.....k.....dk
   .kd...kkk...dk.
   .kdk.kk.kk.kdk.
   ..kdkk...kkdk..
   ...kkcccccck...
   .....kkkkk.....`,
];

function spinnrad(i: 0 | 1): string {
  return ueber(GESTELL, RAD[i] ?? '', 1, 3);
}

const spinnrad_ = station({
  item: 'spinnrad',
  size: [16, 32],
  anchor: [8, 30],
  hoehe: 'zylinder',
  frames: [spinnrad(0), spinnrad(1)],
  clips: {
    aus: { frames: [0], fps: 1, loop: true },
    arbeitet: { frames: [0, 1], fps: 8, loop: true },
  },
  sockets: { arbeit: [[8, 18]] },
  hitbox: [0, 1, 16, 29],
  occluder: { kind: 'rect', x: 2, y: 21, w: 12, h: 8 },
});

export default [werkbank_2, schmelzofen, amboss_bronze, schleifstein_, spinnrad_];
