/**
 * Säulen T0–T1 (M4-12/M4-13, docs/SPIEL.md §8, MASTERPROMPT §16.3 „Stütze (Wand oder Säule)“):
 * `bau_saeule_holz`, `bau_saeule_stein` – freistehende Stützen auf der Standfläche eines Tiles (Ebene
 * Struktur, Vertrag in `_bau.ts`), so hoch wie eine Wand, damit das Dach auf ihnen liegt.
 * - **Holz:** Vierkantständer mit Maserung auf einem Feldstein-Fundament, oben ein Sattelholz, das
 *   quer übersteht (Auflager der Dachbalken). Relief `block`.
 * - **Stein:** runde Säule aus Trommeln mit Fugen, Basis und Kapitell breiter als der Schaft. Relief
 *   `zylinder`.
 * Freistehend und ohne Nachbarn – deshalb mit Relief (Normalen) statt flach.
 */
import { AUFRECHT_ANKER, AUFRECHT_ZELLE, bauSprite, rasterFrame } from './_bau';

const holz = bauSprite(
  { id: 'bau_saeule_holz', size: AUFRECHT_ZELLE, anchor: AUFRECHT_ANKER, hoehe: 'block', occluder: { kind: 'rect', x: 5, y: 22, w: 6, h: 5 }, schatten: 'silhouette', hitbox: [4, 20, 8, 8] },
  [
    rasterFrame(
      { kontur: 'a' },
      `................
       ................
       ................
       ................
       ..aaaaaaaaaaaa..
       .acddeeddeddcca.
       .acdddddddddcca.
       .abbbbbbbbbbbba.
       ..aaacddcbaaaa..
       ....acddcba.....
       ....acdecba.....
       ....acddcba.....
       ....acddcba.....
       ....abddcba.....
       ....acddcba.....
       ....acdccba.....
       ....acddcba.....
       ....acddcba.....
       ....acdecba.....
       ....acddcba.....
       ....acdcbba.....
       ....acddcba.....
       ...aabddcbaa....
       ..a4555554441a..
       ..a3444444331a..
       ..a2333332221a..
       ...kkkkkkkkkk...
       ................
       ................
       ................
       ................
       ................`,
      AUFRECHT_ZELLE,
    ),
  ],
);

const stein = bauSprite(
  { id: 'bau_saeule_stein', size: AUFRECHT_ZELLE, anchor: AUFRECHT_ANKER, hoehe: 'zylinder', occluder: { kind: 'ellipse', x: 8, y: 25, rx: 4, ry: 2 }, schatten: 'silhouette', hitbox: [4, 20, 8, 8] },
  [
    rasterFrame(
      { kontur: '1' },
      `................
       ................
       ................
       ................
       ...1111111111...
       ..155666655551..
       ..145555555541..
       ..133444444331..
       ...1122222211...
       ....13455431....
       ....13455431....
       ....13455431....
       ....12344321....
       ....11222211....
       ....13455431....
       ....13455431....
       ....13455431....
       ....13444431....
       ....12344321....
       ....11222211....
       ....13455431....
       ....13455431....
       ...1345555431...
       ..134555555431..
       ..123444444321..
       ..112222222211..
       ...kkkkkkkkkk...
       ................
       ................
       ................
       ................
       ................`,
      AUFRECHT_ZELLE,
    ),
  ],
);

export default [holz, stein];
