/**
 * Türen, Tor und Falltür T0–T1 (M4-12/M4-13, docs/SPIEL.md §8 „Türen `offen`/`zu`“): `bau_tuer_holz`,
 * `bau_tuer_verstaerkt`, `bau_tor_holz` (+ `bau_tor_holz_seite`), `bau_falltuer_holz` (+ Klappe) –
 * Frames und Clips nach dem Vertrag in `_bau.ts`.
 *
 * Eine Tür ist ein eigenes Wandelement mit Zarge (zwei Pfosten, Sturz), deshalb passt sie in jede
 * Wand: Die Sturzoberseite läuft in der Kappenzeile der Nachbarwände weiter. In einer Ost-West-Wand
 * zeigt das Blatt seine Bretter mit Querleisten, Beschlägen und Ring; es schwingt nach innen (Norden),
 * halb offen verkürzt es sich zur Trapezfläche, offen bleibt nur die Blattkante am Angelpfosten und
 * die Öffnung ist frei (dahinter erscheint der Boden des Raums). In einer Nord-Süd-Wand sieht man von
 * oben die Stirnseite des Nordpfostens und die Oberkante des Blatts; geöffnet steht das Blatt quer im
 * Raum und zeigt seine Fläche.
 * Frame 6 (`schnitt`) ist die auf 4 px gekappte Zarge für den Blick ins Haus (M4-27), passend zu den
 * Schnittfassungen der Wände.
 * - **Holz:** Brettertür mit Querleisten und eisernen Bändern.
 * - **Verstärkt:** dieselbe Tür mit Bronzebändern, Nietköpfen und Bronzering (Materialflag `metall`).
 * - **Tor:** zweiflügelig zwischen hohen Torpfosten mit Kappen, Flügel mit Andreaskreuz; für Wand- und
 *   Zaunlinien (ohne Sturz).
 * - **Falltür:** Luke mit Rahmen, Ring und Bändern im Boden; offen ein dunkler Schacht mit Leitersprossen,
 *   dazu die aufgestellte Klappe als aufrechtes Teil.
 */
import { tausche, ueberlagere } from '../platzierbar/_bild';
import { AUFRECHT_ANKER, AUFRECHT_ZELLE, bauSprite, rasterFrame, schnittRaster, tabellenClips, type Stil } from './_bau';

/** Zusatzzeichen: Querleisten (`=` hell, `-` dunkel), Eisen (`n`, `N`), Bronze (`Q W T P`). */
const TUER_LEGENDE = { '=': 'holz.4', '-': 'holz.1', Q: 'erde.1', W: 'laub.2', T: 'laub.3', P: 'sand.2' } as const;
const EISEN: Stil = { kontur: 'a', legende: TUER_LEGENDE, material: { metall: 'nN' } };
const BRONZE: Stil = { kontur: 'a', legende: TUER_LEGENDE, material: { metall: 'nNQWTP' } };

/** Zarge in einer Ost-West-Wand: Sturz (Oberseite und Front), Pfosten links und rechts, Öffnung frei. */
const ZARGE = `................
               ................
               ................
               ................
               ................
               aaaaaaaaaaaaaaaa
               ccdcccccccdccccc
               dddddeddddddeddd
               dddddddeeddddddd
               cddddddddddddddc
               cddddddddddddddc
               bbbbbbbbbbbbbbbb
               cb............bc
               cb............bc
               cb............bc
               cb............bc
               cb............bc
               cb............bc
               cb............bc
               cb............bc
               cb............bc
               cb............bc
               cb............bc
               cb............bc
               cb............bc
               cb............bc
               kk............kk
               ................
               ................
               ................
               ................
               ................`;

/** Blatt geschlossen (in der Öffnung x 2–13, Zeilen 12–25). */
const BLATT_ZU = `................
                  ................
                  ................
                  ................
                  ................
                  ................
                  ................
                  ................
                  ................
                  ................
                  ................
                  ................
                  ..aaaaaaaaaaaa..
                  ..dcbdcbdcbdcb..
                  ..nNn========a..
                  ..nnn--------a..
                  ..dcbdcbdcbdcb..
                  ..dcbdcbdcnndb..
                  ..dcbdcbdcnNdb..
                  ..dcbdcbdcbdcb..
                  ..dcbdcbdcbdcb..
                  ..nNn========a..
                  ..nnn--------a..
                  ..dcbdcbdcbdcb..
                  ..dcbdcbdcbdcb..
                  ..dcbdcbdcbdcb..
                  ..kkkkkkkkkkkk..
                  ................
                  ................
                  ................
                  ................
                  ................`;

/** Blatt halb offen: nach innen geschwenkt, verkürzt; rechts ist die Öffnung frei. */
const BLATT_HALB = `................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ..aaaaaaaa......
                    ..dcbdcbda......
                    ..nNn====a......
                    ..nnn----a......
                    ..dcbdcbda......
                    ..dcbdcbda......
                    ..dcbdcbda......
                    ..dcbdcnna......
                    ..dcbdcbda......
                    ..nNn===aa......
                    ..nnn---a.......
                    ..dcbdcba.......
                    ..dcbdcba.......
                    ..dcbdaa........
                    ..kkkk..........
                    ................
                    ................
                    ................
                    ................
                    ................`;

/** Blatt offen: nur die Blattkante am Angelpfosten, die Öffnung ist frei. */
const BLATT_OFFEN = `................
                     ................
                     ................
                     ................
                     ................
                     ................
                     ................
                     ................
                     ................
                     ................
                     ................
                     ................
                     ..aa............
                     ..dc............
                     ..nn............
                     ..nn............
                     ..dc............
                     ..dc............
                     ..dc............
                     ..dc............
                     ..dc............
                     ..nn............
                     ..nn............
                     ..dc............
                     ..dc............
                     ..dc............
                     ..kk............
                     ................
                     ................
                     ................
                     ................
                     ................`;

/**
 * Nord-Süd-Wand: Kappe des Nordpfostens (Zeilen 0–1), seine Stirnseite (2–13), Kappe des Südpfostens
 * (14–15); die Stirn bis Zeile 17 verdeckt die Kappe der Wand südlich davon.
 */
const SEITE = `.....cddc.......
               .....cddc.......
               .....abbba......
               .....abcba......
               .....abcba......
               .....abbba......
               .....abcba......
               .....abcba......
               .....abbba......
               .....abcba......
               .....abcba......
               .....abbba......
               .....abcba......
               .....abcba......
               .....cddc.......
               .....aaaaa......
               .....abcba......
               .....kkkkk......
               ................
               ................
               ................
               ................
               ................
               ................
               ................
               ................
               ................
               ................
               ................
               ................
               ................
               ................`;

/** Geschlossen von oben: Oberkante des Blatts als helle Linie vor der Pfostenstirn. */
const SEITE_ZU = `................
                  ................
                  ................
                  ................
                  .......ed.......
                  .......ed.......
                  .......nN.......
                  .......ed.......
                  .......ed.......
                  .......ed.......
                  .......ed.......
                  .......nN.......
                  .......ed.......
                  .......ed.......
                  ................
                  ................
                  ................
                  ................
                  ................
                  ................
                  ................
                  ................
                  ................
                  ................
                  ................
                  ................
                  ................
                  ................
                  ................
                  ................
                  ................
                  ................`;

/** Halb offen: das Blatt schwenkt schräg in den Raum (Osten) und zeigt einen Teil seiner Fläche. */
const SEITE_HALB = `................
                    ................
                    ................
                    ................
                    ........ea......
                    ........dea.....
                    ........bdea....
                    ........nbdea...
                    ........nnbdea..
                    ........dnnbda..
                    ........dcnnba..
                    ........dcbnna..
                    ........dcbdca..
                    ........dcbdca..
                    ........dcbdca..
                    ........dcbdca..
                    ........dcnndca.
                    ........dcnndca.
                    ........kdcbdca.
                    .........kkdcba.
                    ...........kkka.
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................`;

/** Offen: das Blatt steht quer im Raum und zeigt seine Fläche (nach Osten geschwenkt). */
const SEITE_OFFEN = `................
                     ................
                     ................
                     ................
                     .........aaaaaaa
                     .........dcbdcba
                     .........====nNa
                     .........----nna
                     .........dcbdcba
                     .........dcnndca
                     .........dcnNdca
                     .........dcbdcba
                     .........dcbdcba
                     .........====nNa
                     .........----nna
                     .........dcbdcba
                     .........dcbdcba
                     .........kkkkkkk
                     ................
                     ................
                     ................
                     ................
                     ................
                     ................
                     ................
                     ................
                     ................
                     ................
                     ................
                     ................
                     ................
                     ................`;

/** Frames 0–2 Ost-West (zu, halb, offen), 3–5 Nord-Süd, 6 Schnitt (Ost-West, Öffnung frei). */
function tuerRaster(): string[] {
  const offen = ueberlagere(ZARGE, BLATT_OFFEN);
  return [ueberlagere(ZARGE, BLATT_ZU), ueberlagere(ZARGE, BLATT_HALB), offen, ueberlagere(SEITE, SEITE_ZU), ueberlagere(SEITE, SEITE_HALB), ueberlagere(SEITE, SEITE_OFFEN), schnittRaster(offen)];
}

const TUER_CLIPS = {
  zu: [0],
  offen: [2],
  zu_seite: [3],
  offen_seite: [5],
  schnitt: [6],
};
const TUER_ANIMATION = {
  oeffnen: { frames: [0, 1, 2], fps: 12, loop: false },
  schliessen: { frames: [2, 1, 0], fps: 12, loop: false },
  oeffnen_seite: { frames: [3, 4, 5], fps: 12, loop: false },
  schliessen_seite: { frames: [5, 4, 3], fps: 12, loop: false },
};

function tuer(id: string, stil: Stil, raster: readonly string[]): ReturnType<typeof bauSprite> {
  return bauSprite(
    {
      id,
      size: AUFRECHT_ZELLE,
      anchor: AUFRECHT_ANKER,
      hoehe: 'flach',
      clips: { ...tabellenClips(TUER_CLIPS), ...TUER_ANIMATION },
      occluder: { kind: 'sprite' },
      schatten: 'silhouette',
    },
    raster.map((r) => rasterFrame(stil, r, AUFRECHT_ZELLE)),
  );
}

/** Verstärkt: Eisen → Bronze, Querleisten als Bronzebänder mit Nieten. */
const VERSTAERKT = { n: 'W', N: 'T', '=': 'T', '-': 'Q' } as const;
/** Nietköpfe auf den Bändern (Blatt geschlossen). */
const NIETEN = `................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                .....P..P..P....
                ................
                ................
                ................
                ................
                ................
                ................
                .....P..P..P....
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................
                ................`;

const holz = tuer('bau_tuer_holz', EISEN, tuerRaster());
const verstaerkt = tuer(
  'bau_tuer_verstaerkt',
  BRONZE,
  tuerRaster().map((r, i) => {
    const bronze = tausche(r, VERSTAERKT);
    return i === 0 ? ueberlagere(bronze, NIETEN) : bronze;
  }),
);

// ---------------------------------------------------------------------------------------------
// Tor (zwei Tiles)
// ---------------------------------------------------------------------------------------------

/** Tor Ost-West, 32×32: hohe Pfosten mit Kappe, zwei Flügel mit Andreaskreuz. */
const TOR_ZU = `................................
                ................................
                ................................
                ................................
                ................................
                .aaaa......................aaaa.
                aeeeda....................aeeeda
                adddda....................adddda
                abbbba....................abbbba
                acdcba....................acdcba
                acdcba....................acdcba
                acdcba....................acdcba
                acdcbaaaaaaaaaaaaaaaaaaaaacdcba.
                acdcbadcbdcbdcbadcbdcbdcbacdcba.
                acdcbannn=====a=====nnnnaacdcba.
                acdcbadc-dcbd-bad-bdcb-cbacdcba.
                acdcbadcbd-bd-bad-bd-bdcbacdcba.
                acdcbadcbdc-dcbadcb-dcbcbacdcba.
                acdcbadcbdc-dcbadcb-dcbcbacdcba.
                acdcbadcbd-bd-bad-bd-bdcbacdcba.
                acdcbadc-dcbdc-ad-bdcb-cbacdcba.
                acdcbadcbdcbdcbadcbdcbdcbacdcba.
                acdcbannn=====a=====nnnnaacdcba.
                acdcbadcbdcbdcbadcbdcbdcbacdcba.
                acdcbadcbdcbdcbadcbdcbdcbacdcba.
                kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
                ................................
                ................................
                ................................
                ................................
                ................................
                ................................`;

const TOR_HALB = `................................
                  ................................
                  ................................
                  ................................
                  ................................
                  .aaaa......................aaaa.
                  aeeeda....................aeeeda
                  adddda....................adddda
                  abbbba....................abbbba
                  acdcba....................acdcba
                  acdcba....................acdcba
                  acdcba....................acdcba
                  acdcbaaaaaaaa......aaaaaaaacdcba
                  acdcbadcbdcba......adcbdcbacdcba
                  acdcbannn===a......a===nnnacdcba
                  acdcbadc-dcba......adcb-dbacdcba
                  acdcbadcb-dba......adc-bdbacdcba
                  acdcbadcbdcba......adcbdcbacdcba
                  acdcbadcb-dba......adc-bdbacdcba
                  acdcbadc-dcba......adcb-dbacdcba
                  acdcbadcbdcba......adcbdcbacdcba
                  acdcbannn==aa......aa==nnnacdcba
                  acdcbadcbdca........acbdcbacdcba
                  acdcbadcbaa..........abdcbacdcba
                  acdcbaaaa...............aaacdcba
                  kkkkkk..................kkkkkkkk
                  ................................
                  ................................
                  ................................
                  ................................
                  ................................
                  ................................`;

const TOR_OFFEN = `................................
                   ................................
                   ................................
                   ................................
                   ................................
                   .aaaa......................aaaa.
                   aeeeda....................aeeeda
                   adddda....................adddda
                   abbbba....................abbbba
                   acdcba....................acdcba
                   acdcba....................acdcba
                   acdcba....................acdcba
                   acdcbaaa................aaacdcba
                   acdcbadc................cdacdcba
                   acdcbann................nnacdcba
                   acdcbadc................cdacdcba
                   acdcbadc................cdacdcba
                   acdcbadc................cdacdcba
                   acdcbadc................cdacdcba
                   acdcbadc................cdacdcba
                   acdcbadc................cdacdcba
                   acdcbann................nnacdcba
                   acdcbadc................cdacdcba
                   acdcbadc................cdacdcba
                   acdcbakk................kkacdcba
                   kkkkkk....................kkkkkk
                   ................................
                   ................................
                   ................................
                   ................................
                   ................................
                   ................................`;

const tor = bauSprite(
  {
    id: 'bau_tor_holz',
    size: [32, 32],
    anchor: [16, 31],
    hoehe: 'flach',
    clips: { ...tabellenClips({ zu: [0], offen: [2] }), oeffnen: { frames: [0, 1, 2], fps: 10, loop: false }, schliessen: { frames: [2, 1, 0], fps: 10, loop: false } },
    occluder: { kind: 'sprite' },
    schatten: 'silhouette',
  },
  [TOR_ZU, TOR_HALB, TOR_OFFEN].map((r) => rasterFrame(EISEN, r, [32, 32])),
);

/** Tor Nord-Süd, 16×48 über zwei Tiles: Pfostenkappen im Norden und Süden, Flügel von oben bzw. quer. */
function torSeite(zustand: 0 | 1 | 2): string {
  const zeilen: string[] = [];
  for (let y = 0; y < 48; y++) {
    let z = '................';
    const gy = y - 16;
    if (y <= 1) z = '....aeeda.......';
    else if (y <= 17) z = y === 17 ? '....kkkkk.......' : y === 2 ? '....aaaaa.......' : '....abcba.......';
    if (zustand === 0 && y >= 4 && y <= 31) z = `${z.slice(0, 7)}${y % 9 === 6 ? 'nN' : 'ed'}${z.slice(9)}`;
    if (zustand === 1 && y >= 4 && y <= 20) {
      const r = Math.min(6, Math.max(0, Math.floor((y - 4) / 2)));
      z = `${z.slice(0, 8)}${'dcbdcba'.slice(0, r + 1).padEnd(7, '.')}`.slice(0, 16);
    }
    if (zustand === 2 && y >= 4 && y <= 17) z = `${z.slice(0, 9)}${y === 4 ? 'aaaaaaa' : y === 17 ? 'kkkkkkk' : y % 5 === 1 ? '====nNa' : 'dcbdcba'}`;
    if (gy >= 14 && gy <= 15) z = '....aeeda.......';
    if (y >= 30 && y <= 31) z = '....aeeda.......';
    if (y >= 32 && y <= 45) z = y === 45 ? '....kkkkk.......' : y === 32 ? '....aaaaa.......' : '....abcba.......';
    zeilen.push(z.padEnd(16, '.').slice(0, 16));
  }
  return zeilen.join('\n');
}

const torSeiteSprite = bauSprite(
  {
    id: 'bau_tor_holz_seite',
    size: [16, 48],
    anchor: [8, 47],
    hoehe: 'flach',
    clips: { ...tabellenClips({ zu: [0], offen: [2] }), oeffnen: { frames: [0, 1, 2], fps: 10, loop: false }, schliessen: { frames: [2, 1, 0], fps: 10, loop: false } },
    occluder: { kind: 'sprite' },
    schatten: 'silhouette',
  },
  ([0, 1, 2] as const).map((z) => rasterFrame(EISEN, torSeite(z), [16, 48])),
);

// ---------------------------------------------------------------------------------------------
// Falltür
// ---------------------------------------------------------------------------------------------

const falltuer = bauSprite(
  { id: 'bau_falltuer_holz', size: [16, 16], anchor: [0, 0], hoehe: 'flach', clips: tabellenClips({ zu: [0], offen: [1] }) },
  [
    `aaaaaaaaaaaaaaaa
     abnNbbbbbbbnNbba
     abddddddddddddba
     abccccccccccccba
     ab------------ba
     abddddddddedddba
     abcccccnnccccdba
     abccccnaaNccccba
     abddddnaaNddddba
     abccccccNNccccba
     ab------------ba
     abdddeddddddddba
     abccccccccccccba
     abddddddddddddba
     abbbbbbbbbbbbbba
     aaaaaaaaaaaaaaaa`,
    `aaaaaaaaaaaaaaaa
     abbbbbbbbbbbbbba
     abKKKKKKKKKKKKba
     abKKKaKKKKaKKKba
     abKKacaaaacaKKba
     abKKacddddcaKKba
     abKKacKKKKcaKKba
     abKKacaaaacaKKba
     abKKacddddcaKKba
     abKKacKKKKcaKKba
     abKKacaaaacaKKba
     abKKacddddcaKKba
     abKKacKKKKcaKKba
     abKKKKKKKKKKKKba
     abbbbbbbbbbbbbba
     aaaaaaaaaaaaaaaa`,
  ].map((r) => rasterFrame(EISEN, r, [16, 16])),
);

const klappe = bauSprite(
  {
    id: 'bau_falltuer_holz_klappe',
    size: AUFRECHT_ZELLE,
    anchor: AUFRECHT_ANKER,
    hoehe: 'flach',
    clips: { ...tabellenClips({ halb: [0], offen: [1] }), oeffnen: { frames: [0, 1], fps: 10, loop: false }, schliessen: { frames: [1, 0], fps: 10, loop: false } },
    occluder: { kind: 'sprite' },
    schatten: 'silhouette',
  },
  [
    ueberlagere(
      '................\n'.repeat(32),
      `................
       ................
       ................
       ................
       ................
       ................
       ................
       ................
       ................
       ................
       ................
       .aaaaaaaaaaaaaa.
       .abbbbbbbbbbbba.
       .ab----nn----ba.
       .abccccccccccba.
       .aaaaaaaaaaaaaa.
       ................
       ................
       ................
       ................
       ................
       ................
       ................
       ................
       ................
       ................
       ................
       ................
       ................
       ................
       ................
       ................`,
    ),
    `................
     ................
     .aaaaaaaaaaaaaa.
     .abnNbbbbbbnNba.
     .abccccccccccba.
     .abddddddddddba.
     .ab----------ba.
     .abccccccccccba.
     .abcccccNNcccba.
     .abccccNaaNccba.
     .abccccNaaNccba.
     .abddddddddddba.
     .ab----------ba.
     .abccccccccccba.
     .abbbbbbbbbbbba.
     .kkkkkkkkkkkkkk.
     ................
     ................
     ................
     ................
     ................
     ................
     ................
     ................
     ................
     ................
     ................
     ................
     ................
     ................
     ................
     ................`,
  ].map((r) => rasterFrame(EISEN, r, AUFRECHT_ZELLE)),
);

export default [holz, verstaerkt, tor, torSeiteSprite, falltuer, klappe];
