/**
 * Kinds of particles (M5-11, M5-12, M5-21; schema in `schema.ts`). Palette colours only; everything glowing is emissive,
 * everything else is lit like the scene around it (smoke by a fire glows orange from below, rain shows in torch light).
 *
 * Weather particles (`regentropfen`, `schneeflocke`, `ascheflocke`, `aschenglut`, `sandkorn`, `sandschleier`) fall at the
 * speed of their weather (`wetter.ts`) and drift with its wind; of their kind they take the look, the swirl and the
 * ground contact – their `leben` is how long they lie on the ground (snow, ash) or how long a splash lasts.
 */
import type { ParticleKindInput } from './schema';

export const PARTICLE_KIND_DATA: readonly ParticleKindInput[] = [
  // --- Weather (M5-12) -------------------------------------------------------------------------------------------
  {
    // A pale streak slanted by the wind; lit, so at night it shows only in the light of fires and torches.
    id: 'regentropfen',
    form: 'strich',
    groesse: { min: 1, max: 1 },
    wachstum: 1,
    strich: { faktor: 0.026, min: 4, max: 10 },
    farben: ['eis.3'],
    deckung: { start: 0.7, ende: 0.7 },
    emissiv: 0,
    flackern: 0,
    leben: { min: 30, max: 30 },
    schwerkraft: 0,
    widerstand: 0,
    wind: 1,
    wirbel: 0,
    wirbelTakt: 0,
    boden: 'spritzen',
    spritzer: 'regenspritzer',
  },
  {
    // The crown of a drop on the ground: dot, small V, two droplets – a fifth of a second.
    id: 'regenspritzer',
    form: 'spritzer',
    groesse: { min: 1, max: 1 },
    wachstum: 1,
    farben: ['eis.3'],
    deckung: { start: 0.75, ende: 0.4 },
    emissiv: 0,
    flackern: 0,
    leben: { min: 0.16, max: 0.24 },
    schwerkraft: 0,
    widerstand: 0,
    wind: 0,
    wirbel: 0,
    wirbelTakt: 0,
    boden: 'liegen',
  },
  {
    // Flakes sway on a slow swirl; far ones are a dot, near ones a small plus; on the ground they melt away.
    id: 'schneeflocke',
    form: 'flocke',
    groesse: { min: 1, max: 2 },
    wachstum: 1,
    farben: ['eis.4'],
    deckung: { start: 0.95, ende: 0 },
    emissiv: 0,
    flackern: 0,
    leben: { min: 1, max: 2.6 },
    schwerkraft: 0,
    widerstand: 0,
    wind: 1,
    wirbel: 14,
    wirbelTakt: 0.35,
    boden: 'liegen',
  },
  {
    // Grey flakes of ash tumbling down, lying a moment before they fade into the ground.
    id: 'ascheflocke',
    form: 'punkt',
    groesse: { min: 1, max: 2 },
    wachstum: 1,
    farben: ['stein.4', 'stein.3'],
    deckung: { start: 0.85, ende: 0 },
    emissiv: 0,
    flackern: 0,
    leben: { min: 1.2, max: 3 },
    schwerkraft: 0,
    widerstand: 0,
    wind: 1,
    wirbel: 18,
    wirbelTakt: 0.6,
    boden: 'liegen',
  },
  {
    // Every tenth flake of an ashfall still glows: an ember cooling from yellow to red, twinkling as it tumbles.
    id: 'aschenglut',
    form: 'punkt',
    groesse: { min: 1, max: 2 },
    wachstum: 1,
    farben: ['feuer.4', 'feuer.3'],
    deckung: { start: 1, ende: 1 },
    emissiv: 2.4,
    flackern: 0.6,
    leben: { min: 0.3, max: 0.6 },
    schwerkraft: 0,
    widerstand: 0,
    wind: 1,
    wirbel: 24,
    wirbelTakt: 0.8,
    boden: 'vergehen',
  },
  {
    // Grains of a sandstorm: long streaks along the wind, pale where the sun catches them …
    id: 'sandkorn',
    form: 'strich',
    groesse: { min: 1, max: 1 },
    wachstum: 1,
    strich: { faktor: 0.05, min: 6, max: 16 },
    farben: ['sand.4'],
    deckung: { start: 0.9, ende: 0.9 },
    emissiv: 0,
    flackern: 0,
    leben: { min: 30, max: 30 },
    schwerkraft: 0,
    widerstand: 0,
    wind: 1,
    wirbel: 30,
    wirbelTakt: 1.2,
    boden: 'vergehen',
  },
  {
    // … and dark earth-brown in their shade, so the storm reads over pale sand as over dark rock.
    id: 'sandkorn_dunkel',
    form: 'strich',
    groesse: { min: 1, max: 1 },
    wachstum: 1,
    strich: { faktor: 0.04, min: 4, max: 12 },
    farben: ['erde.2'],
    deckung: { start: 0.7, ende: 0.7 },
    emissiv: 0,
    flackern: 0,
    leben: { min: 30, max: 30 },
    schwerkraft: 0,
    widerstand: 0,
    wind: 1,
    wirbel: 30,
    wirbelTakt: 1.2,
    boden: 'vergehen',
  },
  {
    // Veils of blown dust between the grains: long faint wisps racing flat with the storm.
    id: 'sandschleier',
    form: 'schwade',
    groesse: { min: 4, max: 8 },
    wachstum: 1,
    strich: { faktor: 0.16, min: 24, max: 48 },
    farben: ['sand.3'],
    deckung: { start: 0.3, ende: 0.3 },
    emissiv: 0,
    flackern: 0,
    leben: { min: 30, max: 30 },
    schwerkraft: 0,
    widerstand: 0,
    wind: 1,
    wirbel: 20,
    wirbelTakt: 0.5,
    boden: 'vergehen',
  },
  // --- Fire (M5-21) ------------------------------------------------------------------------------------------------
  {
    // A spark thrown up by the flames, cooling from white-yellow through orange to deep red, trailing when fast.
    id: 'funke',
    form: 'strich',
    groesse: { min: 1, max: 1 },
    wachstum: 1,
    strich: { faktor: 0.02, min: 1, max: 3 },
    farben: ['feuer.5', 'feuer.4', 'feuer.3', 'feuer.2'],
    deckung: { start: 1, ende: 1 },
    emissiv: 2.2,
    flackern: 0.45,
    leben: { min: 0.6, max: 1.5 },
    schwerkraft: 45,
    widerstand: 1.2,
    wind: 0.9,
    wirbel: 30,
    wirbelTakt: 2.5,
    boden: 'vergehen',
  },
  {
    // An ember drifting up from a bed of glowing wood, slowly cooling.
    id: 'glut',
    form: 'punkt',
    groesse: { min: 1, max: 1 },
    wachstum: 1,
    farben: ['feuer.4', 'feuer.3', 'feuer.2', 'feuer.1'],
    deckung: { start: 1, ende: 1 },
    emissiv: 1.4,
    flackern: 0.7,
    leben: { min: 1.5, max: 3.5 },
    schwerkraft: -12,
    widerstand: 1.5,
    wind: 1,
    wirbel: 16,
    wirbelTakt: 0.8,
    boden: 'vergehen',
  },
  {
    // Smoke of a blaze: a small dark puff over the flames swelling into a wide, fading cloud that leans with the wind.
    id: 'rauch',
    form: 'scheibe',
    groesse: { min: 3, max: 5 },
    wachstum: 3.4,
    farben: ['stein.1', 'stein.2', 'stein.2'],
    deckung: { start: 0.6, ende: 0 },
    emissiv: 0,
    flackern: 0,
    leben: { min: 2.8, max: 4.6 },
    schwerkraft: -8,
    widerstand: 0.8,
    wind: 1,
    wirbel: 7,
    wirbelTakt: 0.5,
    boden: 'vergehen',
  },
  {
    // The thin wisp over a torch or a small fire: a pixel that widens and fades within two seconds.
    id: 'fackelrauch',
    form: 'scheibe',
    groesse: { min: 1, max: 2 },
    wachstum: 2.6,
    farben: ['stein.2', 'stein.1'],
    deckung: { start: 0.45, ende: 0 },
    emissiv: 0,
    flackern: 0,
    leben: { min: 1.2, max: 2.2 },
    schwerkraft: -6,
    widerstand: 1,
    wind: 1,
    wirbel: 5,
    wirbelTakt: 0.8,
    boden: 'vergehen',
  },
  // --- Night and magic ---------------------------------------------------------------------------------------------
  {
    // A mote of lumen light rising in a spiral with a short trail, cooling from sea-green through lumen blue to deep water.
    id: 'lumenfunke',
    form: 'strich',
    groesse: { min: 1, max: 1 },
    wachstum: 1,
    strich: { faktor: 0.05, min: 1, max: 3 },
    farben: ['wasser.5', 'wasser.4', 'wasser.3', 'wasser.2'],
    deckung: { start: 1, ende: 0.5 },
    emissiv: 1.5,
    flackern: 0.3,
    leben: { min: 2.6, max: 4.2 },
    schwerkraft: -4,
    widerstand: 0.25,
    wind: 0.2,
    wirbel: 10,
    wirbelTakt: 0.5,
    boden: 'vergehen',
  },
  {
    // A firefly: a yellow-green point wandering low over the grass, blinking.
    id: 'gluehwuermchen',
    form: 'punkt',
    groesse: { min: 1, max: 1 },
    wachstum: 1,
    farben: ['gras.5', 'feuer.5'],
    deckung: { start: 1, ende: 1 },
    emissiv: 1.6,
    flackern: 0.95,
    leben: { min: 4, max: 7 },
    schwerkraft: 0,
    widerstand: 0.6,
    wind: 0.1,
    wirbel: 14,
    wirbelTakt: 0.3,
    boden: 'abprallen',
  },
];
