/**
 * M2-27 acceptance: changed chunks are saved as diffs in IndexedDB (and the in-memory store) with
 * the world meta; loading gives identical chunk hashes; only changed chunks are written.
 */
import { IDBFactory } from 'fake-indexeddb';
import { afterEach, describe, expect, it } from 'vitest';
import { saveChunkWorld, loadChunkWorld, encodeChunkRecord, decodeChunkRecord, CHUNK_RECORD_FORMAT } from '../../../src/save/chunks';
import { openSaveDb } from '../../../src/save/db';
import { MemorySaveStore } from '../../../src/save/memoryStore';
import { SaveError } from '../../../src/save/registry';
import type { SaveStore, SaveWriteBatch } from '../../../src/save/store';
import { WORLD_RECORD_BLOB } from '../../../src/save/worldMeta';
import { resolveSimConfig } from '../../../src/game/sim';
import { chunkHash, type ChunkData } from '../../../src/world/model/chunk';
import { contentWorldIdTables, createWorldIdTables, serializeWorldIdTables } from '../../../src/world/model/runtimeIds';
import type { ChunkManager } from '../../../src/world/stream/chunkManager';
import { diffChunk } from '../../../src/world/stream/diff';
import { fixtureGenerate, fixtureManager, settle, type FixturePlan } from '../world/streamFixture';

const WORLD = 'welt-1';
const CONFIG = resolveSimConfig({ seed: 7, worldSize: 'small' });
const GENERATOR_VERSION = 1;

interface Adapter {
  readonly name: string;
  open(): Promise<SaveStore>;
}

const opened: SaveStore[] = [];
afterEach(() => {
  for (const s of opened.splice(0)) s.close();
});

const adapters: Adapter[] = [
  {
    name: 'IndexedDB (fake-indexeddb)',
    async open() {
      const s = await openSaveDb(new IDBFactory(), 'chunks-test');
      opened.push(s);
      return s;
    },
  },
  {
    name: 'in-memory',
    async open() {
      const s = new MemorySaveStore();
      opened.push(s);
      return s;
    },
  },
];

/** Wraps a store and records the chunk operations of every transaction. */
function spy(store: SaveStore): { store: SaveStore; puts: string[][]; deletes: string[][] } {
  const puts: string[][] = [];
  const deletes: string[][] = [];
  const wrapped: SaveStore = Object.create(store) as SaveStore;
  wrapped.write = (build) => {
    const p: string[] = [];
    const d: string[] = [];
    puts.push(p);
    deletes.push(d);
    return store.write((batch) => {
      const recording: SaveWriteBatch = {
        ...batch,
        putWorld: (m) => batch.putWorld(m),
        deleteWorld: (w) => batch.deleteWorld(w),
        putSlot: (r) => batch.putSlot(r),
        deleteSlot: (w, s) => batch.deleteSlot(w, s),
        putBlob: (r) => batch.putBlob(r),
        deleteBlob: (w, n) => batch.deleteBlob(w, n),
        putChunk: (r) => {
          p.push(r.key);
          batch.putChunk(r);
        },
        deleteChunk: (w, k) => {
          d.push(k);
          batch.deleteChunk(w, k);
        },
      };
      build(recording);
    });
  };
  return { store: wrapped, puts, deletes };
}

async function save(store: SaveStore, manager: ChunkManager<FixturePlan>, tick = 1000): Promise<Awaited<ReturnType<typeof saveChunkWorld>>> {
  return saveChunkWorld(store, {
    worldId: WORLD,
    name: 'Testwelt',
    config: CONFIG,
    tick,
    day: 1,
    now: 1_700_000_000_000 + tick,
    gameVersion: '0.1.0',
    generatorVersion: GENERATOR_VERSION,
    tables: contentWorldIdTables(),
    chunks: manager,
  });
}

function chunk(m: ChunkManager<FixturePlan>, cx: number, cy: number): ChunkData {
  return m.ensure(0, cx, cy);
}

describe.each(adapters)('chunk saving: $name', (adapter) => {
  it('change, save, load ⇒ identical chunk hashes; only changed chunks are written', async () => {
    const { store, puts, deletes } = spy(await adapter.open());
    const a = fixtureManager().manager;
    settle(a, 0, 10, 10);
    chunk(a, 9, 10).ground.fill(9, 64, 96); // dug a trench (9: never generated by the fixture)
    const treeTile = fixtureGenerate({ seed: 7 }, 0, 11, 11).object.findIndex((v) => v !== 0);
    expect(treeTile).toBeGreaterThanOrEqual(0);
    chunk(a, 11, 11).setObject(treeTile, 0); // felled a tree
    chunk(a, 10, 12).setObjectState(40, 2, 0, 9999); // damaged a rock
    const flip = chunk(a, 12, 8);
    const old = flip.flags[3] as number;
    flip.flags[3] = old ^ 1; // changed and changed back: not a modification
    flip.flags[3] = old;

    const first = await save(store, a);
    expect(first.written).toEqual(['0:10:12', '0:11:11', '0:9:10']);
    expect(first.deleted).toEqual([]);
    expect(await store.listChunkKeys(WORLD)).toEqual(['0:10:12', '0:11:11', '0:9:10']);

    // Walk away (9:10 unloads with its saved change), change a far chunk, save again.
    settle(a, 0, 20, 20);
    expect(a.get(0, 9, 10)).toBeUndefined();
    chunk(a, 20, 21).ground.fill(8, 0, 32);
    const second = await save(store, a, 2000);
    expect(second.written).toEqual(['0:20:21']);
    // Nothing changed since: nothing written.
    const third = await save(store, a, 3000);
    expect([third.written, third.deleted]).toEqual([[], []]);
    expect(puts.map((p) => p.length)).toEqual([3, 1, 0]);

    // Back at 11:11: the tree grows back to the generated state → its record is deleted.
    settle(a, 0, 10, 10);
    const tree = chunk(a, 11, 11);
    const generated = fixtureGenerate({ seed: 7 }, 0, 11, 11);
    tree.object[treeTile] = generated.object[treeTile] as number;
    const grownState = generated.getObjectState(treeTile);
    if (grownState !== undefined) tree.setObjectState(treeTile, grownState.hp, grownState.growth, grownState.regrowAtTick);
    const fourth = await save(store, a, 4000);
    expect([fourth.written, fourth.deleted]).toEqual([[], ['0:11:11']]);
    expect(deletes.flat()).toEqual(['0:11:11']);
    expect(await store.listChunkKeys(WORLD)).toEqual(['0:10:12', '0:20:21', '0:9:10']);

    // Load into a fresh manager: every chunk hashes as in the running world.
    const loaded = await loadChunkWorld(store, WORLD, { tables: contentWorldIdTables(), generatorVersion: GENERATOR_VERSION });
    expect(loaded.meta).toMatchObject({ id: WORLD, seed: 7, tick: 4000, day: 1 });
    expect(loaded.generatorChanged).toBe(false);
    const b = fixtureManager().manager;
    b.loadStored(loaded.diffs);
    for (const [cx, cy] of [
      [9, 10],
      [10, 12],
      [11, 11],
      [12, 8],
      [20, 21],
      [15, 15],
    ] as const) {
      expect(chunkHash(b.ensure(0, cx, cy))).toBe(chunkHash(a.ensure(0, cx, cy)));
    }
    settle(b, 0, 20, 20);
    expect(chunkHash(b.get(0, 20, 21) as ChunkData)).toBe(chunkHash(a.ensure(0, 20, 21)));
    expect(b.contentHash()).toBe(a.contentHash());
    // Saving the untouched loaded world writes nothing.
    const again = await save(store, b, 5000);
    expect([again.written, again.deleted]).toEqual([[], []]);
  });

  it('a failed transaction keeps the changes for the next save', async () => {
    const store = await adapter.open();
    const m = fixtureManager().manager;
    settle(m, 0, 5, 5);
    chunk(m, 5, 5).ground[0] = 9;
    const failing: SaveStore = Object.create(store) as SaveStore;
    failing.write = (build) =>
      store.write((batch) => {
        build(batch);
        batch.putWorld({ id: '', name: 'x', seed: 1, config: CONFIG, saveFormat: 1, tick: 0, day: 1, createdAt: 0, savedAt: 0 });
      });
    await expect(save(failing, m)).rejects.toThrow();
    expect(await store.listChunkKeys(WORLD)).toEqual([]);
    const retry = await save(store, m);
    expect(retry.written).toEqual(['0:5:5']);
  });
});

describe('chunk records', () => {
  it('remaps runtime ids when content was added after the save', async () => {
    const store = new MemorySaveStore();
    const current = contentWorldIdTables();
    const ids = serializeWorldIdTables(current);
    // The save predates the first terrain type and the first two world objects of today's content.
    const saved = createWorldIdTables({ terrain: ids.terrain.slice(1), biomes: ids.biomes, objects: ids.objects.slice(2) });
    const m = fixtureManager().manager;
    settle(m, 0, 3, 3);
    const c = chunk(m, 3, 3);
    c.ground[7] = saved.terrain.runtimeId('sand');
    c.object[8] = saved.objects.runtimeId('baum_eiche');
    await saveChunkWorld(store, { worldId: WORLD, name: 'alt', config: CONFIG, tick: 1, day: 1, now: 1, gameVersion: '0.0.9', generatorVersion: 1, tables: saved, chunks: m });
    const loaded = await loadChunkWorld(store, WORLD, { tables: current, generatorVersion: 2 });
    expect(loaded.generatorChanged).toBe(true);
    const b = fixtureManager().manager;
    b.loadStored(loaded.diffs);
    const restored = b.ensure(0, 3, 3);
    expect(current.terrain.stringId(restored.ground[7] as number)).toBe('sand');
    expect(current.objects.stringId(restored.object[8] as number)).toBe('baum_eiche');
  });

  it('refuses corrupt records, orphaned chunk records and newer formats', async () => {
    const store = new MemorySaveStore();
    const m = fixtureManager().manager;
    settle(m, 0, 3, 3);
    chunk(m, 3, 3).ground[1] = 9;
    await save(store, m);
    const record = (await store.getChunk(WORLD, '0:3:3'))?.data as ReturnType<typeof encodeChunkRecord>;
    expect(record.format).toBe(CHUNK_RECORD_FORMAT);
    expect(decodeChunkRecord('0:3:3', record).cx).toBe(3);
    expect(() => decodeChunkRecord('0:3:4', record)).toThrow(SaveError);
    expect(() => decodeChunkRecord('0:3:3', { ...record, hash: '0000000000000000' })).toThrow(/hash/);
    expect(() => decodeChunkRecord('0:3:3', { ...record, format: 2 })).toThrow(SaveError);
    expect(() => decodeChunkRecord('0:3:3', { ...record, diff: { ...record.diff, objects: [] } })).toThrow(SaveError);

    await store.write((b) => b.putChunk({ worldId: WORLD, key: '0:3:3', data: { ...record, hash: 'ffffffffffffffff' } }));
    const current = { tables: contentWorldIdTables(), generatorVersion: GENERATOR_VERSION };
    await expect(loadChunkWorld(store, WORLD, current)).rejects.toThrow(/corrupt/);

    await store.write((b) => b.deleteBlob(WORLD, WORLD_RECORD_BLOB));
    await expect(loadChunkWorld(store, WORLD, current)).rejects.toThrow(/no world record/);
    await store.write((b) => b.deleteChunk(WORLD, '0:3:3'));
    expect((await loadChunkWorld(store, WORLD, current)).diffs).toEqual([]);
    await expect(loadChunkWorld(store, 'fehlt', current)).rejects.toThrow(SaveError);
  });

  it('stores the diff, not the chunk: a single changed tile costs a few bytes', () => {
    const base = fixtureGenerate({ seed: 7 }, 0, 1, 1);
    const cur = base.clone();
    cur.ground[500] = 1;
    const record = encodeChunkRecord(diffChunk(base, cur) as NonNullable<ReturnType<typeof diffChunk>>);
    expect(record.diff.fields.ground?.runs.byteLength).toBe(4);
    expect(record.diff.fields.ground?.values.byteLength).toBe(1);
  });
});
