/**
 * Zustands-Icon der Orte (M7-08; docs/SPIEL.md §18 "segen"): `zustand_gesegnet` – der Segen des Schreins, Rahmen `gut`
 * (Kreis), Motiv die goldene Erbauer-Sonne der Schrein-Stele (Ring mit Strahlen um einen hellen Kern), damit das Icon in der
 * Zustandsleiste an den Ort erinnert, der es gab.
 */
import { zustand } from './_zustand';

export default [
  zustand(
    'gesegnet',
    'gut',
    `................
     ................
     ................
     .......E........
     ....E..D..E.....
     .....D.D.D......
     ......kkk.......
     ...EDDkV#kDDE...
     ......k##k......
     .....DkkkkD.....
     ....E..D...E....
     .......E........
     ................
     ................
     ................
     ................`,
    { einzelpixel: 'heller Kern der Erbauer-Sonne' },
  ),
];
