/**
 * Zustands-Icons der 31 Zustände (docs/SPIEL.md §6 „Zustände (M3-19)“, M3-20). Rahmen je Art aus
 * `_zustand.ts`: Kreis = Stärkung, Quadrat = Schwächung, Raute = kostet Leben (mit Puls-Frame).
 *
 * Motive (bei 16 px und ×2 lesbar, je Reihe dieselbe Form):
 * - Kälte: Schneeflocke (frierend) → Thermometer tief mit Flocke (unterkühlt) → Flocke mit Eisriss in der
 *   Raute (erfrierend). Hitze: kleine Sonne (erhitzt) → Thermometer hoch mit Hitzewellen (überhitzt) →
 *   gleißende Sonne in der Raute (Hitzschlag).
 * - Hunger: Keule (hungrig) → abgenagter Knochen in der Raute (verhungernd); satt: dampfende Schale.
 *   Durst: halb leerer Tropfen (durstig) → rissiger, leerer Tropfen in der Raute (verdurstend).
 * - Gift in der Gefahren-Bildsprache (docs/ART.md §7): fahles Giftgrün, Blasen und Tropfen – Gifttropfen
 *   (Vergiftung), grünliche Keule mit Blasen (Lebensmittelvergiftung).
 * - Übrige: Blutstropfen, Flamme, Luftblasen über der Welle (ertrinkend), Tropfen (durchnässt),
 *   Gesicht mit Fieberthermometer, „Zz“ (müde), leerer Blitz mit Schweißtropfen (erschöpft), Schnecke
 *   (verlangsamt), kreisende Sterne (betäubt), geblendetes Auge im Strahlenkranz, gebrochener Knochen,
 *   Humpen (beschwipst), gesprungenes Herz (erschüttert, −15 % max. Leben); gut: Mondsichel mit Stern
 *   (ausgeruht), Hütte mit warmem Fenster (behaglich), Flamme im Strahlenkranz (erleuchtet), Sonne über
 *   dem Horizont (Morgenrot), Auge mit leuchtender Iris (Nachtsicht).
 */
import { zustand, type ZustandArt } from './_zustand';

/** Art (Rahmenform) jedes Zustands; die Reihenfolge folgt docs/SPIEL.md §6. */
export const ZUSTAND_ARTEN: Readonly<Record<string, ZustandArt>> = {
  blutung: 'kritisch',
  vergiftung: 'kritisch',
  lebensmittelvergiftung: 'schlecht',
  fieber: 'schlecht',
  brennen: 'kritisch',
  durchnaesst: 'schlecht',
  frierend: 'schlecht',
  unterkuehlt: 'schlecht',
  erfrierend: 'kritisch',
  erhitzt: 'schlecht',
  ueberhitzt: 'schlecht',
  hitzschlag: 'kritisch',
  muede: 'schlecht',
  erschoepft: 'schlecht',
  verlangsamt: 'schlecht',
  betaeubt: 'schlecht',
  geblendet: 'schlecht',
  knochenbruch: 'schlecht',
  wohlgenaehrt: 'gut',
  ausgeruht: 'gut',
  behaglich: 'gut',
  erleuchtet: 'gut',
  morgenrot: 'gut',
  nachtsicht: 'gut',
  beschwipst: 'schlecht',
  erschuettert: 'schlecht',
  hungrig: 'schlecht',
  verhungernd: 'kritisch',
  durstig: 'schlecht',
  verdurstend: 'kritisch',
  ertrinkend: 'kritisch',
};

/** Motive (16×16, `.` = Rahmen sichtbar). */
const MOTIVE: Readonly<Record<string, string>> = {
  blutung: `................
     ................
     ................
     ................
     .......kk.......
     ......kuFk......
     .....kuFFFk.....
     ....kuSFFFfk....
     ....kSuFFFfk....
     ....kuFFFffk....
     .....kFFffk.....
     ......kkkk......
     ................
     ................
     ................
     ................`,
  vergiftung: `................
     ................
     ................
     ................
     .......kk.......
     ......kJjk......
     .....kJjjjk.....
     ....kJEjjjik....
     ....kEJjjiik....
     ....kjjjiihk....
     .....kiihhk.....
     ......kkkk......
     ................
     ................
     ................
     ................`,
  lebensmittelvergiftung: `................
     ................
     ................
     ....kkkk..JJ....
     ...kjjjik.......
     ...kjiMMik.J....
     ...kiMMmmk......
     ...kmMmmlk......
     ....kmmlkk......
     .....kkk#0k.....
     ........k#0k....
     .......k##k0k...
     ........kk.k....
     ................
     ................
     ................`,
  fieber: `................
     ................
     ................
     .....kkkkk......
     ....kRSRRRk.....
     ...kRSRRRRRk....
     ...kROkRkOR0k...
     ...kRRRRRRk09...
     ...kRuRRRk09k...
     ...kROR0k09k....
     ....kkk0uk......
     ......kuuk......
     .......kk.......
     ................
     ................
     ................`,
  brennen: `................
     ................
     ................
     .......k........
     ......kUk.......
     .....kUvUk......
     .....kvVvUk.....
     ....kUvVVvk.....
     ....kvVVVvUk....
     ....kUvVVvUk....
     .....kUvvUk.....
     ......kkkk......
     ................
     ................
     ................
     ................`,
  durchnaesst: `................
     ................
     ................
     .....k..........
     ....kYk.........
     ...kYZzk..k.....
     ...kZzyk.kYk....
     ....kkk.kYZzk...
     ......k.kZzyk...
     .....kYk.kkk....
     ....kYZzk.......
     ....kZzyk.......
     .....kkk........
     ................
     ................
     ................`,
  frierend: `................
     ................
     ................
     .......#........
     ....#..#..#.....
     .....#.#.#......
     ......###.......
     ...#######......
     ......###.......
     .....#.#.#......
     ....#..#..#.....
     .......#........
     ................
     ................
     ................
     ................`,
  unterkuehlt: `................
     ................
     ................
     ...#.#.#.kk.....
     ....###.k00k....
     ...#####k00k....
     ....###.k00k....
     ...#.#.#k00k....
     ........kzzk....
     .......kzZZzk...
     .......kZYYZk...
     .......kzZZzk...
     ........kkkk....
     ................
     ................
     ................`,
  erfrierend: `................
     ................
     ................
     .......#........
     ......#0#.......
     .....#.#.#......
     .....k###k......
     ...#0###0#0#....
     .....k###k......
     .....#.#.#......
     ......#0#.......
     .......#........
     ................
     ................
     ................
     ................`,
  erhitzt: `................
     ................
     ................
     .......v........
     ....v..v..v.....
     .....kkkkk......
     ....kvVVVvk.....
     ...vkVVVVVkv....
     ....kvVVVvk.....
     ....kUvvvUk.....
     .....kkkkk......
     ....v..v..v.....
     .......v........
     ................
     ................
     ................`,
  ueberhitzt: `................
     ................
     ................
     ....kk.....U....
     ...k00k...U.....
     ...k0uk....U....
     ...k0uk...U.....
     ...k0uk.U..U....
     ...k0uk..U......
     ...kuuuk.U......
     ...kuUuk..U.....
     ...kuFFk.U......
     ....kkk.........
     ................
     ................
     ................`,
  hitzschlag: `................
     ................
     ................
     .......V........
     .......V........
     .....Vkkk.V.....
     .....kvVvk......
     ...VVkVVVkVV....
     .....kvVvk......
     ....V.kkk.V.....
     .......V........
     .......V........
     ................
     ................
     ................
     ................`,
  muede: `................
     ................
     ................
     ......kkkkkk....
     ......k0000k....
     ......kkk00k....
     .......k00kk....
     ...kkkk00kkk....
     ...k99k0000k....
     ....k9kkkkkk....
     ...k9kk.........
     ...k99k.........
     ...kkkk.........
     ................
     ................
     ................`,
  erschoepft: `................
     ................
     ................
     ........kkkk....
     .......kDDBk....
     ......kDBk......
     .....kDBkkk.....
     ....kDDDDBk.....
     ....kkkkDBkk....
     ......kDBkkZk...
     .....kDBk.kZk...
     .....kBk...k....
     .....kk.........
     ................
     ................
     ................`,
  verlangsamt: `................
     ................
     ................
     ........kkkk....
     .......kMooMk...
     ...k.k.kokkMk...
     ...D.D.kMkoMk...
     ...DDD.kmMMmk...
     ...DDDDkkkkkk...
     ...DDDDDDDDDk...
     ...kCCCCCCCCk...
     ....kkkkkkkk....
     ................
     ................
     ................
     ................`,
  betaeubt: `................
     ................
     ................
     ..........k.....
     .....k...kvk....
     ....kvk.kvvvk...
     .....kDDDDkvk...
     ....D......k....
     ...D.....k..D...
     ....D...kvkD....
     .....DDDDkD.....
     ................
     ................
     ................
     ................
     ................`,
  geblendet: `................
     ................
     ................
     ........V.......
     .....V..V..V....
     ......V.V.V.....
     ....kkkVVVkk....
     ...k00VV#VV0k...
     ...k00VVVV00k...
     ....kkkVVVkk....
     ......V.V.V.....
     .....V..V..V....
     ........V.......
     ................
     ................
     ................`,
  knochenbruch: `................
     ................
     ................
     ....kk.kk.......
     ...k#0k#0k......
     ...k0####k......
     ....kk#0kk......
     ......k#k.......
     .......k0k......
     ......kk#0kk....
     .....k0####k....
     .....k#0k#0k....
     ......kk.kk.....
     ................
     ................
     ................`,
  wohlgenaehrt: `................
     ................
     ................
     .......0..0.....
     ......0..0......
     .......0..0.....
     ...kkkkkkkkkk...
     ...kMoMoMMoMk...
     ...kdMMMMMMdk...
     ...kcddddddck...
     ....kcccccck....
     .....kbbbbk.....
     ......kkkk......
     ................
     ................
     ................`,
  ausgeruht: `................
     ................
     ................
     .....kk.........
     ....kEEk........
     ...kEEk....#....
     ...kEDk...###...
     ...kDDk....#....
     ...kDDDk........
     ...kCDDDk...0...
     ....kCCCCk.0....
     .....kkkk.......
     ................
     ................
     ................
     ................`,
  behaglich: `................
     ................
     ................
     .......kk.......
     ......keek......
     .....keeddk.....
     ....keeddcck....
     ...kkkkkkkkkk...
     ....ktvvtbbk....
     ....ktVVtbbk....
     ....kttttcbk....
     ....kkkkkkkk....
     ................
     ................
     ................
     ................`,
  erleuchtet: `................
     ................
     ................
     .......V........
     ....V..k..V.....
     ......kUk.......
     .....kUvUk......
     ...V.kvVvk.V....
     ...V.kvVvk.V....
     .....kUvUk......
     ....V.kkk.V.....
     .......V........
     ................
     ................
     ................
     ................`,
  morgenrot: `................
     ................
     ................
     .......MM.......
     ................
     ....M......M....
     ......kkkk......
     .....kovvok.....
     ...M.kvVVvk.M...
     ....kovVVvok....
     ...kmmmmmmmmk...
     ....kllMMllk....
     ................
     ................
     ................
     ................`,
  nachtsicht: `................
     ................
     ................
     ................
     ................
     ......kkkk......
     ....kk0000kk....
     ...k00zYZz00k...
     ...k0zZkkZz0k...
     ...k00zZZz00k...
     ....kk0000kk....
     ......kkkk......
     ................
     ................
     ................
     ................`,
  beschwipst: `................
     ................
     ................
     ......0.0.......
     ...kkkkkkk......
     ...k##0##k......
     ...kddcddkkk....
     ...kdMoMckbk....
     ...kdMoMck.bk...
     ...kdMMMckbk....
     ...kdcccckk.....
     ...kbbbbbk......
     ...kkkkkkk......
     ................
     ................
     ................`,
  erschuettert: `................
     ................
     ................
     ................
     ....kk...kk.....
     ...kuukkkuuk....
     ...kSSuuk.uuk...
     ...kuuukuuuFk...
     ....kuFk.uFk....
     .....kFFkFk.....
     ......kFk.k.....
     .......k........
     ................
     ................
     ................
     ................`,
  hungrig: `................
     ................
     ................
     ....kkkk........
     ...kMooMk.......
     ...koMMmk.......
     ...kMMmmk.......
     ...kmmllk.......
     ....kllk#k......
     .....kkk#0k.....
     ........k#0k....
     .......k##k0k...
     ........kk.k....
     ................
     ................
     ................`,
  verhungernd: `................
     ................
     ................
     ................
     ......kkkk......
     .....k#k#0k.....
     .....k0##0k.....
     ......k#0k......
     ......k#0k......
     .....k0##0k.....
     .....k#k#0k.....
     ......kkkk......
     ................
     ................
     ................
     ................`,
  durstig: `................
     ................
     ................
     .......kk.......
     ......kNNk......
     .....kNNNNk.....
     .....kNNNNk.....
     ....kzzzzzzk....
     ....kzZZZzyk....
     ....kzZZZzyk....
     ....kyzzzyyk....
     .....kyyyyk.....
     ......kkkk......
     ................
     ................
     ................`,
  verdurstend: `................
     ................
     ................
     .......kk.......
     ......k98k......
     ......k98k......
     .....k98k9k.....
     .....k9k98k.....
     ....k98k898k....
     ....k8k9k88k....
     .....k898kk.....
     ......kkkk......
     ................
     ................
     ................
     ................`,
  ertrinkend: `................
     ................
     ................
     ................
     ........kk......
     .......kYYk.....
     .....k.kzYk.....
     ....kYk.kk......
     ...ZZkZZzZZz....
     ....zzzyzzzz....
     .....yyxyyx.....
     ......xxwx......
     .......ww.......
     ................
     ................
     ................`,
};

export default Object.entries(ZUSTAND_ARTEN).map(([id, art]) => {
  const motiv = MOTIVE[id];
  if (motiv === undefined) throw new Error(`Zustands-Icon: Motiv für ${id} fehlt`);
  const glanz = ['nachtsicht', 'geblendet'].includes(id) ? 'Glanzpunkt in der Pupille als Einzelpixel' : undefined;
  return zustand(id, art, motiv, glanz === undefined ? {} : { einzelpixel: glanz });
});
