/**
 * UI theme foundation (MASTERPROMPT §26 "eine Palette, ein UI-Stil", "ganzzahlige UI-Skalierung
 * (Auto oder 1×–4×)").
 *
 * - Colours: the eight UI colours of the master palette (`UI_HEX`, generated by `npm run assets`)
 *   become CSS custom properties on the root element: `rahmenHell` → `--dh-rahmen-hell`. The
 *   stylesheets (`base.css`) only reference these tokens, so the palette is the single source.
 * - Scale: `--dh-ui-scale` is a whole number 1–4. "Auto" picks the largest factor at which the
 *   480×270 reference frame (the 16:9 internal image of §4.2) fits into the viewport; the
 *   accessibility setting `uiScale` can fix it at 1×–4×. CSS sizes are written as
 *   `calc(<px> * var(--dh-ui-scale))`, so pixel art stays on whole pixels.
 */
import { computed, effect, signal, type ReadonlySignal } from '@preact/signals';
import type { Settings } from '../engine/settings';
import { UI_HEX } from '../generated/palette';
import { INTERNAL_HEIGHT } from '../render/viewport';

/** The `accessibility.uiScale` setting: `'auto'` or a fixed factor. */
export type UiScaleSetting = Settings['accessibility']['uiScale'];
/** An applied UI scale factor. */
export type UiScale = Exclude<UiScaleSetting, 'auto'>;
/** Names of the palette's UI colours. */
export type UiColorName = keyof typeof UI_HEX;

/** Smallest and largest UI scale factor (§26: 1×–4×). */
export const MIN_UI_SCALE = 1;
export const MAX_UI_SCALE = 4;
/** Reference frame of scale 1× [CSS px]: 270 px high (§4.2) at 16:9. */
export const UI_REFERENCE_HEIGHT = INTERNAL_HEIGHT;
export const UI_REFERENCE_WIDTH = (INTERNAL_HEIGHT * 16) / 9;
/** CSS custom property holding the UI scale factor. */
export const UI_SCALE_VAR = '--dh-ui-scale';
/** Prefix of every theme custom property. */
const VAR_PREFIX = '--dh-';

const UI_SCALE_FACTORS: readonly UiScale[] = [1, 2, 3, 4];

function toUiScale(n: number): UiScale {
  const whole = Math.floor(Number.isFinite(n) ? n : MIN_UI_SCALE);
  const clamped = Math.min(MAX_UI_SCALE, Math.max(MIN_UI_SCALE, whole));
  return UI_SCALE_FACTORS[clamped - MIN_UI_SCALE] ?? MIN_UI_SCALE;
}

/** Automatic UI scale for a viewport of `width`×`height` CSS px: ⌊min(w/480, h/270)⌋ clamped to 1–4. */
export function autoUiScale(width: number, height: number): UiScale {
  return toUiScale(Math.min(width / UI_REFERENCE_WIDTH, height / UI_REFERENCE_HEIGHT));
}

/** The factor to apply: the fixed setting, or `autoUiScale` for `'auto'`. */
export function resolveUiScale(setting: UiScaleSetting, width: number, height: number): UiScale {
  return setting === 'auto' ? autoUiScale(width, height) : setting;
}

/** CSS custom property of a UI colour: `rahmenHell` → `--dh-rahmen-hell`. */
export function themeColorVar(name: UiColorName): string {
  return VAR_PREFIX + name.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
}

/** Every colour token as `[custom property, hex]`, in palette order. */
export const THEME_COLORS: ReadonlyArray<readonly [string, string]> = (Object.keys(UI_HEX) as UiColorName[]).map((name) => [themeColorVar(name), UI_HEX[name]] as const);

/** All custom properties the theme defines (colours and the scale). */
export const THEME_VARS: readonly string[] = [...THEME_COLORS.map(([name]) => name), UI_SCALE_VAR];

/** Element whose inline style receives the tokens (the document root in the browser, a fake in tests). */
export interface StyleTarget {
  readonly style: { setProperty(name: string, value: string): void };
}

/** Writes every colour token to `target`. */
export function applyThemeColors(target: StyleTarget): void {
  for (const [name, hex] of THEME_COLORS) target.style.setProperty(name, hex);
}

export interface ThemeOptions {
  /** Current `accessibility.uiScale` setting. */
  readonly setting: UiScaleSetting;
  /** Viewport size [CSS px]. */
  readonly width: number;
  readonly height: number;
}

export interface Theme {
  /** The applied UI scale factor (also written to `--dh-ui-scale`). */
  readonly uiScale: ReadonlySignal<UiScale>;
  /** Report a new viewport size [CSS px] (window resize). */
  setViewport(width: number, height: number): void;
  /** Apply a changed `accessibility.uiScale` setting. */
  setUiScaleSetting(setting: UiScaleSetting): void;
  /** Stops updating `--dh-ui-scale`. */
  dispose(): void;
}

/** Applies the colour tokens to `target` and keeps `--dh-ui-scale` in step with setting and viewport. */
export function createTheme(target: StyleTarget, options: ThemeOptions): Theme {
  applyThemeColors(target);
  const setting = signal<UiScaleSetting>(options.setting);
  const width = signal(options.width);
  const height = signal(options.height);
  const uiScale = computed(() => resolveUiScale(setting.value, width.value, height.value));
  const stop = effect(() => {
    target.style.setProperty(UI_SCALE_VAR, String(uiScale.value));
  });
  return {
    uiScale,
    setViewport(w, h) {
      width.value = w;
      height.value = h;
    },
    setUiScaleSetting(next) {
      setting.value = next;
    },
    dispose: stop,
  };
}
