/**
 * Laubbaum des Grünhains (M1-22, docs/ART.md §3): 48×64, Krone aus neun Blattmassen – jede oben hell
 * (Himmel), unten dunkel, hintere Massen im Kontaktschatten der vorderen –, Kontur `gras.0`. Stamm mit
 * Rindenfurchen und Wurzelansatz, unter der Krone verschattet. Die Krone trägt Blätterdach (Dither-
 * Ausblendung um den Spieler) und Wind-Biegung; Jahreszeiten färben sie über die Rampe `gras`
 * (paletteRows.ts). Occluder: Ellipse am Stammfuß.
 */
import { sprite } from '../../lib/sprite';

export default sprite({
  id: 'baum_laub',
  group: 'gruenhain_basis',
  size: [48, 64],
  anchor: [24, 62],
  hoehe: 'kugel',
  legende: {
    '.': null,
    o: 'gras.0',
    D: 'gras.1',
    d: 'gras.2',
    g: 'gras.3',
    l: 'gras.4',
    L: 'gras.5',
    p: 'holz.0',
    h: 'holz.1',
    w: 'holz.2',
    W: 'holz.3',
  },
  material: { dach: 'oDdglL', wind: 'oDdglL' },
  frames: [
    `................................................
     .......................ooo......................
     ...................ooooLLLooo...................
     ..................oLLLLLLLLLLo..................
     ................ooLLLLLLLLLLLLo.................
     ...............oLLlLLLLlLLLLlLLo................
     ...............ollllllllllllllllo...............
     ..........ooo..olllllllllllllllllo.ooo..........
     .........oLLLoolllgllllgllllgllllooLLLo.........
     ........oLLLLLLdddggllgggllgggdddLLLLLLo........
     .......oLLLLLLLLLLggggggggggggLLLLLLLLLLo.......
     ......oLLLlLLLLlLLLgggggggggllLLLLlLLLLllo......
     .....olLllllLllllLllgggggggdllllllllllllllo.....
     .....olllllllllllllllgdddddgllllllllllllllo.....
     .....ollllgllllglldddlllllllllllllgllllgllo.....
     ....ogggggllgggggglllllllllllddgggggllgggggo....
     ....ogggglgglggggllllllllllllllgggglgglggggo....
     ....ogggggggggggllllllllllllllllgggggggggggo....
     ....ogggggggggglllllllllllllllllgggggggggggo....
     ....odddgDDgggdllllgllllgllllgllggdggdddddgo....
     ....ollllllldddlllgggllgggllggglldddlllllllo....
     ...oollllllldddgggllggggllgggggggddlllllllloo...
     ..ollllllllllDDddlgglgglgglggggggDDllllllllllo..
     .ollllllllddddllldddgggggggggdddllldddllllllllo.
     .ollllglllllllllllllggggggggllllllllllllllllllo.
     oglllgglllllllllllllggggdgddllllllllllllllgglllo
     ogggggggllllllllllllldddddllllllllllllllgggggggo
     ogggggggllllllllllllllDDDDddllllllllllllgggggggo
     .oggggdglgllllglllldddlllllllgllllgllllgggggggo.
     .ogggdddgggglggggllllllllllllggllgggllggggddggo.
     .odddddggggllggggglllllllllllggggggggllggdggddo.
     ..odddDggglgglggglllllllllllllgggggglgglggddgo..
     ...odDDggggggggggllllllllllllllggggggggggdDDo...
     ....oDDogddgggddglllgglllgglllgggddgggddgDDo....
     .....ooodddddddddggggggggggggggdddddddddooo.....
     .......odddddddddggggggggggggggddddddddo........
     ........odddddDddggggggggggggggdddDddddo........
     .........ooddDDDdgggddgggddgggdddDDDooo.........
     ...........oDDoDDDdddddddddddddooDDo............
     ............oo.ooooddddddddddoo..oo.............
     ..................odDDdddDDddo..................
     ..................poDDDDDDooop..................
     ..................phoooooohhhp..................
     ..................phhhwhhwhhhp..................
     ..................phwhwwhwwhhp..................
     ..................phwwhWwhwwhp..................
     ..................phwWhWwWhwhp..................
     ..................phwWhWWwhwhp..................
     ..................phwWhwWwhWhp..................
     ..................phwWwhWwhWhp..................
     ..................phwWwhWwphhp..................
     ..................phwwwhWhpphp..................
     ..................phwWwhWwhhhp..................
     ..................phwWwwhWwWhp..................
     ..................phwWWwhWwWhp..................
     .................phhwWWwhWwWwhp.................
     .................phwwWwwhwWwwhp.................
     ................phhwwWwhwhWwwhhp................
     ...............phhwhwWwhwhwWwhwhp...............
     ..............phhwhhwWwhwhwWwhhwhp..............
     ..............phwhpphwwhphhwwhpphp..............
     ..............pppp.pphwhphhwhp.ppp..............
     ...................pppppppppp...................
     ................................................`,
  ],
  hitbox: [19, 57, 10, 5],
  occluder: { kind: 'ellipse', x: 24, y: 60, rx: 5, ry: 2 },
});
