/**
 * Item-Icons der Waffen, Schilde, Munition und Wurfwaffen (M6-11, M6-09, M6-08; Items src/content/items/{waffen,
 * munition,schilde}.ts). Konvention und Legende: `assets-src/sprites/icons/_icon.ts`.
 *
 * Bildsprache wie die Werkzeug-Icons: Nahkampfwaffen schräg von links unten (Griff) nach rechts oben (Klinge, Kopf),
 * Bögen und Schilde aufrecht, Munition als kleines Bündel. Metall ist in der Rampe `stein` gezeichnet (Ziffern `1`–`6`) und
 * wird über den Materialstufen-Generator Bronze (`stufenSprites`, `_waffe.ts`); die T0-Waffe derselben Klasse ist die
 * eigene Form der Steinstufe (geschlagener Feuerstein, Stein, Knochen) – Holz `a`–`e`, Leder `p`–`t`, Schnur und Knochen
 * `A`–`E`, Glanz `#`.
 *
 * - Brandpfeil und Brandflasche: glühende Spitze bzw. brennender Lappen (`feuer`, emissiv); Giftpfeil: grünlich
 *   triefende Spitze (`gras`); Leuchtpfeil: leuchtender Pilzkopf (`eis`, emissiv); Stumpfpfeil: Harzknauf statt Spitze.
 * - Schleudersteine: drei runde Kiesel; Bolzen: kurz, dick, Bronzespitze, Lederfahnen.
 */
import type { Sprite } from '../../lib/sprite';
import { icon } from '../icons/_icon';
import { stufenSprites } from './_waffe';

/** Die Spitze des Leuchtpfeils leuchtet wie der Leuchtpilz, aus dem sie ist (`icon_leuchtpilz`); Flammen im Icon sind keine Lichtquelle. */
const LEUCHT = { legende: { '0': 'eis.3*', '#': 'eis.4*' } } as const;

const i = (id: string, raster: string, o: Parameters<typeof icon>[2] = {}): Sprite => icon(id, raster, o);

// ---------------------------------------------------------------------------------------------
// Nahkampf
// ---------------------------------------------------------------------------------------------

const schwert = i(
  'form_schwert',
  `................
   .............k..
   ............k6k.
   ...........k56k.
   ..........k456k.
   .........k3456k.
   ........k3456k..
   .......k3456k...
   ......k3456k....
   ..kk.k3456k.....
   ..k5kk345k......
   ...k45kkk.......
   ..krqk45k.......
   .krqk.kk........
   ..kk............
   ................`,
);

const feuersteinklinge = i(
  'form_feuersteinklinge',
  `................
   .............k..
   ............k5k.
   ...........k64k.
   ..........k543k.
   .........k6534k.
   ........k4653k..
   .......k6534k...
   ......k4653k....
   .....kCBk3k.....
   ....kBCBkk......
   ....kcbk........
   ...kcbk.........
   ..kcbk..........
   ..kk............
   ................`,
);

const kampfaxt = i(
  'form_kampfaxt',
  `................
   ..kk............
   .k65kk......kk..
   .k6554kk..kbak..
   ..k6544kkkbak...
   ..k65433kbak....
   ..k6543kbak.....
   .k6544kbak......
   .k655kbak.......
   .k65kbak........
   ..kkbak.........
   ..kqrk..........
   .kqrk...........
   .kbak...........
   ..kk............
   ................`,
);

const steinkampfaxt = i(
  'form_steinkampfaxt',
  `................
   ................
   ..kkk.......kk..
   .k6554k...kdck..
   .k65443kkkdck...
   .k6543CBCBck....
   .k5432BCdck.....
   .k432kkdck......
   ..kkkkdck.......
   ....kdck........
   ...kdck.........
   ..kBCk..........
   .kCBk...........
   .kdck...........
   ..kk............
   ................`,
);

const streitkolben = i(
  'form_streitkolben',
  `................
   ..........kk....
   ........kkk6kk..
   .......k6k55k6k.
   ......kk654435k.
   ......k65443kk..
   .......k5433k...
   ......kbkk3k....
   .....kbak.k.....
   ....kbak........
   ...kbak.........
   ..kqrk..........
   .kqrk...........
   .k3k............
   ..k.............
   ................`,
);

const knochenkeule = i(
  'form_knochenkeule',
  `................
   ..........kk....
   .........kE#kk..
   ........kDE#E#k.
   ........kDDEE#k.
   .......kDDEEEk..
   ......kDDEEk#k..
   .....kDDEEk.k...
   ....kDDEEk......
   ...kBCBkk.......
   ..kCBCk.........
   .kBCBk..........
   .kDEk...........
   .kEk............
   ..k.............
   ................`,
);

const holzkeule = i(
  'holzkeule',
  `................
   .........kkk....
   ........kdeek...
   .......kcdedek..
   ......kcddcdek..
   ......kbcdcdck..
   .....kbccdcdk...
   ....kbbcdcck....
   ...kabbcck......
   ..kabbkk........
   ..kabk..........
   .kabk...........
   .kbk............
   ..k.............
   ................
   ................`,
);

const speer = i(
  'form_speer',
  `................
   .............k..
   ............k6k.
   ...........k65k.
   ..........k654k.
   .........k6543k.
   .........k543k..
   ........kk43k...
   .......kbakk....
   ......kbak......
   .....kbak.......
   ....kqrk........
   ...kqrk.........
   ..kbak..........
   ..kkk...........
   ................`,
);

const dolch = i(
  'form_dolch',
  `................
   ................
   ...........k....
   ..........k6k...
   .........k56k...
   ........k456k...
   .......k3456k...
   ......k3456k....
   ...kk.k345k.....
   ...k5kk34k......
   ....k45kkk......
   ...krqk45k......
   ..krqk.kk.......
   ..kk............
   ................
   ................`,
);

const knochendolch = i(
  'form_knochendolch',
  `................
   ................
   ...........k....
   ..........k#k...
   .........kE#k...
   ........kDE#k...
   .......kDEEk....
   ......kDDEk.....
   .....kDDEk......
   ....kBCBk.......
   ...kCBCk........
   ..kBCBk.........
   ..kDEk..........
   ..kkk...........
   ................
   ................`,
);

const kriegshammer = i(
  'form_kriegshammer',
  `................
   ......kkkkkkkk..
   .....k66555566k.
   .kk55544444445k.
   ..kk3333333334k.
   .....k33322333k.
   ......kkkbakkkk.
   .......kbak.....
   ......kbak......
   .....kbak.......
   ....kbak........
   ...kqrk.........
   ..kqrk..........
   .kbak...........
   ..kk............
   ................`,
);

const felsbrecher = i(
  'form_felsbrecher',
  `................
   .....kkkkkkk....
   ....k5665566k...
   ...k655443456k..
   ...k54433BC34k..
   ...k4332CB323k..
   ....k322BC22k...
   .....kkkdckk....
   ......kdck......
   .....kdck.......
   ....kdck........
   ...kBCk.........
   ..kCBk..........
   .kdck...........
   ..kk............
   ................`,
);

const zweihaender = i(
  'form_zweihaender',
  `................
   ...........kkk..
   ..........k666k.
   .........k4566k.
   ........k34566k.
   .......k23456k..
   ......k23456k...
   .....k23456k....
   ..kk.k2345k.....
   ..k5kk234k......
   ...k45kkk.......
   ..krqk45k.......
   .krqk.kk........
   .k3k............
   ..k.............
   ................`,
);

const grossaxt = i(
  'form_grossaxt',
  `................
   ..kkk...........
   .k6655kk....kk..
   .k65544kk.kbak..
   .k654433kkbak...
   .k654333kbak....
   .k65433kbak.....
   .k6543kbak......
   .k654kbak.......
   .k65kbak........
   ..kkbak.........
   ..kqrk..........
   .kqrk...........
   .kbak...........
   ..kk............
   ................`,
);

// ---------------------------------------------------------------------------------------------
// Fernkampf
// ---------------------------------------------------------------------------------------------

const kurzbogen = icon(
  'kurzbogen',
  `................
   ....kkk.........
   ....Ekdck.......
   ....E.kdck......
   ....E..kdck.....
   ....E...kdck....
   ....E...kdck....
   ....E...kqrk....
   ....E...kqrk....
   ....E...kdck....
   ....E...kdck....
   ....E..kdck.....
   ....E.kdck......
   ....Ekdck.......
   ....kkk.........
   ................`,
);

const kompositbogen = icon(
  'kompositbogen',
  `................
   .....kkk........
   ....kD#k........
   ....EkDkk.......
   ....E.kbak......
   ....E..kbak.....
   ....E..ksak.....
   ....E..kqrk.....
   ....E..kqrk.....
   ....E..ksak.....
   ....E..kbak.....
   ....E.kbak......
   ....EkDkk.......
   ....kD#k........
   .....kkk........
   ................`,
);

const schleuder = icon(
  'schleuder',
  `................
   ................
   ......kkkk......
   .....kqrrqk.....
   ....kq3443qk....
   ....kr4332rk....
   ....kq3322qk....
   .....kqrrqk.....
   ......kCCk......
   .....kCkkCk.....
   ....kCk..kCk....
   ...kCk....kCk...
   ..kCk......kCk..
   ..kBk......kBk..
   ...k........k...
   ................`,
);

const armbrust = i(
  'form_armbrust',
  `................
   ......kkkk......
   ......k55k......
   .kkkkkk54kkkkkk.
   .kdddddccdddddk.
   .kcckkkcbkkkcck.
   ..kkE.kcbk.Ekk..
   .....Ek43kE.....
   ......kcbk......
   ......kcbk......
   ......k34k......
   ......kcbk......
   ......kcbk......
   ......kcbk......
   .......kk.......
   ................`,
);

const holzschild = icon(
  'holzschild',
  `................
   .....kkkkkk.....
   ...kkqrrrrqkk...
   ..kqcddcddcbqk..
   ..krdcddcdcbrk..
   .kqcddckkcdbbqk.
   .krcdckeekcbbrk.
   .krdcdkedkcbbrk.
   .kqcddckkcdbbqk.
   ..krcdcddcbbrk..
   ..kqcddcdcbbqk..
   ...kkqrrrrqkk...
   .....kkkkkk.....
   ................
   ................
   ................`,
);

const bronzeschild = i(
  'form_bronzeschild',
  `................
   .....kkkkkk.....
   ...kk566655kk...
   ..k5cddcddcb4k..
   ..k6dcddcdcb3k..
   .k5cddckkcdbb3k.
   .k6cdck65kcbb2k.
   .k5dcdk54kcbb2k.
   .k5cddckkcdbb2k.
   ..k4cdcddcbb2k..
   ..k3cddcdcbb1k..
   ...kk322211kk...
   .....kkkkkk.....
   ................
   ................
   ................`,
);

// ---------------------------------------------------------------------------------------------
// Munition
// ---------------------------------------------------------------------------------------------

/** Pfeil mit Spitze aus `spitze` (Zeilen 1–4 rechts oben) und Federn hinten links. */
const pfeil = (spitze: readonly [string, string, string, string]): string =>
  `................
   ..........${spitze[0]}.
   ..........${spitze[1]}.
   .........${spitze[2]}.
   .........${spitze[3]}.
   .........kck....
   ........kck.....
   .......kck......
   ......kck.......
   ...kkkck........
   ..kLlkck........
   ..kLlckk........
   ..kkLlk.........
   ..klLk..........
   .kkkk...........
   ................`;

const pfeilStein = i('form_pfeil', pfeil(['..kk.', '.k65k', 'k6543k', 'kk43kk']));
const pfeilFeuerstein = i('form_pfeil_feuerstein', pfeil(['..kk.', '.k56k', 'k6452k', 'kk42kk']));

const pfeilStumpf = icon('pfeil_stumpf', pfeil(['..kk.', '.kCDk', 'kBCDDk', 'kkBCkk']));

const pfeilFeuer = icon('pfeil_feuer', pfeil(['.kVk.', 'kVvvk', 'kvuuFk', 'kkFFkk']));

const pfeilGift = icon('pfeil_gift', pfeil(['..kk.', '.k6hk', 'k6hiGk', 'kkiGkk']));

const pfeilLeucht = icon('pfeil_leucht', pfeil(['..kk.', '.k#0k', 'k#009k', 'kk09kk']), LEUCHT);

const bolzen = i(
  'form_bolzen',
  `................
   ................
   ................
   ................
   ..........kkk...
   .........k654k..
   ........k6543k..
   .......kbkk3k...
   ......kbak.k....
   .....kbak.......
   ....kbak........
   ..kkbak.........
   .kqpkk..........
   .kpqpk..........
   ..kkk...........
   ................`,
);

const schleuderstein = icon(
  'schleuderstein',
  `................
   ................
   ................
   ................
   ........kkk.....
   .......k554k....
   ......k54432k...
   ...kkkk4322k....
   ..k5544kk21k....
   .k543322kkkkk...
   .k43221k.k543k..
   ..k211k.k54321k.
   ...kkk..k43221k.
   ........kk211k..
   ..........kkk...
   ................`,
);

// ---------------------------------------------------------------------------------------------
// Wurfwaffen
// ---------------------------------------------------------------------------------------------

const wurfmesser = i(
  'form_wurfmesser',
  `................
   ................
   ...........kk...
   ..........k65k..
   .........k654k..
   ........k6543k..
   .......k6543k...
   ...kk.k543k.....
   ...k5k543k......
   ....k453k.......
   ...kqkk3k.......
   ..kqrk.k........
   ..krqk..........
   ...kk...........
   ................
   ................`,
);

const wurfmesserFeuerstein = i(
  'form_wurfmesser_feuerstein',
  `................
   ................
   ...........kk...
   ..........k65k..
   .........k654k..
   ........k6543k..
   .......k6542k...
   ......k5432k....
   ......kk42k.....
   .....kBCkk......
   ....kCBk........
   ...kBCk.........
   ..kCBk..........
   ..kkk...........
   ................
   ................`,
);

const brandflasche = icon(
  'brandflasche',
  `................
   ........kk......
   .......kVUk.....
   ......kUvVUk....
   .......kvUk.....
   ......kkCCkk....
   .....kqrCCrqk...
   .....kkqrrqkk...
   ....kqrssrrqpk..
   ...kqrsBAsrqqpk.
   ...kqrsABsrrqpk.
   ...kqrssrrrqqpk.
   ....kqqrrqqqpk..
   .....kkpppppk...
   ......kkkkkk....
   ................`,

);

export default [
  ...stufenSprites({ metall: schwert, bronze: 'bronzeschwert', stein: { form: feuersteinklinge, id: 'feuersteinklinge' } }, 'icon_'),
  ...stufenSprites({ metall: kampfaxt, bronze: 'bronzekampfaxt', stein: { form: steinkampfaxt, id: 'steinkampfaxt' } }, 'icon_'),
  ...stufenSprites({ metall: streitkolben, bronze: 'bronzestreitkolben', stein: { form: knochenkeule, id: 'knochenkeule' } }, 'icon_'),
  holzkeule,
  ...stufenSprites({ metall: speer, bronze: 'bronzespeer' }, 'icon_'),
  ...stufenSprites({ metall: dolch, bronze: 'bronzedolch', stein: { form: knochendolch, id: 'knochendolch' } }, 'icon_'),
  ...stufenSprites({ metall: kriegshammer, bronze: 'bronzekriegshammer', stein: { form: felsbrecher, id: 'felsbrecher' } }, 'icon_'),
  ...stufenSprites({ metall: zweihaender, bronze: 'bronzezweihaender' }, 'icon_'),
  ...stufenSprites({ metall: grossaxt, bronze: 'bronzegrossaxt' }, 'icon_'),
  kurzbogen,
  kompositbogen,
  schleuder,
  ...stufenSprites({ metall: armbrust, bronze: 'armbrust' }, 'icon_'),
  holzschild,
  ...stufenSprites({ metall: bronzeschild, bronze: 'bronzeschild' }, 'icon_'),
  ...stufenSprites({ metall: pfeilStein, bronze: 'pfeil_bronze', stein: { form: pfeilFeuerstein, id: 'pfeil_feuerstein' } }, 'icon_'),
  pfeilStumpf,
  pfeilFeuer,
  pfeilGift,
  pfeilLeucht,
  ...stufenSprites({ metall: bolzen, bronze: 'bolzen_bronze' }, 'icon_'),
  schleuderstein,
  ...stufenSprites({ metall: wurfmesser, bronze: 'wurfmesser_bronze', stein: { form: wurfmesserFeuerstein, id: 'wurfmesser_feuerstein' } }, 'icon_'),
  brandflasche,
];
