/**
 * Deko, Pflanzen und Textilien T0–T1 (M4-19; docs/SPIEL.md §8 `blumentopf`, `vase_keramik`, `topfpflanze`,
 * `pflanzkuebel`, `teppich_stroh`, `uhr_sonne`, `vogelhaus`, `holzstapel`, `wegweiser`).
 * Blätter tragen das Wind-Flag (sie wiegen im Shader), der Teppich liegt flach (Boden, begehbar).
 */
import { moebel } from './_moebel';

/** Blumentopf: Terrakottatopf mit Rand, rote Blüten mit Blättern (Blütenfarben über Palettenzeilen umfärbbar). 1×1, auch auf dem Tisch. */
const blumentopf = moebel({
  item: 'blumentopf',
  size: [16, 16],
  anchor: [8, 14],
  hoehe: 'kugel',
  frames: [
    `................
     ....kk....kk....
     ...kMMk..kMMk...
     ..kMomMkkMomMk..
     ..kmMMmkkmMMmk..
     ...kmmkMMkmmk...
     ...kkhkMomkhkk..
     ..khihkmmkhihk..
     ..kkhiihhiihkk..
     ...kttttttttk...
     ...ksssssssrk...
     ....krsssrrk....
     ....krrsrrrk....
     ....kqrrrrqk....
     .....kkkkkk.....
     ................`,
  ],
  occluder: { kind: 'ellipse', x: 8, y: 13, rx: 4, ry: 2 },
});

/** Keramikvase: bauchige Vase mit blauer Glasur und hellem Wellenband, darin zwei Halme. 1×1, auch auf dem Tisch. */
const vase = moebel({
  item: 'vase_keramik',
  size: [16, 16],
  anchor: [8, 15],
  hoehe: 'zylinder',
  frames: [
    `................
     ........k.......
     .......kik......
     ......kihk......
     .....kkhkk......
     ......kZZk......
     .....kyzzyk.....
     .....kkyykk.....
     ....kyzZZzyk....
     ...kyzZZZZzyk...
     ...kYYzYYzYYk...
     ...kzYYzzYYzk...
     ...kyzzzzzzyk...
     ....kyyyyyyk....
     .....kxxxxk.....
     ......kkkk......`,
  ],
  occluder: { kind: 'ellipse', x: 8, y: 14, rx: 4, ry: 2 },
});

/** Topfpflanze: Tontopf mit einem großen, gefächerten Blattbusch. 1×1. */
const topfpflanze = moebel({
  item: 'topfpflanze',
  size: [16, 20],
  anchor: [8, 18],
  hoehe: 'kugel',
  wind: 'jih',
  frames: [
    `................
     ......kkk.......
     .....kjjik.kk...
     ..kk.kjiik.kjik.
     .kjik.khik.kjik.
     .kjiikkhkkkjiik.
     ..kiihkikkhiik..
     ..kkhkjjikkhkk..
     .kjikkjiihkkjik.
     .kjiihkhihkhiik.
     ..kiihkhhkhiik..
     ...kkhghghhkk...
     ....kkgghgkk....
     ...kttttttttk...
     ...ksssssssrk...
     ....krsssrrk....
     ....krrsrrrk....
     ....kqrrrrqk....
     .....kkkkkk.....
     ................`,
  ],
  occluder: { kind: 'ellipse', x: 8, y: 17, rx: 4, ry: 2 },
});

/** Pflanzkübel: langer Holzkasten auf zwei Füßen mit gelben Blüten und Blattwerk. 2×1. */
const pflanzkuebel = moebel({
  item: 'pflanzkuebel',
  size: [32, 20],
  anchor: [16, 17],
  hoehe: 'block',
  wind: 'ihg',
  frames: [
    `................................
     ................................
     ....kk......kk.......kk.........
     ...kook....kook.....kook...kk...
     ..koMMok..koMMokk..koMMok.kook..
     ...kook.kkkkookhik..kook.koMMok.
     ..kkhkkkooMkkhiihkkkkhkkkkookk..
     .khiihkkoMMokkhhkkhiikkhikkhk...
     .kkhhiihkookhiihkhiihhkhhiihkk..
     .kgghhghhkkhgghhghhgghhghhgghk..
     .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
     .keeeeeeeeeeeeeeeeeeeeeeeeeeeek.
     .kdddcdddddddddcddddddddddcdddk.
     .kdddcdddddddddcddddddddddcdddk.
     .kbbbcbbbbbbbbbcbbbbbbbbbbcbbbk.
     .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
     ..kdbk..................kdbk....
     ..kkkk..................kkkk....
     ................................
     ................................`,
  ],
  occluder: { kind: 'rect', x: 2, y: 10, w: 28, h: 7 },
});

/** Strohteppich: geflochtene Matte mit doppelter Randborte, versetzten Querhalmen und einer Raute aus rot gefärbten Halmen, Fransen an den Schmalseiten. Liegt flach auf dem Boden (begehbar). 2×2. */
const teppich = moebel({
  item: 'teppich_stroh',
  size: [32, 32],
  anchor: [16, 30],
  hoehe: 'flach',
  frames: [
    `................................
     ...C.C.C.C.C.C.C.C.C.C.C.C.C....
     .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
     .kCCCCCCCCCCCCCCCCCCCCCCCCCCCCk.
     .kCBBBBBBBBBBBBBBBBBBBBBBBBBBCk.
     .kCBCCDDCCDDCCDDCCDDCCDDCCDDBCk.
     .kCBDDDDEEDDDDEEDDDDEEDDDDEEBCk.
     .kCBDDDDEEDDDDEEDDDDEEDDDDEEBCk.
     .kCBCCDDCCDDCCDmmCDDCCDDCCDDBCk.
     .kCBDDEEDDDDEEmmmmEEDDDDEEDDBCk.
     .kCBDDEEDDDDEmmDDmmEDDDDEEDDBCk.
     .kCBCCDDCCDDmmDDCCmmCCDDCCDDBCk.
     .kCBEEDDDDEmmDDllEDmmDEEDDDDBCk.
     .kCBEEDDDDmmDDllllDDmmEEDDDDBCk.
     .kCBCCDDCmmDCllDCllDCmmDCCDDBCk.
     .kCBDDDDmmDDllEEDDllEEmmDDEEBCk.
     .kCBDDDDmmDDllEEDDllEEmmDDEEBCk.
     .kCBCCDDCmmDCllDCllDCmmDCCDDBCk.
     .kCBDDEEDDmmEEllllEEmmDDEEDDBCk.
     .kCBDDEEDDDmmEDllDEmmDDDEEDDBCk.
     .kCBCCDDCCDDmmDDCCmmCCDDCCDDBCk.
     .kCBEEDDDDEEDmmDEmmDDDEEDDDDBCk.
     .kCBEEDDDDEEDDmmmmDDDDEEDDDDBCk.
     .kCBCCDDCCDDCCDmmCDDCCDDCCDDBCk.
     .kCBDDDDEEDDDDEEDDDDEEDDDDEEBCk.
     .kCBDDDDEEDDDDEEDDDDEEDDDDEEBCk.
     .kCBCCDDCCDDCCDDCCDDCCDDCCDDBCk.
     .kCBBBBBBBBBBBBBBBBBBBBBBBBBBCk.
     .kCCCCCCCCCCCCCCCCCCCCCCCCCCCCk.
     .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
     ...C.C.C.C.C.C.C.C.C.C.C.C.C....
     ................................`,
  ],
  occluder: { kind: 'none' },
  schatten: 'none',
});

/** Sonnenuhr: Steinsäule mit Fuß und runder Zifferblattplatte, darauf ein bronzener Zeiger (Metallflag). 1×1. */
const sonnenuhr = moebel({
  item: 'uhr_sonne',
  size: [16, 20],
  anchor: [8, 18],
  hoehe: 'zylinder',
  metall: true,
  frames: [
    `................
     ................
     ....kkkkkkkk....
     ..kk56565656kk..
     .k55555kk55555k.
     .k6555kTWk5556k.
     .k555kTWk55555k.
     .k65kTWk555556k.
     ..kkkkkk4444kk..
     ...kkkkkkkkkk...
     ....kk4444kk....
     .....k4443k.....
     .....k4443k.....
     .....k4343k.....
     .....k4443k.....
     ....kk3333kk....
     ...k55555555k...
     ...k44443444k...
     ...kkkkkkkkkk...
     ................`,
  ],
  occluder: { kind: 'rect', x: 4, y: 15, w: 8, h: 3 },
});

/** Vogelhaus: Häuschen mit rotem Schindeldach und Flugloch auf einem Pfahl mit Fußbrett. 1×1. */
const vogelhaus = moebel({
  item: 'vogelhaus',
  size: [16, 32],
  anchor: [8, 29],
  hoehe: 'block',
  frames: [
    `................
     .......kk.......
     ......kmmk......
     .....kmMMmk.....
     ....kmMmmMmk....
     ...kmMmllmMmk...
     ..kmMmlkklmMmk..
     .kllllkddklllllk
     .kkkkkdddekkkkk.
     ...kdddddddek...
     ...kddkkkdddk...
     ...kddkKkdddk...
     ...kddkKkcddk...
     ...kddkbkdddk...
     ...kcccccccck...
     ...kbbbbbbbbk...
     ....kkkdckkk....
     ......kdck......
     ......kdck......
     ......kdck......
     ......kdck......
     ......kdck......
     ......kdck......
     ......kdck......
     ......kdck......
     ......kdck......
     ....kkkdckkk....
     ...kddddcccdk...
     ...kcccccccck...
     ....kkkkkkkk....
     ................
     ................`,
  ],
  occluder: { kind: 'rect', x: 6, y: 26, w: 4, h: 2 },
});

/**
 * Holzstapel: runde Scheite in drei Lagen (4 · 3 · 2), dicht gepackt – jede Lage liegt in den Mulden der
 * darunter –, Stirnseiten rund mit hellem Splint, Jahresring und dunklem Kern, dunkle Zwickel zwischen den
 * Scheiten; seitlich zwei Pflöcke halten den Stapel. 2×1.
 */
const holzstapel = moebel({
  item: 'holzstapel',
  size: [32, 20],
  anchor: [16, 17],
  hoehe: 'block',
  frames: [
    `................................
     ...........kkk...kkk............
     ..k.......kdeek.kdeek........k..
     .kbk.....kedccekedccek......kbk.
     .kbk.....kdcbcdkdcbcdk......kbk.
     .kbk.....kdccdckdccdck......kbk.
     .kbk....kkkddckkkddckkk.....kbk.
     .kbk...kdeekkkdeekkkdeek....kbk.
     .kbk..kedccekedccekedccek...kbk.
     .kbk..kdcbcdkdcbcdkdcbcdk...kbk.
     .kbk..kdccdckdccdckdccdck...kbk.
     .kbk.kkkddckkkddckkkddckkk..kbk.
     .kbkkdeekkkdeekkkdeekkkdeek.kbk.
     .kbkedccekedccekedccekedccekkbk.
     .kbkdcbcdkdcbcdkdcbcdkdcbcdkkbk.
     .kbkdccdckdccdckdccdckdccdckkbk.
     .kbkkddckakddckakddckakddckakbk.
     .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
     ................................
     ................................`,
  ],
  occluder: { kind: 'rect', x: 1, y: 10, w: 30, h: 8 },
});

/** Wegweiser: Pfahl mit zwei Pfeilbrettern nach links und rechts, eingebrannte Schriftzeichen, Fußbrett. 1×1. */
const wegweiser = moebel({
  item: 'wegweiser',
  size: [16, 31],
  anchor: [8, 29],
  hoehe: 'block',
  frames: [
    `................
     ......kkkk......
     ......kdck......
     ..kkkkkkkkkkk...
     ..keeeeeeeeeek..
     ..kdnndnnddnddk.
     ..kbbbbbbbbbbk..
     ..kkkkkkkkkkk...
     ...kkkkkkkkkkk..
     ..keeeeeeeeeek..
     .kddnddnndnndk..
     ..kbbbbbbbbbbk..
     ...kkkkkkkkkkk..
     ......kdck......
     ......kdck......
     ......kdck......
     ......kdck......
     ......kdck......
     ......kdck......
     ......kdck......
     ......kdck......
     ......kdck......
     ......kdck......
     ......kdck......
     ......kdck......
     ......kdck......
     ....kkkdckkk....
     ...kddddcccdk...
     ...kcccccccck...
     ....kkkkkkkk....
     ................`,
  ],
  occluder: { kind: 'rect', x: 6, y: 25, w: 4, h: 2 },
});

/**
 * Steinbrunnen (Deko): Ring aus Feldsteinen mit Wasser (Glanzflag), darüber ein Satteldach aus roten
 * Schindeln auf zwei Pfosten, Welle mit Seil und Holzeimer. 2×2.
 */
const brunnen = moebel({
  item: 'steinbrunnen_deko',
  size: [32, 39],
  anchor: [16, 37],
  hoehe: 'block',
  nass: 'xyzZ',
  frames: [
    `................................
     ...............kk...............
     .............kkmmkk.............
     ...........kkmMMMMmkk...........
     .........kkmMMmmmmMMmkk.........
     .......kkmMMmmllllmmMMmkk.......
     .....kkmMMmmllkkkkllmmMMmkk.....
     ...kkmMMmmllkk....kkllmmMMmkk...
     ..klllllllkk........kklllllllk..
     ..kkkkkkkk............kkkkkkkk..
     ...kdck..................kcdk...
     ...kdck..................kcdk...
     ...kkkkkkkkkkkkkkkkkkkkkkkkkk...
     ...kdccccccccccccccccccccccdk...
     ...kkkkkkkkkkkkkkkkkkkkkkkkkk...
     ...kdck.......kddk.......kcdk...
     ...kdck.....kkkkkkkk.....kcdk...
     ...kdck.....kddcddck.....kcdk...
     ...kdck.....kdkkkkdk.....kcdk...
     ...kdck......kdccdk......kcdk...
     ...kdck......kkkkkk......kcdk...
     ...kdck...kkkkkkkkkkkk...kcdk...
     ...kdckkkk554555555455kkkkcdk...
     ...kdkk5545kkkkkkkkkk5455kkdk...
     ...kk5544kkyyyyyyyyyykk4455kk...
     ...k5454kyyyyzzyyyyzzyyk4545k...
     ..k5445kyyyyyyyyyyzzyyyyk5445k..
     .k5454kyyyyyyyyyyyyyyyyyyk4545k.
     .k4545kxyyyyyyyyyyyyyyyyxk5454k.
     .k54545kkxxxxxxxxxxxxxxkk54545k.
     .k455455kkkkkkkkkkkkkkkk554554k.
     .k5545554555455555545554555455k.
     .k44k4443k44443kk34444k3444k44k.
     .k33k3333k33333kk33333k3333k33k.
     .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
     .k4443k44443k444444k34444k3444k.
     .k3333k33333k333333k33333k3333k.
     .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
     ................................`,
  ],
  occluder: { kind: 'ellipse', x: 16, y: 31, rx: 14, ry: 5 },
});

/** Schaukelpferd: Holzpferd mit Fasermähne im Profil auf gebogenen Kufen. 1×1. */
const schaukelpferd = moebel({
  item: 'schaukelpferd',
  size: [16, 20],
  anchor: [8, 17],
  hoehe: 'block',
  frames: [
    `................
     ..........kkk...
     .........kDDDk..
     ........kDkeddk.
     .......kDkeddkdk
     .......kDkddddkk
     ......kDDkcddk..
     ..kkkkkDkdddk...
     .kCkdddddddck...
     kCCkddddddddk...
     .kkkdddddddck...
     ...kbdccccbk....
     ...kbk..kbk.....
     ...kbk..kbk.....
     .kk.kbk..kbk.kk.
     kdekkbkkkkbkkedk
     .kddddddddddddk.
     ..kkkkkkkkkkkk..
     ................
     ................`,
  ],
  occluder: { kind: 'rect', x: 2, y: 14, w: 12, h: 3 },
  spiegelbar: true,
});

/** Waschzuber: runder Bottich aus Dauben mit zwei Griffen, voll Wasser (Glanzflag). 1×1. */
const waschzuber = moebel({
  item: 'waschzuber',
  size: [16, 16],
  anchor: [8, 14],
  hoehe: 'zylinder',
  nass: 'xyzZ',
  frames: [
    `................
     ................
     ................
     ....kkkkkkkk....
     ..kkeeeeeeeekk..
     .kekxxxxxxxxkek.
     kckyyyyyZZyyykck
     kckyyyyyyyyyykck
     .kekkyyyyyykkek.
     .kbdkkkkkkkkdbk.
     .kddcdddcdddcdk.
     .kddcdddcdddcdk.
     .kbbbbbbbbbbbbk.
     ..kaaaaaaaaaak..
     ...kkkkkkkkkk...
     ................`,
  ],
  occluder: { kind: 'ellipse', x: 8, y: 12, rx: 6, ry: 2 },
  spiegelbar: true,
});

export default [brunnen, schaukelpferd, waschzuber, blumentopf, vase, topfpflanze, pflanzkuebel, teppich, sonnenuhr, vogelhaus, holzstapel, wegweiser];
