/**
 * Grab (MASTERPROMPT §11.6, M3-26): entsteht am Todesort und hält das Inventar, bis es geleert ist.
 * Erdhügel mit Schollen und zwei Steinen am Fuß, dahinter ein gebundenes Holzkreuz; am Querholz weht ein
 * Tuchstreifen in der Kleidungsfarbe der Spielfigur (Rampe `wasser`, von der Charakter-Palettenzeile
 * mitgefärbt), damit man das eigene Grab erkennt. Clip `wehen`: drei Frames, 6 fps (hängt → weht → hängt
 * halb). 24×24, Fußpunkt unten Mitte des Hügels; Sockel `marker` für den Kartenmarker/Hinweis über dem
 * Kreuz.
 */
import { sprite } from '../../lib/sprite';

export default sprite({
  id: 'grab',
  group: 'platzierbar',
  size: [24, 24],
  anchor: [12, 21],
  hoehe: 'kugel',
  legende: {
    '.': null,
    k: 'nacht.1',
    '4': 'stein.3',
    '5': 'stein.4',
    b: 'holz.1',
    d: 'holz.3',
    D: 'sand.3',
    q: 'erde.1',
    r: 'erde.2',
    s: 'erde.3',
    t: 'erde.4',
    y: 'wasser.2',
    z: 'wasser.3',
  },
  frames: [
    `........................
     ...........kk...........
     ..........kdbk..........
     ..........kdbk..........
     ......kkkkkkkkkkkk......
     .....kdddddDbdddddk.....
     .....kbbbbbbDbbbbbk.....
     ......kkkkkkkkkkzz......
     ..........kdbk.kyzk.....
     ..........kdbk.kyyk.....
     .........kkdbkk.kyk.....
     ......kkkttttttkkk......
     ....kktstttttsttttkk....
     ...kttsstttttssttttsk...
     ..kssssttsstssssstsssk..
     ..kssssssssssssssssssk..
     .kssssrrsssssrssssrrsrk.
     ..ksrrrrrrrsrrrrrsrrrk..
     ..krrrrqrrrrrqqqrrrrrk..
     ...krrkkrrrrrqqrrkkqk...
     ....kk54kqqrqqqqk54k....
     .....k4qkqqqqqqkk4qk....
     ......kk.kkkkkk..kk.....
     ........................`,
    `........................
     ...........kk...........
     ..........kdbk..........
     ..........kdbk..........
     ......kkkkkkkkkkkk......
     .....kdddddDbdddddk.....
     .....kbbbbbbDbbbbbkkk...
     ......kkkkkkkkkkkzzzk...
     ..........kdbk...yyzk...
     ..........kdbk...kkyk...
     .........kkdbkk....k....
     ......kkkttttttkkk......
     ....kktstttttsttttkk....
     ...kttsstttttssttttsk...
     ..kssssttsstssssstsssk..
     ..kssssssssssssssssssk..
     .kssssrrsssssrssssrrsrk.
     ..ksrrrrrrrsrrrrrsrrrk..
     ..krrrrqrrrrrqqqrrrrrk..
     ...krrkkrrrrrqqrrkkqk...
     ....kk54kqqrqqqqk54k....
     .....k4qkqqqqqqkk4qk....
     ......kk.kkkkkk..kk.....
     ........................`,
    `........................
     ...........kk...........
     ..........kdbk..........
     ..........kdbk..........
     ......kkkkkkkkkkkk......
     .....kdddddDbdddddk.....
     .....kbbbbbbDbbbbbkk....
     ......kkkkkkkkkkzzzk....
     ..........kdbk.kyyzk....
     ..........kdbk..kyyk....
     .........kkdbkk..kk.....
     ......kkkttttttkkk......
     ....kktstttttsttttkk....
     ...kttsstttttssttttsk...
     ..kssssttsstssssstsssk..
     ..kssssssssssssssssssk..
     .kssssrrsssssrssssrrsrk.
     ..ksrrrrrrrsrrrrrsrrrk..
     ..krrrrqrrrrrqqqrrrrrk..
     ...krrkkrrrrrqqrrkkqk...
     ....kk54kqqrqqqqk54k....
     .....k4qkqqqqqqkk4qk....
     ......kk.kkkkkk..kk.....
     ........................`,
  ],
  clips: { wehen: { frames: [0, 1, 2, 1], fps: 6, loop: true } },
  sockets: { marker: [[12, 0]] },
  hitbox: [2, 1, 20, 22],
  occluder: { kind: 'none' },
});
