/**
 * Werkbank als platziertes Welt-Objekt (docs/SPIEL.md §6 `werkbank`, M3-16, Station T0): schwere
 * Arbeitsplatte aus drei Bohlen mit gewellten Fugen und Astloch, vier Beine (die hinteren im Schatten),
 * Querstreben; darauf ein Steinklotz als Amboss und ein Steinhammer, daneben Späne. 32×32, der Fußpunkt
 * liegt mittig unter den vorderen Beinen. Arbeitshöhe etwa Hüfthöhe der Spielfigur.
 */
import { sprite } from '../../lib/sprite';

export default sprite({
  id: 'werkbank',
  group: 'platzierbar',
  size: [32, 32],
  anchor: [16, 30],
  hoehe: 'block',
  legende: {
    '.': null,
    k: 'nacht.1',
    '2': 'stein.1',
    '3': 'stein.2',
    '4': 'stein.3',
    '5': 'stein.4',
    a: 'holz.0',
    b: 'holz.1',
    c: 'holz.2',
    d: 'holz.3',
    e: 'holz.4',
  },
  frames: [
    `................................
     ................................
     ................................
     ................................
     ................................
     ................................
     ................kkkk............
     .....kkkkk.....k5554k...........
     ....k55554k....k4443kkkkkkk.....
     ....k44443k....k2332ddddddk.....
     ...kk32223kkkkkkkkkkkkkkkkkkk...
     ..keekkkkkeeeeeeeeeeeeeeeceeek..
     ..kdddddccdddddddddddddededddk..
     ..kcccddddcccccdddddcccccddddk..
     ..kdddccccdddddcccccdddddcccck..
     ..kddddddddddccdddddcccddddddk..
     ..kddddddddddddddddddddddddddk..
     ..kcccccccccccccccccccccccccck..
     ..kbbbbbbbbbbbbbbbbbbbbbbbbbbk..
     ..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..
     ...kdcbkk.............kbkdcbk...
     ...kdcbkk.............kbkdcbk...
     ...kdcbkkkkkkkkkkkkkkkkbkdcbk...
     ...kdcbkbbbbbbbbbbbbbbbbkdcbk...
     ...kdcbkkkkkkkkkkkkkkkkkkdcbk...
     ...kdcbkcccccccccccccccckdcbk...
     ...kdcbkbbbbbbbbbbbbbbbbkdcbk...
     ...kdcbkkkkkkkkkkkkkkkkkkdcbk...
     ...kdcbk................kdcbk...
     ...kbbak................kbbak...
     ...kkkkk................kkkkk...
     ................................`,
  ],
  sockets: { arbeit: [[16, 12]] },
  hitbox: [2, 6, 28, 25],
  occluder: { kind: 'rect', x: 3, y: 20, w: 26, h: 10 },
});
