/**
 * Dünengras-Horste (M3-40, docs/ART.md §5 Salzküste): einzelne Büschel blaugrünen Dünengrases, die die
 * Präsentation in Gruppen über die Dünen streut (`src/render/world/groundDecor.ts`) – quer über die
 * Kachelgrenzen, dicht in den Horsten, mit Sand dazwischen. So zerfällt das Dünengrasfeld in Büschelgruppen
 * statt in ein gleichmäßiges 16-px-Raster.
 *
 * Gleiche Handschrift wie die Motive des Tilesets `tileset_duenengras`: windschiefe Fächer aus 1-px-Halmen,
 * am Fuß dunkles Grün (`gras.2`), in der Mitte Petrol (`wasser.3`), oben Türkis (`wasser.4`), Spitzen
 * Schaumtürkis (`wasser.5`), trockene Halme `sand.2` mit heller Spitze `sand.4`, Fußschatten `sand.2`.
 * Die Halme sind als Wind markiert: der Wind biegt sie leicht. Drei Größen als Frames (klein, mittel,
 * groß); flach wie der Boden, auf dem sie liegen.
 */
import { sprite } from '../../lib/sprite';

export default sprite({
  id: 'bodendeko_duenengras',
  group: 'terrain',
  size: [12, 10],
  anchor: [6, 8],
  hoehe: 'flach',
  legende: { '.': null, l: 'wasser.5', g: 'wasser.4', t: 'wasser.3', k: 'gras.2', d: 'sand.2', h: 'sand.4' },
  frames: [
    // klein
    `............
     ............
     ............
     ............
     ....l.l.....
     ....t.gh....
     .....tk.....
     ....dkd.....
     .....d......
     ............`,
    // mittel
    `............
     ............
     .....g......
     ...l.g.l....
     ....gtg.h...
     ....ttth....
     .....tkd....
     ....dkkd....
     .....dd.....
     ............`,
    // groß
    `............
     ..l.g.g.l...
     .g.g.t.g.g..
     ..gt.t.tg.h.
     ...tttkt.h..
     ...tktktd...
     ....kkkd....
     ...dkkkd....
     ....ddd.....
     ............`,
  ],
  clips: { klein: { frames: [0], fps: 8, loop: true }, mittel: { frames: [1], fps: 8, loop: true }, gross: { frames: [2], fps: 8, loop: true } },
  schatten: 'none',
  occluder: { kind: 'none' },
  material: { wind: 'lgth' },
  einzelpixel: 'Halmspitzen und Fußschatten sind einzelne Pixel',
});
