/**
 * Brand (MASTERPROMPT §16.2 „Brennbar“, §16.8, §6.2 „Feuer“; M4-28 in der Spielansicht): Flammen auf einer brennenden
 * Kachel der Feuersimulation – über einer Wand, einem Möbel, einem Dach oder einem Baum. Die Präsentation
 * (`src/render/game/fire.ts`) wählt die Größe aus der Stärke des Brandes (jung, voll, heruntergebrannt) und setzt über
 * hohe Dinge mehrere Flammen übereinander; volle Feuereffekte (Funken, Rauch, Hitzeflimmern) folgen mit M5-21.
 *
 * `brand`: Zelle 16×16, Anker `[8, 15]` (Fußpunkt der Flamme). Vier Größen als Clips zu je sechs Frames, 12 fps (§4.5:
 * Effekte schneller als Figuren), in der Bewegung der Herdfeuer-Flamme – Ruhe → Ducken → Strecken mit abreißender
 * Spitze → Neigen rechts → zwei Zungen → Neigen links:
 * - `glimmen`: Glutbett mit kurzen Zungen (ein fast abgebrannter Brand),
 * - `klein`: eine Zunge (der Brand fängt an),
 * - `mittel`: Flamme mit Nebenzunge,
 * - `gross`: voller Brand mit drei Zungen.
 * Handgezeichnet sind je Größe die Ruheform und die Form mit zwei Zungen; Ducken, Strecken und Neigen entstehen daraus
 * durch Weglassen, Anheben und zeilenweises Versetzen. Alles leuchtet (emissiv): außen Tiefrot `feuer.1`, innen über
 * Orange zum weißgelben Kern `feuer.5` am Fuß – der Kern ist heller als der Rand (docs/ART.md §2.6, §9 Punkt 9).
 * Spiegelbar: benachbarte Flammen stehen verschieden.
 */
import { sprite } from '../../lib/sprite';

const GROESSE = 16;
/** Frames je Clip und Takt. */
const TAKT = 12;

/** Ruheform je Größe (Zeilen 0–15, Fuß in Zeile 15). */
const GLIMMEN = `................
                 ................
                 ................
                 ................
                 ................
                 ................
                 ................
                 ................
                 ................
                 ................
                 ................
                 ................
                 ........r.......
                 ...r...rfr..r...
                 ..rfr.rfFr.rfr..
                 .rfFfrfyFfrfFfr.`;

const GLIMMEN_ZUNGEN = `................
                        ................
                        ................
                        ................
                        ................
                        ................
                        ................
                        ................
                        ................
                        ................
                        ................
                        ................
                        ....r.......r...
                        ...rfr..r..rfr..
                        ..rfFr.rfr.rfr..
                        .rfFyfrfFfrfFfr.`;

const KLEIN = `................
               ................
               ................
               ................
               ................
               ................
               ................
               ................
               ................
               .......r........
               .......rr.......
               ......rffr......
               ......rFFfr.....
               .....rFyyFr.....
               .....rFyWyr.....
               ......rffr......`;

const KLEIN_ZUNGEN = `................
                      ................
                      ................
                      ................
                      ................
                      ................
                      ................
                      ................
                      ................
                      ........r.......
                      ......r.rr......
                      ......rrffr.....
                      ......rFFfr.....
                      .....rFyyFr.....
                      .....rFyWyr.....
                      ......rffr......`;

const MITTEL = `................
                ................
                ................
                ........r.......
                .......rr.......
                .......rfr......
                ....r.rffr......
                ....rrfFFfr.r...
                ....rfFyFfrrr...
                ...rfFyyFffFr...
                ...rfFyWyFFFr...
                ...rfyWWyyFfr...
                ...rFyWWWyFr....
                ....rFyWWyFr....
                ....rfFyyFfr....
                .....rrffrr.....`;

const MITTEL_ZUNGEN = `................
                       ................
                       ................
                       ..........r.....
                       .......r..rr....
                       .......rr.rfr...
                       ....r.rfr.rfr...
                       ....rrfFfrfFr...
                       ....rfFyFffFr...
                       ...rfFyyFFyFr...
                       ...rfFyWyyyFr...
                       ...rfyWWWyFfr...
                       ...rFyWWWyFr....
                       ....rFyWWyFr....
                       ....rfFyyFfr....
                       .....rrffrr.....`;

const GROSS = `................
               .......r........
               .......rr.......
               ......rfr...r...
               ......rffr..rr..
               ..r..rfFfr.rfr..
               ..rr.rfFFfrrfr..
               .rfr.rFyFfrfFr..
               .rfrrfFyyFffFr..
               .rffrFyyyFfFFfr.
               .rfFfFyWyyFFyFr.
               .rfFFyWWWyFyyFr.
               ..rFyyWWWWyyFr..
               ..rfFyWWWWyFfr..
               ...rfFyyyyFfr...
               ....rrfFFfrr....`;

const GROSS_ZUNGEN = `................
                      ..........r.....
                      ......r...rr....
                      ......rr..rfr...
                      .....rfr..rfr...
                      .r...rffr.rfFr..
                      .rr..rfFfrrfFr..
                      .rfr.rFFfffyFr..
                      .rfrrfFyFfFyFr..
                      .rffrFyyFFyyFfr.
                      .rfFfFyWyyyWyFr.
                      .rfFFyWWWyWWyFr.
                      ..rFyyWWWWWyFr..
                      ..rfFyWWWWyFfr..
                      ...rfFyyyyFfr...
                      ....rrfFFfrr....`;

const LEER = '.'.repeat(GROESSE);

function zeilenVon(t: string): string[] {
  return t
    .split('\n')
    .map((z) => z.trim())
    .filter((z) => z.length > 0);
}

/** Oberste Zeile mit Flamme. */
function oben(z: readonly string[]): number {
  const i = z.findIndex((zeile) => zeile !== LEER);
  return i < 0 ? z.length - 1 : i;
}

/** Ducken: die obersten `n` Zeilen der Flamme fallen weg, der Fuß bleibt. */
function ducke(t: string, n: number): string {
  const z = zeilenVon(t);
  const o = oben(z);
  return z.map((zeile, i) => (i < o + n ? LEER : zeile)).join('\n');
}

/** Strecken: die obersten `n` Zeilen (die Spitze der Hauptzunge) heben sich um eine Zeile und reißen ab. */
function reisse(t: string, n: number): string {
  const z = zeilenVon(t);
  const o = oben(z);
  return z.map((zeile, i) => (i >= o - 1 && i < o + n - 1 ? (z[i + 1] as string) : i === o + n - 1 ? LEER : zeile)).join('\n');
}

/** Anteil der Flammenhöhe (von oben), der sich neigt; darunter steht der Körper auf seinem Glutbett. */
const NEIGE_ANTEIL = 0.6;

/** Neigen: die Zeilen der oberen Flamme versetzt, an der Spitze um `weite` px (positiv = rechts), der Körper steht. */
function neige(t: string, weite: number): string {
  const z = zeilenVon(t);
  const o = oben(z);
  const grenze = o + Math.max(1, Math.round((z.length - 1 - o) * NEIGE_ANTEIL));
  return z
    .map((zeile, i) => {
      if (i < o || i >= grenze) return zeile;
      const v = Math.round(((grenze - i) / (grenze - o)) ** 1.5 * weite);
      const neu = v >= 0 ? '.'.repeat(v) + zeile : zeile.slice(-v);
      return neu.slice(0, GROESSE).padEnd(GROESSE, '.');
    })
    .join('\n');
}

/** Die sechs Frames einer Größe: Ruhe, Ducken, Strecken, rechts, zwei Zungen, links. */
function folge(ruhe: string, zungen: string, tief: number, spitze: number, weite: number): string[] {
  return [ruhe, ducke(ruhe, tief), reisse(ruhe, spitze), neige(ruhe, weite), zungen, neige(zungen, -weite)];
}

/** Größen in Clip-Reihenfolge (Index = Stärke 0–3 der Präsentation). */
const GROESSEN = [
  { clip: 'glimmen', frames: folge(GLIMMEN, GLIMMEN_ZUNGEN, 1, 1, 1) },
  { clip: 'klein', frames: folge(KLEIN, KLEIN_ZUNGEN, 1, 2, 1) },
  { clip: 'mittel', frames: folge(MITTEL, MITTEL_ZUNGEN, 2, 2, 2) },
  { clip: 'gross', frames: folge(GROSS, GROSS_ZUNGEN, 2, 2, 2) },
] as const;

export default sprite({
  id: 'brand',
  group: 'effekte',
  size: [GROESSE, GROESSE],
  anchor: [8, 15],
  hoehe: 'flach',
  legende: { '.': null, r: 'feuer.1*', f: 'feuer.2*', F: 'feuer.3*', y: 'feuer.4*', W: 'feuer.5*' },
  frames: GROESSEN.flatMap((g) => g.frames),
  clips: Object.fromEntries(GROESSEN.map((g, k) => [g.clip, { frames: g.frames.map((_, i) => k * g.frames.length + i), fps: TAKT, loop: true }])),
  spiegelbar: true,
  schatten: 'none',
  occluder: { kind: 'none' },
  einzelpixel: 'Flammenspitzen und abreißende Zungen sind einzelne leuchtende Pixel',
});
