/**
 * Bodenschatten liegender Items (docs/SPIEL.md §2 „Welt-Drop nutzt dasselbe Icon“, M3-10, M3-15): der
 * Drop schwebt als Icon (`icon_<itemId>`, Schatten `none`) leicht wippend über diesem flachen Oval, das
 * ihn auf jedem Grund verankert. Frame 0 = Drop am Boden, Frame 1 = Drop oben im Wippen (Schatten
 * kleiner); Clip `wippen` im Takt des Auf und Ab. Die Präsentation blendet ihn über die Dither-Ausblendung
 * des Sprite-Batchers halb durchsichtig (Kern `nacht.2`, Rand `nacht.3` – weich statt Loch).
 */
import { sprite } from '../../lib/sprite';

export default sprite({
  id: 'drop_schatten',
  group: 'effekte',
  size: [16, 8],
  anchor: [8, 4],
  hoehe: 'flach',
  legende: { '.': null, k: 'nacht.2', n: 'nacht.3' },
  frames: [
    `................
     ................
     ....nnnnnnnn....
     ...nkkkkkkkkn...
     ...nkkkkkkkkn...
     ....nnnnnnnn....
     ................
     ................`,
    `................
     ................
     ................
     .....nnnnnn.....
     ....nkkkkkkn....
     .....nnnnnn.....
     ................
     ................`,
  ],
  clips: { wippen: { frames: [0, 0, 1, 1], fps: 4, loop: true } },
  schatten: 'none',
  occluder: { kind: 'none' },
});
