/**
 * Sammel-Partikel (MASTERPROMPT §14 „Feedback: Partikel je Material“, M3-11/M3-12/M3-15): je Material
 * ein kleines Sprite mit vier Frames, die ein taumelndes Bruchstück zeigen (Clip `flug`, 16 fps –
 * Effekte laufen schneller als Figuren, §4.5). Die Präsentation streut sie beim Treffer mit eigener
 * Geschwindigkeit, Schwerkraft und Lebensdauer; die Frames drehen das Teil, der Clip läuft in Schleife.
 * - `partikel_splitter` (Holz: Axt an Bäumen, Stümpfen, Treibholz): heller Span mit dunkler Kante.
 * - `partikel_steinsplitter` (Stein, Erz: Spitzhacke): kantiger Splitter, oben hell.
 * - `partikel_funken` („Zu hart“, Stahl auf Stein, Glut): emissiver Funke, der verglüht (nicht in
 *   Schleife – Clip `verglimmen`).
 * - `partikel_blatt` (Laub beim Fällen und Sammeln): Blatt in `gras`, das sich im Fall dreht; die
 *   Präsentation färbt es mit der Jahreszeit-Zeile der Krone.
 * - `partikel_erde` (Graben, Pflanzen ernten): Scholle mit Krümel.
 * - `staubwolke` (Aufprall des Baumes, Graben, Landung): Staubwolke, die aufquillt und zerfasert.
 */
import { sprite } from '../../lib/sprite';

const GRUPPE = 'effekte';
/** Takt der taumelnden Bruchstücke (Bilder je Sekunde). */
const FLUG_FPS = 16;
const EINZEL = 'Bruchstücke und Funken sind einzelne Pixel im Flug';

export default [
  sprite({
    id: 'partikel_splitter',
    group: GRUPPE,
    size: [8, 8],
    anchor: [4, 4],
    hoehe: 'flach',
    legende: { '.': null, e: 'holz.4', d: 'holz.3', b: 'holz.1' },
    frames: [
      `........
       ........
       ..edd...
       ...ddbb.
       ........
       ........
       ........
       ........`,
      `........
       .....e..
       ....dd..
       ...db...
       ..bb....
       ........
       ........
       ........`,
      `........
       ...e....
       ...d....
       ...db...
       ....b...
       ....b...
       ........
       ........`,
      `........
       ..e.....
       ..dd....
       ...db...
       ....bb..
       ........
       ........
       ........`,
    ],
    clips: { flug: { frames: [0, 1, 2, 3], fps: FLUG_FPS, loop: true } },
    schatten: 'none',
    occluder: { kind: 'none' },
    einzelpixel: EINZEL,
  }),
  sprite({
    id: 'partikel_steinsplitter',
    group: GRUPPE,
    size: [8, 8],
    anchor: [4, 4],
    hoehe: 'flach',
    legende: { '.': null, k: 'nacht.1', '6': 'stein.5', '5': 'stein.4', '3': 'stein.2' },
    frames: [
      `........
       ........
       ...6k...
       ..653k..
       ...3k...
       ........
       ........
       ........`,
      `........
       ........
       ..56....
       ..653k..
       ...kk...
       ........
       ........
       ........`,
      `........
       ........
       ...k6...
       ..k356..
       ...k3...
       ........
       ........
       ........`,
      `........
       ........
       ...kk...
       ..k356..
       ....65..
       ........
       ........
       ........`,
    ],
    clips: { flug: { frames: [0, 1, 2, 3], fps: FLUG_FPS, loop: true } },
    schatten: 'none',
    occluder: { kind: 'none' },
    einzelpixel: EINZEL,
  }),
  sprite({
    id: 'partikel_funken',
    group: GRUPPE,
    size: [8, 8],
    anchor: [4, 4],
    hoehe: 'flach',
    legende: { '.': null, W: 'feuer.5*', y: 'feuer.4*', F: 'feuer.3*', r: 'feuer.1*' },
    frames: [
      `........
       ........
       ....W...
       ...yW...
       ..Fy....
       ........
       ........
       ........`,
      `........
       ........
       ....y...
       ...Fy...
       ...r....
       ........
       ........
       ........`,
      `........
       ........
       ........
       ...F....
       ...r....
       ........
       ........
       ........`,
      `........
       ........
       ........
       ...r....
       ........
       ........
       ........
       ........`,
    ],
    clips: { verglimmen: { frames: [0, 1, 2, 3], fps: 20, loop: false } },
    schatten: 'none',
    occluder: { kind: 'none' },
    einzelpixel: EINZEL,
  }),
  sprite({
    id: 'partikel_blatt',
    group: GRUPPE,
    size: [8, 8],
    anchor: [4, 4],
    hoehe: 'flach',
    legende: { '.': null, g: 'gras.1', h: 'gras.2', i: 'gras.3', j: 'gras.4' },
    frames: [
      `........
       ........
       ...jj...
       ..jiih..
       ...hh...
       ........
       ........
       ........`,
      `........
       ........
       .....j..
       ...ji...
       ..hh....
       ........
       ........
       ........`,
      `........
       ........
       ...hh...
       ..hggh..
       ...hh...
       ........
       ........
       ........`,
      `........
       ........
       ..j.....
       ...ih...
       ....hh..
       ........
       ........
       ........`,
    ],
    clips: { flug: { frames: [0, 1, 2, 3], fps: 10, loop: true } },
    schatten: 'none',
    occluder: { kind: 'none' },
    material: { wind: true },
    einzelpixel: EINZEL,
  }),
  sprite({
    id: 'partikel_erde',
    group: GRUPPE,
    size: [8, 8],
    anchor: [4, 4],
    hoehe: 'flach',
    legende: { '.': null, t: 'erde.4', s: 'erde.3', r: 'erde.2', q: 'erde.1' },
    frames: [
      `........
       ........
       ...ts...
       ..tsrq..
       ...rq...
       .....q..
       ........
       ........`,
      `........
       ........
       ..st....
       ..srr...
       ...qq.r.
       ........
       ........
       ........`,
      `........
       ........
       ...rs...
       ..qrst..
       ...qr...
       ..q.....
       ........
       ........`,
      `........
       ........
       ...ts...
       ..rsr...
       ..qq....
       ....r...
       ........
       ........`,
    ],
    clips: { flug: { frames: [0, 1, 2, 3], fps: FLUG_FPS, loop: true } },
    schatten: 'none',
    occluder: { kind: 'none' },
    einzelpixel: EINZEL,
  }),
  sprite({
    id: 'staubwolke',
    group: GRUPPE,
    size: [16, 16],
    anchor: [8, 13],
    hoehe: 'kugel',
    legende: { '.': null, E: 'sand.4', D: 'sand.3', C: 'sand.2', B: 'sand.1' },
    frames: [
      `................
       ................
       ................
       ................
       ................
       ................
       ................
       ................
       ................
       ......EE........
       .....EDDE.EE....
       ....EDDCDEDDE...
       ...EDCCBCCDCD...
       ....DCBBBBCC....
       ................
       ................`,
      `................
       ................
       ................
       ................
       ................
       ................
       ......EEE.......
       ....EEDDDE.EE...
       ...EDDDCDDEDDE..
       ..EDDCCCDDDCDDE.
       ..EDCCBCCCCCCD..
       ...DCBBBBBCCCD..
       ....CBBBBBBCC...
       .....CCBBCC.....
       ................
       ................`,
      `................
       ................
       ................
       ................
       .....EE...EE....
       ...EEDDE.EDDE...
       ..EDDDDDEDDDDE..
       ..EDDCCDDDCCDE..
       .EDDCCCCDCCCDDE.
       .EDCCBBCCCBCCDE.
       ..DCCBBBCBBCCD..
       ..DCBB..BBCCD...
       ...CC....BCC....
       ................
       ................
       ................`,
      `................
       ................
       ................
       ....EE......EE..
       ...EDDE....EDDE.
       ...DDC......DD..
       ................
       ..EE..........E.
       .EDD........EDE.
       .DC..........D..
       ................
       ................
       ................
       ................
       ................
       ................`,
      `................
       ...EE.......E...
       ...DE......EDE..
       ................
       ................
       .E............E.
       .D............D.
       ................
       ................
       ................
       ................
       ................
       ................
       ................
       ................
       ................`,
    ],
    clips: { aufwirbeln: { frames: [0, 1, 2, 3, 4], fps: 12, loop: false } },
    schatten: 'none',
    occluder: { kind: 'none' },
    einzelpixel: 'Zerfasernde Staubränder in den letzten Frames',
  }),
];
