/**
 * Stehende Fackel (M1-33): ein angespitzter Holzpfahl, im Boden verkeilt zwischen zwei Steinen, oben ein
 * Pechkopf mit eisernem Ring und die Flamme der Wandfackel (`fackel_wand` bleibt Wänden vorbehalten).
 * Die Flamme sitzt knapp über Kopfhöhe der Spielfigur, der Lichtsockel in ihrem Kern (19 px über dem
 * Fuß). Vier Flammen-Frames mit Antizipation und Nachschwingen wie an der Wand: aufrecht, nach rechts
 * mit abgespaltener Zunge, geduckt, nach links mit abreißender Spitze; der Clip schwingt aufrecht →
 * links → geduckt → rechts, 10 fps (§4.5: Effekte schneller als Figuren). Flamme emissiv, außen
 * Tiefrot `feuer.1`, innen über Orange zum weißgelben Kern `feuer.5`; Glut auf dem Pechkopf. Der Pfahl
 * ist hell/dunkel geteilt wie der Griff der Wandfackel, ein Astknoten bricht die Länge. 12 Farben inkl.
 * Kontur.
 */
import { sprite } from '../../lib/sprite';

/** Pechkopf, Eisenring (`m`/`M`, Metall), Pfahl und Keilsteine (`s`/`S`) – Zeilen 15–31, in allen Frames gleich. */
const PFAHL = `
     .....kpFFpk.....
     .....khoohk.....
     .....kphhpk.....
     .....kMMmmk.....
     ......kOok......
     ......kOok......
     ......kOok......
     ......kOok......
     ......kOpk......
     ......kOok......
     ......kOok......
     ......kOok......
     ......kOok......
     ....k.kOok.kk...
     ...kSkkOokkSSk..
     ..kSsskOokSsssk.
     ..kkkkkkkkkkkkk.`;

/** Flammen-Frames (Zeilen 0–14): dieselben vier Formen wie `fackel_wand`, oben mit Luft für die Zungen. */
const FLAMMEN = [
  `................
   ................
   ................
   ................
   ................
   ................
   ........r.......
   .......rr.......
   .......rfr......
   ......rffr......
   ......rfFfr.....
   .....rfFyFf.....
   .....fFyyFf.....
   .....FyWWyF.....
   ......yWWy......`,
  `................
   ................
   ................
   ................
   ................
   ................
   .........r......
   .........rr.....
   ......r..rfr....
   ......rf.rfr....
   ......rffffr....
   .....rfFFyFf....
   .....fFyyyFf....
   .....FyWWyF.....
   ......yWWy......`,
  `................
   ................
   ................
   ................
   ................
   ................
   ................
   ................
   ........r.......
   .......rfr......
   ......rfffr.....
   .....rfFFFfr....
   .....fFyyyFf....
   .....FyWWyF.....
   ......yWWy......`,
  `................
   ................
   ................
   ................
   ................
   .....r..........
   ......r.........
   ......rr........
   .....rffr.......
   .....rfFfr......
   .....fFFyf......
   .....fFyyFf.....
   .....FyWWyF.....
   ......yWWy......
   ................`,
];

export default sprite({
  id: 'fackel_stand',
  group: 'licht',
  size: [16, 32],
  anchor: [8, 31],
  hoehe: 'zylinder',
  legende: {
    '.': null,
    k: 'nacht.1',
    p: 'holz.0',
    h: 'holz.1',
    o: 'holz.2',
    O: 'holz.3',
    m: 'stein.1',
    M: 'stein.3',
    s: 'stein.1',
    S: 'stein.3',
    r: 'feuer.1*',
    f: 'feuer.2*',
    F: 'feuer.3*',
    y: 'feuer.4*',
    W: 'feuer.5*',
  },
  material: { metall: 'mM' },
  frames: FLAMMEN.map((flamme) => `${flamme}\n${PFAHL}`),
  clips: { idle: { frames: [0, 3, 2, 1], fps: 10, loop: true } },
  sockets: { licht: [[8, 12]] },
  occluder: { kind: 'none' },
  schatten: 'silhouette',
});
