/**
 * Wandfackel (MASTERPROMPT §5, Beispiel des Quellformats; M1-22): Pechkopf auf Holzgriff in eisernem
 * Wandring. Vier Flammen-Frames mit Antizipation und Nachschwingen: aufrecht, nach rechts mit
 * abgespaltener Zunge, geduckt (holt Luft), nach links mit abreißender Spitze; der Clip schwingt
 * aufrecht → links → geduckt → rechts. Flamme emissiv, außen Tiefrot `feuer.1`, innen über Orange zum
 * weißgelben Kern `feuer.5`; Glut auf dem Pechkopf. Effekte laufen schneller als Figuren (§4.5):
 * 10 fps. 12 Farben inkl. Kontur.
 */
import { sprite } from '../../lib/sprite';

export default sprite({
  id: 'fackel_wand',
  group: 'licht',
  size: [16, 16],
  anchor: [8, 15],
  hoehe: 'zylinder',
  legende: {
    '.': null,
    k: 'nacht.1',
    p: 'holz.0',
    h: 'holz.1',
    o: 'holz.2',
    O: 'holz.3',
    m: 'stein.1',
    M: 'stein.3',
    r: 'feuer.1*',
    f: 'feuer.2*',
    F: 'feuer.3*',
    y: 'feuer.4*',
    W: 'feuer.5*',
  },
  material: { metall: 'mM' },
  frames: [
    `........r.......
     .......rr.......
     .......rfr......
     ......rffr......
     ......rfFfr.....
     .....rfFyFf.....
     .....fFyyFf.....
     .....FyWWyF.....
     ......yWWy......
     .....kpFFpk.....
     .....khoohk.....
     .....kphhpk.....
     .....kMMmmk.....
     ......kOok......
     ......kOok......
     .......kk.......`,
    `.........r......
     .........rr.....
     ......r..rfr....
     ......rf.rfr....
     ......rffffr....
     .....rfFFyFf....
     .....fFyyyFf....
     .....FyWWyF.....
     ......yWWy......
     .....kpFFpk.....
     .....khoohk.....
     .....kphhpk.....
     .....kMMmmk.....
     ......kOok......
     ......kOok......
     .......kk.......`,
    `................
     ................
     ........r.......
     .......rfr......
     ......rfffr.....
     .....rfFFFfr....
     .....fFyyyFf....
     .....FyWWyF.....
     ......yWWy......
     .....kpFFpk.....
     .....khoohk.....
     .....kphhpk.....
     .....kMMmmk.....
     ......kOok......
     ......kOok......
     .......kk.......`,
    `.....r..........
     ......r.........
     ......rr........
     .....rffr.......
     .....rfFfr......
     .....fFFyf......
     .....fFyyFf.....
     .....FyWWyF.....
     ......yWWy......
     .....kpFFpk.....
     .....khoohk.....
     .....kphhpk.....
     .....kMMmmk.....
     ......kOok......
     ......kOok......
     .......kk.......`,
  ],
  clips: { idle: { frames: [0, 3, 2, 1], fps: 10, loop: true } },
  sockets: { licht: [[8, 6]] },
  occluder: { kind: 'none' },
  schatten: 'silhouette',
});
