/**
 * Kampf-Effekte (M6-05, M6-15; MASTERPROMPT §6.2 „Kampf: 2-Frame-Trefferblitz, Hitstop, Knockback, Screenshake,
 * Waffen-Smears, Einschlagpartikel je Material, Auflösen besiegter Gegner“, §4.6 „Telegraphs: Ausholpose + kurzer
 * Glint + Sound; Boss-Flächenangriffe mit Bodenmarkierung“; docs/ART.md §8 „Telegraphs“). Die Präsentation
 * (`src/render/game/combat.ts`, `telegraphs.ts`) setzt sie:
 * - `kampf_glint`: der kurze Glint beim Ausholen einer Kreatur und wenn der schwere Schlag geladen ist – ein Stern in
 *   `eis.4*` (ART §8), der aufblitzt und erlischt (Clip `blitz`, 20 fps: das volle Bild steht zwei Frames).
 * - `kampf_punkt`: einzelne Pixel, aus denen die Präsentation Linien und Kreise pixelgenau setzt (Mittelpunkt-Kreis,
 *   keine gedrehten Striche): Bodenmarkierung der Flächenangriffe in der Warnfarbe (`feuer.2*`, ART §8
 *   `UI_COLORS.warnung`), ihr wachsender Innenring (`feuer.3*`) und die Füllung (`feuer.1*`, gedithert), die
 *   Schmierspur eines Schlags (`eis.4*` → `eis.3*` → `eis.2*`, verglimmend) und die violette Spur der Schattenbrut
 *   (`verderb.4*`). Frame-Reihenfolge: `PUNKT` in `src/render/game/combatFeedback.ts`.
 * - `partikel_fell`: ein Büschel Fell, das sich im Flug dreht (Treffer auf Fell).
 * - `partikel_schatten`: ein Fetzen Tintenrauch mit violettem Saum, der zerfasert (Treffer auf Schattenbrut, ihr Zerfall
 *   in Funken beim Tod, §6.2 „Schattenbrut … Zerfall in Funken beim Tod“).
 */
import { sprite } from '../../lib/sprite';

const GRUPPE = 'kampf';
/** Takt der taumelnden Bruchstücke (wie `partikel.ts`). */
const FLUG_FPS = 16;
const OHNE = { schatten: 'none', occluder: { kind: 'none' } } as const;

export default [
  sprite({
    id: 'kampf_glint',
    group: GRUPPE,
    size: [9, 9],
    anchor: [4, 4],
    hoehe: 'flach',
    legende: { '.': null, '#': 'eis.4*', '0': 'eis.3*' },
    frames: [
      `.........
       .........
       .........
       ....#....
       ...###...
       ....#....
       .........
       .........
       .........`,
      `....0....
       ....0....
       ....#....
       ...0#0...
       00#####00
       ...0#0...
       ....#....
       ....0....
       ....0....`,
      `.........
       .........
       ....0....
       ...0#0...
       ..0###0..
       ...0#0...
       ....0....
       .........
       .........`,
    ],
    clips: { blitz: { frames: [0, 1, 1, 2], fps: 20, loop: false } },
    ...OHNE,
    einzelpixel: 'Die Strahlenspitzen des Sterns sind einzelne Pixel',
  }),
  sprite({
    id: 'kampf_punkt',
    group: GRUPPE,
    size: [1, 1],
    anchor: [0, 0],
    hoehe: 'flach',
    legende: { '.': null, a: 'feuer.2*', b: 'feuer.3*', c: 'feuer.1*', d: 'eis.4*', e: 'eis.3*', f: 'eis.2*', g: 'verderb.4*' },
    frames: ['a', 'b', 'c', 'd', 'e', 'f', 'g'],
    clips: { punkt: { frames: [0], fps: 1, loop: true } },
    ...OHNE,
    einzelpixel: 'Ein einzelnes Pixel, aus dem die Präsentation Kreise und Bögen pixelgenau setzt',
  }),
  sprite({
    id: 'partikel_fell',
    group: GRUPPE,
    size: [8, 8],
    anchor: [4, 4],
    hoehe: 'flach',
    legende: { '.': null, E: 'sand.3', D: 'sand.2', r: 'erde.2' },
    frames: [
      `........
       ........
       ...E....
       ..EDD...
       ...Dr...
       ....r...
       ........
       ........`,
      `........
       ........
       ........
       ..EED...
       ...DDr..
       .....r..
       ........
       ........`,
      `........
       ........
       ....E...
       ...DE...
       ...rD...
       ...r....
       ........
       ........`,
      `........
       ........
       ........
       ...DEE..
       ..rDD...
       ..r.....
       ........
       ........`,
    ],
    clips: { flug: { frames: [0, 1, 2, 3], fps: FLUG_FPS, loop: true } },
    ...OHNE,
    einzelpixel: 'Haarspitzen im Flug sind einzelne Pixel',
  }),
  sprite({
    id: 'partikel_schatten',
    group: GRUPPE,
    size: [8, 8],
    anchor: [4, 4],
    hoehe: 'flach',
    legende: { '.': null, n: 'nacht.1', v: 'verderb.1', W: 'verderb.3*', w: 'verderb.2*' },
    frames: [
      `........
       ........
       ...ww...
       ..wvvW..
       ..vnnv..
       ...vn...
       ........
       ........`,
      `........
       ...w....
       ..wvW...
       ..vnvw..
       ...nnv..
       ....v...
       ........
       ........`,
      `........
       ..w.....
       ..vW.w..
       ...nv...
       ..vn.v..
       ........
       ........
       ........`,
      `........
       .w......
       ..v..w..
       ...W....
       ..v..v..
       ........
       ........
       ........`,
    ],
    clips: { zerfasern: { frames: [0, 1, 2, 3], fps: 10, loop: false } },
    ...OHNE,
    einzelpixel: 'Zerfasernder Rauch und Funken sind einzelne Pixel',
  }),
];
