/**
 * Item-Icons der Bauteile (M4-12/M4-13, docs/SPIEL.md §8): je Bauteil `icon_<itemId>` (16×16, Motiv
 * ≤ 14×14 mit 1 px Luft, Kontur `nacht.1`; Konvention in `_icon.ts`). Jedes Icon zeigt das Teil als
 * handliches Bauelement in seinem Material, so dass Wand, Boden, Dach, Tür, Fenster, Säule, Zaun und
 * Zugang auch im kleinen Inventarplatz unterscheidbar bleiben:
 * - Wände als Wandstück (Palisade: drei gespitzte Stämme mit Seil; Holz: Blockwand mit Stammköpfen;
 *   Fachwerk: Balkenfeld mit Strebe; Stein: Mauerstück in Lagen),
 * - Böden als Fliese in Aufsicht mit Vorderkante, Dächer als Dachstück mit Traufe,
 * - Türen, Tor, Falltür, Fenster von vorn, Säulen stehend, Zäune als Feld, Leiter schräg, Treppe von der
 *   Seite, Steg als Bohlenstück auf Pfählen.
 */
import { icon } from './_icon';

export default [
  icon(
    'wand_palisade',
    `................
     ...k...k...k....
     ..kek.kek.kek...
     .kedckedckedck..
     .kbdckbdckbdck..
     .kbdckbcckbdck..
     .kbcckbdckbdck..
     .kbdckbdckbcck..
     .kDDDDDDDDDDDk..
     .kCBCBCBCBCBCk..
     .kbdckbdckbdck..
     .kbdckbcckbdck..
     .kbcckbdckbdck..
     .kqqkkqqkkqqk...
     ..kk..kk..kk....
     ................`,
  ),
  icon(
    'wand_holz',
    `................
     ................
     .kkkkkkkkkkkkkk.
     .kbdbkdeeddeedk.
     .kdedkcccccccck.
     .kbdbkbbbbbbbbk.
     .kkkkkkkkkkkkkk.
     .kddeeddddkbdbk.
     .kcccccccckdedk.
     .kbbbbbbbbkbdbk.
     .kkkkkkkkkkkkkk.
     .kbdbkdeedddeek.
     .kdedkcccccccck.
     .kbdbkbbbbbbbbk.
     .kkkkkkkkkkkkkk.
     ................`,
  ),
  icon(
    'wand_fachwerk',
    `................
     .kkkkkkkkkkkkkk.
     .kbbbbbbbbbbbbk.
     .kbEEEEbbDDDbbk.
     .kbEDDDbbDDbbDk.
     .kbDDDDbbDbbDDk.
     .kbbbbbbbbbDDDk.
     .kbDDDDbbbbDEDk.
     .kbDDDDbbbDDDDk.
     .kbDDEDbbDDDDDk.
     .kbbbbbbbbbbbbk.
     .k444434443444k.
     .k333333333333k.
     .kkkkkkkkkkkkkk.
     ................
     ................`,
  ),
  icon(
    'wand_stein',
    `................
     ................
     ..kkkkkkkkkkkk..
     .k555525555525k.
     .k444424444424k.
     .k222222222222k.
     .k552555555255k.
     .k442444444244k.
     .k332333433233k.
     .k222222222222k.
     .k555552555555k.
     .k444442444434k.
     .k333332333333k.
     .kkkkkkkkkkkkkk.
     ................
     ................`,
  ),
  icon(
    'boden_holz',
    `................
     ................
     ................
     .kkkkkkkkkkkkkk.
     .kddddbddeddddk.
     .kbbbbbbbbbbbbk.
     .kcccccccbcccck.
     .kbbbbbbbbbbbbk.
     .kdddeddddbdddk.
     .kbbbbbbbbbbbbk.
     .kccbccccccccck.
     .kbbbbbbbbbbbbk.
     .kaaaaaaaaaaaak.
     .kkkkkkkkkkkkkk.
     ................
     ................`,
  ),
  icon(
    'boden_stein',
    `................
     ................
     ................
     .kkkkkkkkkkkkkk.
     .k554425554455k.
     .k444424444444k.
     .k222222222222k.
     .k455552445544k.
     .k444442444444k.
     .k222222222222k.
     .k552455554255k.
     .k442444444244k.
     .k111111111111k.
     .kkkkkkkkkkkkkk.
     ................
     ................`,
  ),
  icon(
    'boden_lehm',
    `................
     ................
     ................
     .kkkkkkkkkkkkkk.
     .kCCCDDCCCCCCCk.
     .kCCCCCCCBBCCCk.
     .kCDDCCCCCCBCCk.
     .kCCCCBBCCCCCCk.
     .kCCCCCCBBCCDDk.
     .kCCBCCCCCCCCCk.
     .kCCCBBCCCCBBCk.
     .kCCCCCCCCCCCCk.
     .kAAAAAAAAAAAAk.
     .kkkkkkkkkkkkkk.
     ................
     ................`,
  ),
  icon(
    'dach_stroh',
    `................
     .......kk.......
     ......kqqk......
     .....kDCCDk.....
     ....kDDCDDCk....
     ...kEDDCDDCDk...
     ..kBBCBBBCBBBk..
     .kDCDDCDDCDDCDk.
     .kEDEEDEEDEEDEk.
     .kBBCBBBCBBBBBk.
     .kDDCDDDCDDDCDk.
     .kDEDDEDDEDDEDk.
     .kEEEDEEEEEDEEk.
     .kBABBABBBABBAk.
     .kkkkkkkkkkkkkk.
     ................`,
  ),
  icon(
    'dach_schindel',
    `................
     .......kk.......
     ......kcck......
     .....krqqrk.....
     ....ksstsssk....
     ...kqqqqqqqqk...
     ..krrqrrrqrrrk..
     .kssqsstsqsstsk.
     .kqqqqqqqqqqqqk.
     .krqrrrqrrrqrrk.
     .kssqstssqsstsk.
     .kqqqqqqqqqqqqk.
     .krrrqrrrrqrrrk.
     .kcccccccccccck.
     .kkkkkkkkkkkkkk.
     ................`,
  ),
  icon(
    'dach_glas',
    `................
     .......kk.......
     ......kbbk......
     .....kb90bk.....
     ....kb8900bk....
     ...kbbbbbbbbk...
     ..kb89b8890bbk..
     .kb890b890b89bk.
     .kb90bb90bb90bk.
     .kbbbbbbbbbbbbk.
     .kb890b8890b89k.
     .kb900b8900b90k.
     .kb000b9000b00k.
     .kcccccccccccck.
     .kkkkkkkkkkkkkk.
     ................`,
    { material: { nass: '890' } },
  ),
  icon(
    'tuer_holz',
    `................
     ...kkkkkkkkkk...
     ...kbccccccbk...
     ...kcdcbdcbck...
     ...kcdcbdcbck...
     ...knNeeeeeek...
     ...knneeeeeek...
     ...kcdcbdcbck...
     ...kcdcbdnnck...
     ...kcdcbdNnck...
     ...kcdcbdcbck...
     ...knNeeeeeek...
     ...knneeeeeek...
     ...kcdcbdcbck...
     ...kkkkkkkkkk...
     ................`,
    { material: { metall: 'nN' } },
  ),
  icon(
    'tuer_verstaerkt',
    `................
     ...kkkkkkkkkk...
     ...kbccccccbk...
     ...kcdcbdcbck...
     ...kMMMMMMMMk...
     ...klEllEllEk...
     ...kcdcbdcbck...
     ...kcdcbdMMck...
     ...kcdcbdMlck...
     ...kcdcbdcbck...
     ...kMMMMMMMMk...
     ...klEllEllEk...
     ...kcdcbdcbck...
     ...kcdcbdcbck...
     ...kkkkkkkkkk...
     ................`,
    { material: { metall: 'lMEm' } },
  ),
  icon(
    'tor_holz',
    `................
     .kkk........kkk.
     .kek........kek.
     .kdkkkkkkkkkkdk.
     .kdkdcbkkdcbkdk.
     .kdkeeekkeeekdk.
     .kdkdcbkkdcbkdk.
     .kdkdcbkkdnbkdk.
     .kdkcbdkkcnbkdk.
     .kdkdcbkkdcbkdk.
     .kdkeeekkeeekdk.
     .kdkdcbkkdcbkdk.
     .kdkkkkkkkkkkdk.
     .kbk........kbk.
     .kkk........kkk.
     ................`,
  ),
  icon(
    'falltuer_holz',
    `................
     ................
     ..kkkkkkkkkkkk..
     .kbbbbbbbbbbbbk.
     .kbddddddddddbk.
     .kbccccccccccbk.
     .kbbbbbbbbbbbbk.
     .kbddddnnddddbk.
     .kbcccnkkNcccbk.
     .kbddddNNddddbk.
     .kbbbbbbbbbbbbk.
     .kbccccccccccbk.
     .kbddddddddddbk.
     .kkkkkkkkkkkkkk.
     ................
     ................`,
    { material: { metall: 'nN' } },
  ),
  icon(
    'fenster_offen',
    `................
     ...kkkkkkkkkk...
     ...kddddddddk...
     .kkkbbbbbbbbkkk.
     .kdkbKKKKKKbkdk.
     .kckbKKKKKKbkck.
     .kdkbKKKKKKbkdk.
     .kckbKKKKKKbkck.
     .kdkbnKKKKnbkdk.
     .kckbnnnnnnbkck.
     .kkkeeeeeeeekkk.
     ...kbbbbbbbbk...
     ...kkkkkkkkkk...
     ................
     ................
     ................`,
  ),
  icon(
    'fenster_glas',
    `................
     ..kkkkkkkkkkkk..
     ..kddddddddddk..
     ..kbbbbbbbbbbk..
     ..kb8890b890bk..
     ..kb890bb90bbk..
     ..kb90bbb0b8bk..
     ..kbbbbbbbbbbk..
     ..kb889b8890bk..
     ..kb890b890bbk..
     ..kb90bb90b8bk..
     ..keeeeeeeeeek..
     ..kbbbbbbbbbbk..
     ...kkkkkkkkkk...
     ................
     ................`,
    { material: { nass: '890' } },
  ),
  icon(
    'fenster_buntglas',
    `................
     ..kkkkkkkkkkkk..
     ..kddddddddddk..
     ..kbbbbbbbbbbk..
     ..kbuuunnzzzbk..
     ..kbuunDDnzzbk..
     ..kbunDDDDnzbk..
     ..kbnDDDDDDnbk..
     ..kbinDDDDnubk..
     ..kbiinDDnuubk..
     ..kbiiinnuuubk..
     ..keeeeeeeeeek..
     ..kbbbbbbbbbbk..
     ...kkkkkkkkkk...
     ................
     ................`,
    { material: { nass: 'uziD' } },
  ),
  icon(
    'saeule_holz',
    `................
     ..kkkkkkkkkkk...
     .kcddeeddeddck..
     .kbbbbbbbbbbbk..
     ..kkkcddckkkk...
     ....kcdeck......
     ....kcddck......
     ....kbddck......
     ....kcddck......
     ....kcdeck......
     ....kcddbk......
     ...kkcddckk.....
     ..k55444431k....
     ..k33333221k....
     ..kkkkkkkkkk....
     ................`,
  ),
  icon(
    'saeule_stein',
    `................
     ...kkkkkkkkk....
     ..k556666555k...
     ..k344444433k...
     ...kk22222kk....
     ....k34553k.....
     ....k34553k.....
     ....k23442k.....
     ....k34553k.....
     ....k34553k.....
     ....k23442k.....
     ...k3455543k....
     ..k345555543k...
     ..k223333322k...
     ..kkkkkkkkkkk...
     ................`,
  ),
  icon(
    'zaun_holz',
    `................
     .kkkk......kkkk.
     .keek......keek.
     .kdck......kdck.
     .kdckkkkkkkkdck.
     .kdcddddddddddk.
     .kdcbbbbbbbbdck.
     .kdckkkkkkkkdck.
     .kdck......kdck.
     .kdckkkkkkkkdck.
     .kdcddddddddddk.
     .kdcbbbbbbbbdck.
     .kdckkkkkkkkdck.
     .kbbk......kbbk.
     .kkkk......kkkk.
     ................`,
  ),
  icon(
    'zaun_stein',
    `................
     ................
     ................
     ....kkkkk.......
     ..kk55665kkkk...
     .k5545ii455i5k..
     .k44444ii44445k.
     .k22112221121k..
     .k541455514555k.
     .k431444413444k.
     .k321333312333k.
     .k111222111221k.
     .k551455514455k.
     .k331333312333k.
     .kkkkkkkkkkkkkk.
     ................`,
  ),
  icon(
    'leiter_holz',
    `................
     .........kk.kk..
     ........kdkkdk..
     ........kdkdk...
     .......kkeeekk..
     .......kdkkdk...
     ......kdkkdk....
     ......keeeekk...
     .....kdkkdk.....
     .....kdkdk......
     ....kkeeekk.....
     ....kdkkdk......
     ...kdkkdk.......
     ...kbk.kbk......
     ...kk...kk......
     ................`,
  ),
  icon(
    'treppe_holz',
    `................
     ................
     ..........kkkkk.
     ..........keeek.
     .......kkkkdddk.
     .......keeekbbk.
     ....kkkkdddkcck.
     ....keeekbbkbbk.
     .kkkkdddkcckcck.
     .keeekbbkbbkbbk.
     .kdddkcckcckcck.
     .kbbkbbkbbkbbbk.
     .kcckcckcckccck.
     .kbbbbbbbbbbbbk.
     .kkkkkkkkkkkkkk.
     ................`,
  ),
  icon(
    'steg_holz',
    `................
     ................
     ................
     .kkkkkkkkkkkkkk.
     .kddeddddeddddk.
     .kbbbbbbbbbbbbk.
     .kcccccccbcccck.
     .kbbbbbbbbbbbbk.
     .kdddeddddddedk.
     .kbbbbbbbbbbbbk.
     .kcccccccccccck.
     .kbdbbbbbbbbdbk.
     .kkckkkkkkkkckk.
     ..kbk......kbk..
     ..kyk......kyk..
     ................`,
    { material: { nass: 'y' } },
  ),
];
