/**
 * Item-Icons der Bronzewerkzeuge T1 (M4-10, src/content/items/verarbeitung_bronzewerkzeuge.ts): Bronzeaxt,
 * Bronzeschaufel, Bronzehacke, Bronzesichel, Bronzehammer, Bronzemesser.
 *
 * Dieselbe Bildsprache wie die Steinwerkzeuge (`werkzeuge.ts`): Stiel schräg von links unten nach rechts
 * oben, Kopf oben, jede Werkzeugart mit ihrer eigenen Silhouette. Der Unterschied liegt im Material:
 * statt geschlagenen Steins mit Schnurbindung ein gegossener, geschmiedeter Bronzekopf – glatte Kontur,
 * helle Schneide mit Glanz (`T`/`P`), goldbrauner Körper (`X`), Schatten zur Tülle hin (`W`/`Q`) – und eine
 * Tülle (Bronzering) statt der Schnur, wo der Stiel im Kopf steckt. Sichel und Messer haben einen mit Garn
 * umwickelten Griff (Leinengarn in `stein.5`/`stein.3` wie `icon_garn`, kühl gegen die warme Bronze, damit
 * Klinge und Griff getrennt lesen). Die Bronzerampe ist `METALL_RAMPEN.bronze` (Metallflag).
 */
import { icon } from './_icon';
import { METALL_RAMPEN, METALL_ZEICHEN } from './verarbeitung';

const BRONZE = { legende: METALL_RAMPEN.bronze, material: { metall: METALL_ZEICHEN } } as const;

export default [
  icon(
    'bronzeaxt',
    // Geschwungenes Blatt mit bogiger Schneide, zur Tülle hin schmal; die Tülle umfasst den Stiel.
    `................
     ...kk...........
     ..kTPk......kk..
     .kTPXWk....kdbk.
     .kTPXXWkkkkdbk..
     .kTPXXXWQXTXk...
     .kTXXXWQWXWk....
     .kTXXWWkdbk.....
     ..kTWWkdbk......
     ..kTQkdbk.......
     ...kkdbk........
     ...kDBk.........
     ..kBDk..........
     .kdbk...........
     ..kk............
     ................`,
    BRONZE,
  ),
  icon(
    'bronzeschaufel',
    // Spitzes Blatt mit Mittelgrat in Verlängerung des Stiels, Tülle am Blattfuß.
    `................
     ..........kkk...
     .........kTPTk..
     ........kTXPXTk.
     .......kTXXPXWk.
     .......kXXPXWQk.
     .......kXPXWQk..
     ......kQTWQkk...
     ......kdbk......
     .....kdbk.......
     ....kdbk........
     ...kDBk.........
     ..kBDk..........
     .kdbk...........
     ..kk............
     ................`,
    BRONZE,
  ),
  icon(
    'bronzehacke',
    // Arm quer vom Stielende, an seinem Ende das nach unten gebogene Blatt mit heller Schneide.
    `................
     ...kkkkkkkkkk...
     ..kTPTTTTTTXQkk.
     ..kXXXXXWWWQTXk.
     ..kXXWkkkkkQWQk.
     ..kTXWk..kdbk...
     ..kTXWk.kdbk....
     ..kPTQkkdbk.....
     ...kkkkdbk......
     .....kdbk.......
     ....kdbk........
     ...kDBk.........
     ..kBDk..........
     .kdbk...........
     ..kk............
     ................`,
    BRONZE,
  ),
  icon(
    'bronzesichel',
    // Schlanker Sichelbogen, innen die helle Schneide, Bronzezwinge, Garngriff.
    `................
     ......kkkkk.....
     .....kXTTTXkk...
     ....kXTPkkkTXk..
     ...kXTPk...kTWk.
     ...kXTk.....kWk.
     ...kXTk......k..
     ...kWXTk........
     ....kWXk........
     .....kWWk.......
     ....k64k........
     ...k46k.........
     ..k64k..........
     .kbbk...........
     ..kk............
     ................`,
    BRONZE,
  ),
  icon(
    'bronzehammer',
    // Gegossener Hammerkopf quer auf dem Stiel, zwei Bahnen, Tülle unten.
    `................
     ......kkkkkkkk..
     .....kPPTTTTTTk.
     .....kTXXXXXXTk.
     .....kXXWXXWXXk.
     .....kWWQWWQWWk.
     ......kkkQTQkk..
     .......kkdbk....
     .......kdbk.....
     ......kdbk......
     .....kdbk.......
     ...kkDBk........
     ..kBDk..........
     .kdbk...........
     ..kk............
     ................`,
    BRONZE,
  ),
  icon(
    'bronzemesser',
    // Blattförmige Klinge mit hellem Grat, Parierzwinge, Garngriff, Knauf.
    `................
     .............k..
     ............kPk.
     ...........kTPk.
     ..........kXTPk.
     .........kWXTPk.
     ........kWXTPk..
     .......kWXTPk...
     ......kWXTk.....
     .....kQQWk......
     ....k64k........
     ...k46k.........
     ..k64k..........
     .kQXk...........
     ..kk............
     ................`,
    BRONZE,
  ),
];
