/**
 * Item-Icons der Heilmittel (M4-35, src/content/items/heilmittel.ts): die Schiene – zwei gerade Zweige
 * nebeneinander, an zwei Stellen mit Faserseil (Drall hell/dunkel wie `icon_faserseil`) zusammengebunden,
 * die Schnittenden hell. Die Zweige liegen schräg wie die Stiele der Werkzeug-Icons; die Kontur trennt
 * beide Zweige, damit das Paar nicht als ein breiter Stab liest. Konvention und Legende: `_icon.ts`.
 */
import { icon } from './_icon';

export default [
  icon(
    'schiene',
    `................
     ..........kk....
     .........kedkkk.
     ........kdbkedk.
     .......kDBDBDk..
     ......kBDBDBk...
     .....kdbkdbk....
     ....kdbkdbk.....
     ...kDBDBDk......
     ..kBDBDBk.......
     .kdbkdbk........
     .kedkdbk........
     ..kkkedk........
     ....kkk.........
     ................
     ................`,
  ),
];
