/**
 * Interaktions-Hinweise in der Welt (M3-10 „[E] Aufheben: Feuerstein ×3“, M3-11 „Halten mit
 * Fortschrittsring“): Glyphen für die weltnahe UI bzw. den Sprite-Pass, gezeichnet in der Akzentfarbe
 * der Interaktions-Outline (`laub.4`, nächste Palettenfarbe zu `UI_COLORS.akzent`) und leuchtend, damit
 * sie auch außerhalb von Lichtinseln lesbar bleiben.
 * - `hinweis_taste`: leere Tastenkappe 16×16; die Taste selbst (E, F, Q …, frei belegbar) schreibt die
 *   Pixelschrift in die Kappe (Innenfläche x 3–12, y 3–10).
 * - `hinweis_maus_links` / `hinweis_maus_rechts`: Maus mit hervorgehobener Taste (Werkzeug benutzen,
 *   Platzieren).
 * - `hinweis_ring`: Fortschrittsring für gehaltene Aktionen, neun Frames (0/8 … 8/8, im Uhrzeigersinn ab
 *   12 Uhr); die Präsentation wählt den Frame aus dem Fortschritt (kein Clip mit Takt, `stufen`).
 * - `hinweis_pfeil`: kleiner Pfeil über dem Ziel, wippt (Clip `wippen`, 6 fps).
 */
import { sprite } from '../../lib/sprite';

const GRUPPE = 'hinweise';

export default [
  sprite({
    id: 'hinweis_taste',
    group: GRUPPE,
    size: [16, 16],
    anchor: [8, 15],
    hoehe: 'flach',
    legende: { '.': null, k: 'nacht.1', E: 'sand.4', D: 'sand.3', C: 'sand.2', B: 'sand.1' },
    frames: [
      `................
       ..kkkkkkkkkkkk..
       .kDEEEEEEEEEEDk.
       .kEEEEEEEEEEEEk.
       .kEEEEEEEEEEEEk.
       .kEEEEEEEEEEEEk.
       .kEEEEEEEEEEEEk.
       .kEEEEEEEEEEEEk.
       .kEEEEEEEEEEEEk.
       .kEEEEEEEEEEEEk.
       .kDEEEEEEEEEEDk.
       .kCDDDDDDDDDDCk.
       .kBCCCCCCCCCCBk.
       ..kkkkkkkkkkkk..
       ................
       ................`,
    ],
    schatten: 'none',
    occluder: { kind: 'none' },
  }),
  ...(['links', 'rechts'] as const).map((seite) =>
    sprite({
      id: `hinweis_maus_${seite}`,
      group: GRUPPE,
      size: [16, 16],
      anchor: [8, 15],
      hoehe: 'flach',
      legende: { '.': null, k: 'nacht.1', E: 'sand.4', D: 'sand.3', C: 'sand.2', o: 'laub.4*', M: 'laub.3*' },
      frames: [
        seite === 'links'
          ? `................
             .....kkkkkk.....
             ....koookEEk....
             ...kooMkkEEEk...
             ...koMMkkEEEk...
             ...kkkkkkkkkk...
             ...kEEEEEEEEk...
             ...kEEEEEEEEk...
             ...kDEEEEEEDk...
             ...kDEEEEEEDk...
             ...kCDDDDDDCk...
             ....kCDDDDCk....
             .....kkkkkk.....
             ................
             ................
             ................`
          : `................
             .....kkkkkk.....
             ....kEEkoook....
             ...kEEEkkMook...
             ...kEEEkkMMok...
             ...kkkkkkkkkk...
             ...kEEEEEEEEk...
             ...kEEEEEEEEk...
             ...kDEEEEEEDk...
             ...kDEEEEEEDk...
             ...kCDDDDDDCk...
             ....kCDDDDCk....
             .....kkkkkk.....
             ................
             ................
             ................`,
      ],
      schatten: 'none',
      occluder: { kind: 'none' },
    }),
  ),
  sprite({
    id: 'hinweis_ring',
    group: GRUPPE,
    size: [16, 16],
    anchor: [8, 8],
    hoehe: 'flach',
    legende: { '.': null, k: 'nacht.1', n: 'nacht.2', o: 'laub.4*', M: 'laub.3*' },
    frames: [
      `................
       .....kkkkkk.....
       ....knnnnnnk....
       ...knnnnnnnnk...
       ..knnnnnnnnnnk..
       .knnnnkkkknnnnk.
       .knnnk....knnnk.
       .knnnk....knnnk.
       .knnnk....knnnk.
       .knnnk....knnnk.
       .knnnnkkkknnnnk.
       ..knnnnnnnnnnk..
       ...knnnnnnnnk...
       ....knnnnnnk....
       .....kkkkkk.....
       ................`,
      `................
       .....kkkkkk.....
       ....knnnoook....
       ...knnnnMoook...
       ..knnnnnMMMnnk..
       .knnnnkkkknnnnk.
       .knnnk....knnnk.
       .knnnk....knnnk.
       .knnnk....knnnk.
       .knnnk....knnnk.
       .knnnnkkkknnnnk.
       ..knnnnnnnnnnk..
       ...knnnnnnnnk...
       ....knnnnnnk....
       .....kkkkkk.....
       ................`,
      `................
       .....kkkkkk.....
       ....knnnoook....
       ...knnnnMoook...
       ..knnnnnMMMook..
       .knnnnkkkkMMook.
       .knnnk....kMook.
       .knnnk....kMMok.
       .knnnk....knnnk.
       .knnnk....knnnk.
       .knnnnkkkknnnnk.
       ..knnnnnnnnnnk..
       ...knnnnnnnnk...
       ....knnnnnnk....
       .....kkkkkk.....
       ................`,
      `................
       .....kkkkkk.....
       ....knnnoook....
       ...knnnnMoook...
       ..knnnnnMMMook..
       .knnnnkkkkMMook.
       .knnnk....kMook.
       .knnnk....kMMok.
       .knnnk....kMMok.
       .knnnk....kMook.
       .knnnnkkkknMook.
       ..knnnnnnnnnok..
       ...knnnnnnnnk...
       ....knnnnnnk....
       .....kkkkkk.....
       ................`,
      `................
       .....kkkkkk.....
       ....knnnoook....
       ...knnnnMoook...
       ..knnnnnMMMook..
       .knnnnkkkkMMook.
       .knnnk....kMook.
       .knnnk....kMMok.
       .knnnk....kMMok.
       .knnnk....kMook.
       .knnnnkkkkMMook.
       ..knnnnnMMMook..
       ...knnnnMoook...
       ....knnnoook....
       .....kkkkkk.....
       ................`,
      `................
       .....kkkkkk.....
       ....knnnoook....
       ...knnnnMoook...
       ..knnnnnMMMook..
       .knnnnkkkkMMook.
       .knnnk....kMook.
       .knnnk....kMMok.
       .knnnk....kMMok.
       .knnnk....kMook.
       .knnnnkkkkMMook.
       ..knnMMMMMMook..
       ...koooMMoook...
       ....kooooook....
       .....kkkkkk.....
       ................`,
      `................
       .....kkkkkk.....
       ....knnnoook....
       ...knnnnMoook...
       ..knnnnnMMMook..
       .knnnnkkkkMMook.
       .knnnk....kMook.
       .knnnk....kMMok.
       .koMMk....kMMok.
       .kooMk....kMook.
       .kooMMkkkkMMook.
       ..kooMMMMMMook..
       ...koooMMoook...
       ....kooooook....
       .....kkkkkk.....
       ................`,
      `................
       .....kkkkkk.....
       ....knnnoook....
       ...knnnnMoook...
       ..konnnnMMMook..
       .kooMnkkkkMMook.
       .kooMk....kMook.
       .koMMk....kMMok.
       .koMMk....kMMok.
       .kooMk....kMook.
       .kooMMkkkkMMook.
       ..kooMMMMMMook..
       ...koooMMoook...
       ....kooooook....
       .....kkkkkk.....
       ................`,
      `................
       .....kkkkkk.....
       ....kooooook....
       ...koooMMoook...
       ..kooMMMMMMook..
       .kooMMkkkkMMook.
       .kooMk....kMook.
       .koMMk....kMMok.
       .koMMk....kMMok.
       .kooMk....kMook.
       .kooMMkkkkMMook.
       ..kooMMMMMMook..
       ...koooMMoook...
       ....kooooook....
       .....kkkkkk.....
       ................`,
    ],
    clips: { stufen: { frames: [0, 1, 2, 3, 4, 5, 6, 7, 8], fps: 8, loop: false } },
    schatten: 'none',
    occluder: { kind: 'none' },
  }),
  sprite({
    id: 'hinweis_pfeil',
    group: GRUPPE,
    size: [10, 12],
    anchor: [5, 10],
    hoehe: 'flach',
    legende: { '.': null, k: 'nacht.1', o: 'laub.4*', M: 'laub.3*' },
    frames: [
      `..........
       ..kkkkkk..
       ..kooook..
       ..kMooMk..
       .kkMooMkk.
       .koooooMk.
       ..kooMMk..
       ...kMMk...
       ....kk....
       ..........
       ..........
       ..........`,
      `..........
       ..........
       ..kkkkkk..
       ..kooook..
       ..kMooMk..
       .kkMooMkk.
       .koooooMk.
       ..kooMMk..
       ...kMMk...
       ....kk....
       ..........
       ..........`,
      `..........
       ..........
       ..........
       ..kkkkkk..
       ..kooook..
       ..kMooMk..
       .kkMooMkk.
       .koooooMk.
       ..kooMMk..
       ...kMMk...
       ....kk....
       ..........`,
    ],
    clips: { wippen: { frames: [0, 1, 2, 1], fps: 6, loop: true } },
    schatten: 'none',
    occluder: { kind: 'none' },
  }),
];
