/**
 * Sprites der Instrumente, des Keschers und seines Fangs (M7-31, src/content/items/instrumente.ts; Strang A):
 *
 * - Item-Icons (Konvention und Legende `_icon.ts`): `icon_floete` – ein schräger Holzstab mit drei dunklen Grifflöchern,
 *   das Mundstück mit Harz dunkel abgesetzt; `icon_laute` – bauchiger Holzkörper mit Schallloch, Hals schräg nach rechts
 *   oben, abgeknickter Wirbelkasten; `icon_netz` – Zweigring mit hellem Fasergeflecht an langem Stiel; `icon_grille` –
 *   eine Feldgrille von oben, dunkelbraun, mit Fühlern und geknickten Sprungbeinen; `icon_gluehwuermchen` – ein
 *   Glühwürmchen von oben, blasse Flügel, der Hinterleib glimmt (emissiv grün-gelb); `icon_gluehwuermchenglas` – ein
 *   Glas mit Zweigdeckel, drinnen im Dunkeln vier glimmende Punkte.
 * - Hand-Layer `ausruestung_netz` (wie die Werkzeuge, assets-src/sprites/ausruestung/werkzeuge.ts): der Kescher aufrecht
 *   gehalten, Ring mit Geflecht oben, beim Schwung mit Smear-Bogen in der Farbe der Fasern.
 * - Möbellicht `obj_gluehwuermchenglas` (Kontaktbogen `moebel_t0_t1`, Konventionen `assets-src/sprites/moebel/_moebel.ts`):
 *   das Glas am Boden, Clip `idle` – die Glühwürmchen wandern im Glas (vier Frames, 4 fps, langsamer als eine Flamme),
 *   `aus` – das Glas dunkel und leer. Sockel `licht` in der Glasmitte, `GLAS_LICHT_HOEHE_PX` = 6 über dem Fußpunkt.
 */
import { werkzeugSprite } from '../../lib/figureWerkzeug';
import { sprite } from '../../lib/sprite';
import { MOEBEL_GRUPPE } from '../moebel/_moebel';
import { icon } from './_icon';

/** Leuchtende Zeichen der Glühwürmchen (emissiv): Grün-Gelb des Hinterleibs, warmer Kern. */
const GLUEHEN = { '!': 'gras.5*', '?': 'sand.4*' } as const;

const ICONS = [
  icon(
    'floete',
    `................
     .............kk.
     ............kedk
     ...........kedck
     ..........kedck.
     .........keKck..
     ........kedck...
     .......keKck....
     ......kedck.....
     .....keKck......
     ....kedck.......
     ...kedck........
     ..kbbck.........
     ..kbbk..........
     ...kk...........
     ................`,
    { hoehe: 'zylinder', einzelpixel: 'Grifflöcher der Flöte als einzelne dunkle Pixel auf dem Holzstab' },
  ),
  icon(
    'laute',
    `................
     ............kkk.
     ...........kbbk.
     ..........kbkk..
     .........kdk....
     ........kdk.....
     ...kkkkkdk......
     ..kdddeddkk.....
     .kdeddddddk.....
     .kddnnnddck.....
     .kdnKKKndck.....
     .kcdnnnddck.....
     .kccddddcbk.....
     ..kccccccbk.....
     ...kkkkkkk......
     ................`,
    { einzelpixel: 'Glanzpunkt auf dem gewölbten Holzbauch der Laute' },
  ),
  icon(
    'netz',
    `................
     ..kkkkk.........
     .kcCkCck........
     kcCkCkCck.......
     kCkCkCkCk.......
     kcCkCkCck.......
     kCkCkCkCk.......
     .kcCkCck........
     ..kccck.........
     ....kkdk........
     .......kdk......
     ........kdk.....
     .........kdk....
     ..........kdk...
     ...........kck..
     ............kk..`,
    { hoehe: 'flach', einzelpixel: 'Maschen des Netzes: einzelne helle Faserknoten im Geflecht' },
  ),
  icon(
    'grille',
    `................
     ...k........k...
     ....k......k....
     .....k.kk.k.....
     ......kppk......
     .....kqrrqk.....
     ..k.kqrsrqk.k...
     ...kkqqrqqkk....
     ....kpqrqpk.....
     ..kkpqqrqqpkk...
     .kqkpqqrqqpkqk..
     .kqkkpqrqpkkqk..
     ..kq.kpqpk.qk...
     ..kq..kpk..qk...
     ..k....k....k...
     ................`,
    { hoehe: 'flach', einzelpixel: 'Fühler und Beinglieder der Grille als einzelne Konturpixel' },
  ),
  icon(
    'gluehwuermchen',
    `................
     ................
     ......k..k......
     .......kk.......
     ......kppk......
     .....kqppqk.....
     ....k9qqqq9k....
     ...k99qrrq99k...
     ...k9kkqqkk9k...
     ....k.k!!k.k....
     ......k!?!k.....
     ......k!!!k.....
     .......k!k......
     ........k.......
     ................
     ................`,
    { hoehe: 'flach', legende: GLUEHEN, einzelpixel: 'Fühlerspitzen und der warme Leuchtkern im Hinterleib' },
  ),
  icon(
    'gluehwuermchenglas',
    `................
     ................
     .....kkkkkk.....
     ....kdcdcdck....
     ....kkkkkkkk....
     .....k9889k.....
     ....k8n!nn8k....
     ...k8nnnn?n8k...
     ...k9n?nnnn9k...
     ...k9nnn!nn9k...
     ...k8!nnnn?8k...
     ...k9nn?nnn9k...
     ...k89nnnn98k...
     ....k888888k....
     .....kkkkkk.....
     ................`,
    { hoehe: 'zylinder', legende: GLUEHEN, einzelpixel: 'die glimmenden Glühwürmchen im dunklen Glas', material: { nass: '89' } },
  ),
];

/** Der Kescher in der Hand: Ring mit Geflecht oben am langen Stiel (Griffpixel `+`). */
const NETZ_HAND = sprite({
  ...werkzeugSprite({
    id: 'ausruestung_netz',
    legende: { '.': null, k: 'nacht.1', c: 'holz.2', d: 'holz.3', C: 'sand.3' },
    griffZeichen: 'd',
    schmier: 'C',
    halten: 'oben',
    spiegelbar: true,
    raster: `.kkkkk.
             kcCkCck
             kCkCkCk
             kcCkCck
             kCkCkCk
             .kcCck.
             ..kdk..
             ..kdk..
             ..kdk..
             ..kdk..
             ..kdk..
             ..kdk..
             ..k+k..
             ..kdk..
             ...k...`,
    wirkpunkt: [0, -9],
  }),
  einzelpixel: 'Maschen des Netzes: einzelne helle Faserknoten im Geflecht',
});

/** Glas am Boden: die Punkte wandern von Frame zu Frame; `aus` ohne Licht. */
const GLAS_RAHMEN = (innen: readonly string[]): string =>
  [
    '................',
    '................',
    '.....kkkkkk.....',
    '....kdcdcdck....',
    '....kkkkkkkk....',
    '.....k:;;:k.....',
    ...innen,
    '....k::::::k....',
    '.....kkkkkk.....',
    '................',
  ].join('\n');

const GLAS_INNEN: readonly (readonly string[])[] = [
  ['....k:n!nn:k....', '...k:nnnn?n:k...', '...k;n?nnnn;k...', '...k;nnn!nn;k...', '...k:!nnnn?:k...', '...k:nn?nnn:k...', '...k::nnnn::k...'],
  ['....k:nn!n:k....', '...k:n?nnnn:k...', '...k;nnnn!n;k...', '...k;n!nnnn;k...', '...k:nnn?nn:k...', '...k:?nnn!n:k...', '...k::nnnn::k...'],
  ['....k:n!nn:k....', '...k:nnnnn?:k...', '...k;n!nnnn;k...', '...k;nnn?nn;k...', '...k:!nnnnn:k...', '...k:nnn!?n:k...', '...k::nnnn::k...'],
  ['....k:nnn!:k....', '...k:n!nnnn:k...', '...k;nnn?nn;k...', '...k;!nnnn!;k...', '...k:nn?nnn:k...', '...k:nnnn?n:k...', '...k::nnnn::k...'],
  ['....k:nnnn:k....', '...k:nnnnnn:k...', '...k;nngnnn;k...', '...k;nnnnnn;k...', '...k:nnnngn:k...', '...k:nnnnnn:k...', '...k::nnnn::k...'],
];

const GLAS = sprite({
  id: 'obj_gluehwuermchenglas',
  group: MOEBEL_GRUPPE,
  size: [16, 16],
  anchor: [8, 14],
  hoehe: 'zylinder',
  spiegelbar: true,
  legende: { '.': null, k: 'nacht.1', n: 'nacht.2', c: 'holz.2', d: 'holz.3', ':': 'eis.1', ';': 'eis.3', g: 'gras.2', ...GLUEHEN },
  material: { nass: ':;' },
  frames: GLAS_INNEN.map(GLAS_RAHMEN),
  clips: { idle: { frames: [0, 1, 2, 3], fps: 4, loop: true }, aus: { frames: [4], fps: 1, loop: true } },
  // Lichtpunkt in der Glasmitte, `GLAS_LICHT_HOEHE_PX` (src/content/items/instrumente.ts) über dem Fußpunkt.
  sockets: { licht: [[8, 8], [8, 8], [8, 8], [8, 8], [8, 8]] },
  occluder: { kind: 'ellipse', x: 8, y: 14, rx: 3, ry: 1 },
  einzelpixel: 'die glimmenden Glühwürmchen als einzelne Lichtpunkte im dunklen Glas',
});

export default [...ICONS, NETZ_HAND, GLAS];
