/**
 * Item-Icons der Grünhain-Jagdgüter (M6-22; src/content/items/jagd_gruenhain.ts): Wespenstachel – ein gestreifter
 * Wespenhinterleib (gelb `feuer.4`/`feuer.3`, Streifen und Kontur `nacht.1`) mit silbernem Stachel (`eis.3`).
 */
import { icon } from './_icon';

export default [
  icon(
    'wespenstachel',
    `................
     ................
     ...........kkk..
     ..........kvvvk.
     .........kvvvvk.
     ........kkkkkvk.
     .......kUUvvkk..
     ......kUUvvvk...
     .....kkkkkkk....
     ....kUUvvvk.....
     ....kUUvvk......
     ...kkkkkk.......
     ..k0k...........
     .k0k............
     .kk.............
     ................`,
    { einzelpixel: 'Der Stachel ist eine 1 px breite Spitze' },
  ),
];
