/**
 * Item-Icons der Küsten-Jagdgüter (M6-23, M6-24; src/content/items/jagd_kueste.ts): rohes Krebsfleisch – eine
 * aufgebrochene Schere mit rot-orangem Panzer (Rampe laub) und hellem, fasrigem Fleisch (Rampen haut und sand) an der
 * Bruchkante. Nesselfäden (M6-Gate) – der Rest eines Quallenschirms (Rampe eis, Glanz `eis.4` oben) mit drei glasigen,
 * gewellten Fäden darunter, je Faden 1 px mit Kontur `nacht.1`, Glanzpunkte `eis.3` in jedem vierten Pixel.
 */
import { icon } from './_icon';

export default [
  icon(
    'krebsfleisch_roh',
    `................
     ...........kk...
     ..........kMok..
     ...kk.....kMMk..
     ..kMok...kmMk...
     ..kmMok..kmMk...
     ...kmMokkmMMk...
     ....kmMMMMmk....
     ...kkmMMmmmk....
     ..kSSkmmmmLk....
     .kSEESkkLLk.....
     .kSESRSSkk......
     .kRSSRSRSk......
     ..kRRSRRk.......
     ...kkkkk........
     ................`,
  ),
  icon(
    'nesselfaden',
    `................
     ....kkkkkkkk....
     ...k899##998k...
     ...k78999987k...
     ...kk0kk0kk0k...
     ....k9kk9kk9k...
     ...k8k..k8kk8k..
     ...k9k..k9kk9k..
     ....k0kk0kk0k...
     ....k9kk9kk9k...
     ...k8k..k8kk8k..
     ...k9k..k9k.k...
     ....k..k0k......
     ........k.......
     ................
     ................`,
  ),
];
