/**
 * Item-Icons der Küsten-Jagdgüter (M6-23, M6-24; src/content/items/jagd_kueste.ts): rohes Krebsfleisch – eine
 * aufgebrochene Schere mit rot-orangem Panzer (Rampe laub) und hellem, fasrigem Fleisch (Rampen haut und sand) an der
 * Bruchkante.
 */
import { icon } from './_icon';

export default [
  icon(
    'krebsfleisch_roh',
    `................
     ...........kk...
     ..........kMok..
     ...kk.....kMMk..
     ..kMok...kmMk...
     ..kmMok..kmMk...
     ...kmMokkmMMk...
     ....kmMMMMmk....
     ...kkmMMmmmk....
     ..kSSkmmmmLk....
     .kSEESkkLLk.....
     .kSESRSSkk......
     .kRSSRSRSk......
     ..kRRSRRk.......
     ...kkkkk........
     ................`,
  ),
];
