/**
 * Item-Icons des ersten Leuchtfeuers (M7-36/M7-37, Strang F; src/content/items/{lumen,leuchtfeuer,stationen}.ts):
 * Lumen-Laterne, Lumen-Werkbank, Wegstein. Alle drei tragen das Lumen wie die Lumen-Scherbe (jagd.ts): kühles
 * Eis-Blau mit emissivem Kern (`@` `eis.3*`, `=` `eis.4*`), damit „Lumen“ überall dasselbe Zeichen hat.
 *
 * - **Lumen-Laterne**: Bronzelaterne (`METALL_RAMPEN.bronze`) mit Bügel, Kappe, zwei Stegen und Fuß; hinter dem
 *   Glas (`eis.1`/`eis.2`) der glühende Lumen-Kern – kein Flammengelb, sie brennt nicht.
 * - **Lumen-Werkbank**: der Werkbank-Körper (grundlagen.ts) mit einem Lumen-Kristall in Bronzefassung und einer
 *   kleinen Bronzeform auf der Platte.
 * - **Wegstein**: ein behauener Stehstein (Steinrampe, Licht oben links), in der Mitte das Lumen-Auge, darunter
 *   eingekerbte Zeichen.
 */
import { icon } from './_icon';
import { METALL_RAMPEN, METALL_ZEICHEN } from './verarbeitung';

/** Emissives Lumen wie `icon_lumen_scherbe`. */
const LUMEN = { '@': 'eis.3*', '=': 'eis.4*' } as const;

export default [
  icon(
    'lumen_laterne',
    `................
     ......kkkk......
     .....kX..Xk.....
     .....kXkkXk.....
     ....kkTPPTkk....
     ...kWXTTTTXWk...
     ...kQk9@@9kQk...
     ...kXk@==@kXk...
     ...kXk@==@kXk...
     ...kXk9@@9kXk...
     ...kQk8998kQk...
     ...kWXXTTXXWk...
     ....kQWWWWQk....
     .....kkkkkk.....
     ................
     ................`,
    { legende: { ...METALL_RAMPEN.bronze, ...LUMEN }, material: { metall: METALL_ZEICHEN } },
  ),
  icon(
    'lumen_werkbank',
    `................
     ..........kk....
     .........k=@k...
     .........k@=9k..
     ..kk.....k9@8k..
     .k98k...kQXXQk..
     .kkkkkkkkkkkkkk.
     .keeeeeeeeeeeek.
     .kdddddbddddddk.
     .kcccccbcccccck.
     .kbbbbbbbbbbbbk.
     .kcbkkkkkkkkcbk.
     .kcbk......kcbk.
     .kbak......kbak.
     .kkkk......kkkk.
     ................`,
    { legende: { ...METALL_RAMPEN.bronze, ...LUMEN }, material: { metall: METALL_ZEICHEN } },
  ),
  icon(
    'wegstein',
    `................
     ......kkkk......
     .....k5555k.....
     ....k554443k....
     ....k54kk43k....
     ....k4k@=k3k....
     ....k4k=@k2k....
     ....k44kk32k....
     ....k443332k....
     ....k4kk332k....
     ....k43kk32k....
     ...k44333322k...
     ..k4433332222k..
     ...kkkkkkkkkk...
     ................
     ................`,
    { legende: LUMEN },
  ),
];
