/**
 * Item-Icons der Möbel und Lichter T0–T1 (M4-19; src/content/items/moebel.ts): Betten, Sitzmöbel, Tische,
 * Schränke und Regale, Deko-Behälter, Harzlampen, Laternen und der Steinkamin. Bronzebeschläge (`T`, `W`)
 * tragen das Metallflag.
 * Aufsicht wie das Objekt im Kleinen (docs/ART.md §3: 16×16, Motiv ≤ 14×14, 1 px Luft), Kontur `nacht.1`;
 * Flammen im Icon leuchten nicht – ein Möbel in der Tasche ist keine Lichtquelle.
 */
import { icon, type IconOptionen } from './_icon';

/** Bronzebeschläge der Möbel (Farben der Stufenzeile `stufe_bronze`, Metallflag). */
const METALL: IconOptionen = { legende: { T: 'laub.3', W: 'laub.2' }, material: { metall: 'TW' } };

export default [
  icon(
    'strohbett',
    `................
     ..kkkkkkkkkkkk..
     ..kddddddddddk..
     ..kckDEEEEDkck..
     ..kcECDDCDDECk..
     ..kcDCDDEDCDDk..
     ..kcDDCDDCDEDk..
     ..kcDEDCDDCDDk..
     ..kcCDDCDEDDCk..
     ..kckMMMMMMkck..
     ..kckmmmmmmkck..
     ..kckllllllkck..
     ..kkkkkkkkkkkk..
     ..kbk......kbk..
     ..kkk......kkk..
     ................`,
  ),
  icon(
    'holzbett',
    `................
     ..kk........kk..
     ..kdkkkkkkkkdk..
     ..kdeeeeeeeedk..
     ..kbbbbbbbbbbk..
     ..kkkDEEEEDkkk..
     ..kckEEEEEEkck..
     ..kcEEEEEEEEck..
     ..kcMMMMMMMMck..
     ..kclmMMmmmlck..
     ..kclmmMMmmlck..
     ..kclmmmmMMlck..
     ..kkkkkkkkkkkk..
     ..kdeeeeeeeedk..
     ..kkkk....kkkk..
     ................`,
  ),
  icon(
    'hocker_holz',
    `................
     ................
     ................
     ................
     .....kkkkkk.....
     ....keeeeeek....
     ...keddddddek...
     ...kddcccdddk...
     ...kcdddddcck...
     ....kbbbbbbk....
     ....kakkkkak....
     ...kdbk..kdbk...
     ...kdbk..kdbk...
     ..kdbk....kdbk..
     ..kkkk....kkkk..
     ................`,
  ),
  icon(
    'stuhl_holz',
    `................
     ...kk......kk...
     ...kekkkkkkek...
     ...kdeeeeeedk...
     ...kdkkkkkkdk...
     ...kdk....kdk...
     ...kdkkkkkkdk...
     ...kbbbbbbbbk...
     ...keeeeeeeek...
     ...kddddddddk...
     ...kbbbbbbbbk...
     ...kdbkkkkdbk...
     ...kdbkcckdbk...
     ...kdbk..kdbk...
     ...kkkk..kkkk...
     ................`,
  ),
  icon(
    'bank_holz',
    `................
     ................
     ................
     ................
     ................
     ................
     ..kkkkkkkkkkkk..
     .keeeeeeeeeeeek.
     .kddcccdddcccdk.
     .kbbbbbbbbbbbbk.
     .kkakkkkkkkkakk.
     ..kdbk....kdbk..
     ..kdbk....kdbk..
     .kdbk......kdbk.
     .kkkk......kkkk.
     ................`,
  ),
  icon(
    'gartenbank',
    `................
     ................
     ..kkkkkkkkkkkk..
     ..keeeeeeeeeek..
     ..kbbbbbbbbbbk..
     ..kkdkkkkkkdkk..
     .kkkkkkkkkkkkkk.
     .k55keeeeeek55k.
     .k43kbbbbbbk34k.
     .k44keeeeeek44k.
     .kkkkkkkkkkkkkk.
     .k55k......k55k.
     .k43k......k34k.
     .k44k......k44k.
     .kkkk......kkkk.
     ................`,
  ),
  icon(
    'schaukelstuhl',
    `................
     ..kk............
     .kedk...........
     .kdck...........
     ..kdck..........
     ..kdck..........
     ..kdckkkkkkkk...
     ..kdceeeeeeedk..
     ..kdckkkkkkkbk..
     ..kdeeeeeeeeek..
     ..kbbbbbbbbbbk..
     ...kbk....kbk...
     .kk.kbk..kbk.kk.
     .kdkkkbkkbkkkdk.
     ..kkddddddddkk..
     ................`,
  ),
  icon(
    'truhenbank',
    `................
     ................
     ..kk........kk..
     ..kdkkkkkkkkdk..
     ..kdeeeeeeeedk..
     ..kdcdddcdddck..
     ..kkkkkkkkkkkk..
     .keeeeeeeeeeeek.
     .kbbbbbbbbbbbbk.
     .kkkkkkTTkkkkkk.
     .kdkcccWWccckdk.
     .kdkcddddddckdk.
     .kdkbbbbbbbbkdk.
     .kbccccccccccbk.
     .kkkk......kkkk.
     ................`, METALL,
  ),
  icon(
    'sitzkissen',
    `................
     ................
     ................
     ................
     ................
     ...kkkkkkkkkk...
     ..kMooMMMMooMk..
     .kMMMMMMMMMMMMk.
     .kmMMMMkkMMMMmk.
     .kmMMMkLLkMMMmk.
     .kmmMMMkkMMMmmk.
     .kmmmMMMMMMmmmk.
     .klmmmmmmmmmmlk.
     ..kllllllllllk..
     ...kkkkkkkkkk...
     ................`,
  ),
  icon(
    'tisch_holz',
    `................
     ................
     ................
     ..kkkkkkkkkkkk..
     .keeeeeeeeeeeek.
     .kddddcccdddddk.
     .kccbccccccbcck.
     .kdddddcccddddk.
     .kbbbbbbbbbbbbk.
     .kkkkkkkkkkkkkk.
     ..kdbkcccckdbk..
     ..kdbkkkkkkdbk..
     ..kdbk....kdbk..
     ..kdbk....kdbk..
     ..kkkk....kkkk..
     ................`,
  ),
  icon(
    'tischdecke',
    `................
     ................
     ................
     ..kkkkkkkkkkkk..
     .kEEmmEEmmEEmmk.
     .kEEmmEEmmEEmmk.
     .kmmllmmllmmllk.
     .kEEmmEEmmEEmmk.
     .kmmllmmllmmllk.
     .kEEmmEEmmEEmmk.
     .kCClCClCClCCCk.
     .kkkkkkkkkkkkkk.
     ..kdbk....kdbk..
     ..kdbk....kdbk..
     ..kkkk....kkkk..
     ................`,
  ),
  icon(
    'schreibpult',
    `................
     ...........kk...
     ..........kEEk..
     .........kEEk...
     ..kkkkkkkEDkkk..
     .keeeeeekkDkkek.
     .kdEEEEdkNNkddk.
     .kdECCEdkNNkddk.
     .kdEEEEdkkkkddk.
     .kbbbbbbbbbbbbk.
     .kkkkkkkkkkkkkk.
     .kkccTcckkcTcck.
     .kkbbbbbkkbbbbk.
     ..kdbkkkkkkdbk..
     ..kkkk....kkkk..
     ................`, METALL,
  ),
  icon(
    'nachttisch',
    `................
     ...kkkkkkkkkk...
     ..keeeeeeeeeek..
     ..kbbbbbbbbbbk..
     ..kkkkkkkkkkkk..
     ..kdkcccccckdk..
     ..kdkcddkkckdk..
     ..kdkcddddckdk..
     ..kdkbbbbbbkdk..
     ..kdkkkkkkkkdk..
     ..kdkKKmyKKkdk..
     ..kdkKKmyKKkdk..
     ..kdkbbbbbbkdk..
     ..kbkkkkkkkkbk..
     ..kkk......kkk..
     ................`,
  ),
  icon(
    'schrank_holz',
    `................
     .kkkkkkkkkkkkkk.
     .keeeeeeeeeeeek.
     .kbbbbbbbbbbbbk.
     .kkkkkkkkkkkkkk.
     ..kdbbbdkdbbbdk.
     ..kdcccdkdcccdk.
     ..kdcccdkdcccdk.
     ..kddddTkTddddk.
     ..kdbbbdkdbbbdk.
     ..kdcccdkdcccdk.
     ..kdcccdkdcccdk.
     .kkkkkkkkkkkkkk.
     .kbbbbbbbbbbbbk.
     .kkkk......kkkk.
     ................`, METALL,
  ),
  icon(
    'kommode',
    `................
     ..kkkkkkkkkkkk..
     .keeeeeeeeeeeek.
     .kbbbbbbbbbbbbk.
     .kkkkkkkkkkkkkk.
     .kdkccTcckcTckk.
     .kdkbbbbbkbbbkk.
     .kdkkkkkkkkkkkk.
     .kdkccTcckcTckk.
     .kdkbbbbbkbbbkk.
     .kdkkkkkkkkkkkk.
     .kccccccccccccc.
     .kbbbbbbbbbbbbk.
     .kkkkkkkkkkkkkk.
     ..kbk......kbk..
     ................`, METALL,
  ),
  icon(
    'buecherregal',
    `................
     .kkkkkkkkkkkkkk.
     .kccccccccccccc.
     .kkkkkkkkkkkkkk.
     .kdcyymmnhhClck.
     .kdcyymmnhhClck.
     .kdcxylmnghCllk.
     .kdddddddddddck.
     .kdcCCmhhnyymck.
     .kdcCClhgnyxmck.
     .kdcCClhgnxxlck.
     .kdddddddddddck.
     .kbbbbbbbbbbbbk.
     .kkkkkkkkkkkkkk.
     ..kbk......kbk..
     ................`,
  ),
  icon(
    'weinregal',
    `................
     .kkkkkkkkkkkkkk.
     .keeeeeeeeeeeek.
     .kkkkkkkkkkkkkk.
     .kdnhncnhncnhdk.
     .kdhChchChchCdk.
     .kdngncngncngdk.
     .kdcccccccccccd.
     .kdnhncnnncnhdk.
     .kdhChcnnnchCdk.
     .kdngncnnncngdk.
     .kdbbbbbbbbbbdk.
     .kkkkkkkkkkkkkk.
     ..kbk......kbk..
     ..kkk......kkk..
     ................`,
  ),
  icon(
    'regal_wand',
    `................
     ................
     ................
     ................
     ...kk...........
     ..kssk...kkk....
     ..krsk..kssrk...
     .kkrrkk.krrrk...
     .kqrrqkkkqqqkk..
     .kkqqkkdekkkkdk.
     .kkkkkkkkkkkkkk.
     .keeeeeeeeeeeek.
     .kbbbbbbbbbbbbk.
     ..kkbk....kbkk..
     ...kkk....kkk...
     ................`,
  ),
  icon(
    'kleiderhaken',
    `................
     ..kkkkkkkkkkkkk.
     ..keeeeeeeeeeek.
     ..kbbbbbbbbbbbk.
     ..kkdkkkkdkkkkk.
     ...kdk..kdk..kk.
     ..kssrk.kDk.....
     .kssssrkkEDk....
     .ksrssrrkDDDk...
     .ksrsssrkEDDk...
     .kqrrssrkDDDDk..
     .kqrrrrqkCDDDk..
     .kqqrrqqkkCCCk..
     ..kqqqqk..kkk...
     ...kkkk.........
     ................`,
  ),
  icon(
    'truhe_deko',
    `................
     ................
     ...kkkkkkkkkk...
     ..kMMeeeeeeMMk..
     .kdMMddddddMMdk.
     .kdmmddddddmmdk.
     .kcmmccMMccmmck.
     .kkkkkkmmkkkkkk.
     .kdmmdkqqkdmmdk.
     .kdmmdkkkkdmmdk.
     .kcmmccccccmmck.
     .kcmmccccccmmck.
     .kbqqbbbbbbqqbk.
     .kkkkkkkkkkkkkk.
     ..kbk......kbk..
     ................`,
  ),
  icon(
    'kiste_deko',
    `................
     ................
     ....kkk.hikk....
     ...kMMmkihMmk...
     ..kkmmlkkmmlkk..
     .kMMmkMMmkMMmkk.
     .kmmlkmmlkmmlkk.
     .kkkkkkkkkkkkkk.
     .kceeeeeeeeeeck.
     .kcddddddddddck.
     .kbbbbbbbbbbbbk.
     .kceeeeeeeeeeck.
     .kcddddddddddck.
     .kbbbbbbbbbbbbk.
     .kkkkkkkkkkkkkk.
     ................`,
  ),
  icon(
    'fass_holz',
    `................
     ....kkkkkkkk....
     ..kkeeeeeeeekk..
     .keccccccccccek.
     .kedddcdddcddek.
     .keddddcdddcdek.
     ..kkeeeeeeeekk..
     .kbbbbbbbbbbbbk.
     .kaaaaaaaaaaaak.
     .kdddcdddcddddk.
     .kdddcdddcddddk.
     .kbbbbbbbbbbbbk.
     .kaaaaaaaaaaaak.
     ..kbbcbbbcbbbk..
     ...kkkkkkkkkk...
     ................`,
  ),
  icon(
    'harzlampe',
    `................
     .......F........
     ......FuF.......
     ...kkkuvukkkk...
     ..kssvVVvssssk..
     ..kooMoooMooMk..
     ..krsssssssrrk..
     ...krrrrrrrrk...
     ....kqqqqqqk....
     .....kkddkk.....
     ......kddk......
     .....kdkdkdk....
     ....kdk.k.kdk...
     ...kdk..k..kdk..
     ...kkk..k..kkk..
     ................`,
  ),
  icon(
    'harzlampe_wand',
    `................
     ................
     ................
     .......F........
     ...kkkFUFkkkk...
     ..ksssUvvUsssk..
     ..kooMvVVvMoMk..
     ..krsssssssrrk..
     ...krrrrrrrrk...
     ....kqqqqqqk....
     .....kkkkkk.....
     ..kkkkcddckkkk..
     ..kdddddddddck..
     ..kcccccccccck..
     ..kkkkkkkkkkkk..
     ................`,
  ),
  icon(
    'laterne_stehend',
    `................
     ......kMMk......
     .....kMMMMk.....
     ....kMMMMMMk....
     ...kmmmmmmmmk...
     ...kqkkkkkkqk...
     ...kmkDEEDkmk...
     ...kmkDvvDkmk...
     ...kmkDVVDkmk...
     ...kmkDDDDkmk...
     ...kqkkkkkkqk...
     ....kqqqqqqk....
     ...kkkkkkkkkk...
     ..kddddddddddk..
     ..kkkkkkkkkkkk..
     ................`,
  ),
  icon(
    'laternenpfahl',
    `................
     .......kk.......
     ......kMMk......
     .....kMMMMk.....
     ....kmmmmmmk....
     ....kqkkkkqk....
     ....kmkEEkmk....
     ....kmkvvkmk....
     ....kqkkkkqk....
     ....kMMMMMMk....
     .....kkddkk.....
     ......kdck......
     ......kdck......
     ....kkddcckk....
     ....kkkkkkkk....
     ................`,
  ),
  icon(
    'kamin_stein',
    `................
     ....kkkkkkkk....
     ....k545k54k....
     ....kkkkkkkk....
     ....k4k5545k....
     .kkkkkkkkkkkkkk.
     .kddddddddddddk.
     .kkkkkkkkkkkkkk.
     .k54kKKKKKKk45k.
     .k43kKnnFnnk34k.
     .kkkknFuuFnkkkk.
     .k54knFvvFnk45k.
     .k43kkcckcckk4k.
     .k545455544554k.
     .kkkkkkkkkkkkkk.
     ................`,
  ),
];
