/**
 * Item-Icons der Setzlinge und Blumen (docs/SPIEL.md §6, M3-04, M3-11 „40 % Setzling“, M3-13 Blumen).
 *
 * Setzlinge: ein gemeinsamer Wurzelballen (Erde, unten) mit dem Stämmchen, darüber die Krone der Art in
 * ihrer eigenen Silhouette – Eiche rund und gelappt, Birke weißer Stamm mit lichtem Hängelaub, Buche hoch
 * und oval, Kiefer als Nadelstufen, Weide als Vorhang; die Obstbäume tragen eine runde Krone mit ihrer
 * Frucht bzw. Blüte (Apfel rot, Kirsche Blütenweiß mit roten Paaren, Birne gelb, Walnuss grüne Nüsse).
 * Blumen: eine Form, drei Blütenfarben über Platzhalterzeichen (`<` hell, `=` mittel, `>` dunkel,
 * `@` Blütenmitte).
 */
import { icon } from './_icon';

/** Wurzelballen (Zeilen 10–15); `|` = Stämmchen in der Farbe der Art. */
const BALLEN = `.......k|k......
     .....kks|skk....
     ....ksrs|rsrk...
     ....kqrrqrrqk...
     .....kkkkkkk....
     ................`;

/** Setzling: zehn Kronenzeilen (0–9) über dem Wurzelballen; `stamm` färbt `|`. */
function setzling(art: string, krone: string, stamm: string, legende: Readonly<Record<string, string>> = {}) {
  return icon(`setzling_${art}`, `${krone}\n     ${BALLEN}`, { legende: { '|': stamm, ...legende }, hoehe: 'kugel' });
}

const BLUME = `................
     .....kk.kk......
     ....k<<k<<k.....
     ...kk<=k=<kk....
     ..k<<=@@@=<<k...
     ..k>==@@@==>k...
     ...kk>=k=>kk....
     ....k>>k>>k.....
     .....kkhkk......
     ..kk...hk.kk....
     .kjik..hkkjik...
     ..kiikkhkiik....
     ...kkkhhkkk.....
     ......khk.......
     ......kk........
     ................`;

function blume(farbe: string, hell: string, mittel: string, dunkel: string, mitte: string) {
  return icon(`blume_${farbe}`, BLUME, { legende: { '<': hell, '=': mittel, '>': dunkel, '@': mitte }, hoehe: 'kugel' });
}

export default [
  setzling(
    'eiche',
    `................
     .....kk.kkk.....
     ...kkjjkjjjkk...
     ..kjjiijjiijjk..
     .kjiiijiiiijiik.
     .kiihiiihiiihik.
     .khhihhhhhihhhk.
     ..khhhkkckhhhk..
     ...kkk..ck.kk...
     .......kck......`,
    'holz.2',
  ),
  setzling(
    'birke',
    `................
     .....kkkkkk.....
     ....kJJjjjJk....
     ...kJjjJjjjjk...
     ..kjjjijjjijjk..
     ..kjiijjjjiijk..
     ...kiihk0khiik..
     ....kkkk7kkkk...
     .......k7k......
     .......k0k......`,
    'eis.3',
  ),
  setzling(
    'buche',
    `................
     .......kk.......
     ......kjJk......
     .....kjJjjk.....
     ....kjjjjiik....
     ....kijjiihk....
     ....kiiiihhk....
     .....khhhhk.....
     ......kk4k......
     .......k4k......`,
    'stein.3',
  ),
  setzling(
    'kiefer',
    `................
     .......kk.......
     ......khhk......
     .....khiihk.....
     ....kghhhhgk....
     ...khhiiiihhk...
     ..kkghhhhhhgkk..
     ..kghhiiiihhgk..
     ...kkgggggmkk...
     .......kmk......`,
    'laub.2',
  ),
  setzling(
    'weide',
    `................
     ....kkkkkkkk....
     ..kkjJjjJjjjkk..
     .kjjjjjjjjjjjik.
     .kijikjcjkijik..
     .kik.kjck.kijk..
     .kik.kick.kik...
     .kik.kick..kik..
     ..k...kck...k...
     .......kck......`,
    'holz.2',
  ),
  setzling(
    'apfelbaum',
    `................
     ......kkkk......
     ....kkjjjjkk....
     ...kjjijjiijk...
     ..kjijjiiuuiik..
     ..kiiuuiiuFihk..
     ..kiiuFiiihhhk..
     ...khhhhchhhk...
     ....kkkkckkk....
     .......kck......`,
    'holz.2',
  ),
  setzling(
    'kirschbaum',
    `................
     ......kkkk......
     ....kk##jjkk....
     ...kj#0jj#0jk...
     ..kjiijj#0ijjk..
     ..k#0iiiiuiiik..
     ..k0iuiiiuFihk..
     ...khFhhchhhk...
     ....kkkkckkk....
     .......kck......`,
    'holz.2',
  ),
  setzling(
    'birnbaum',
    `................
     ......kkkk......
     ....kkjjjjkk....
     ...kjjijjiijk...
     ..kjiDjjiiEiik..
     ..kiDDiiiDEDik..
     ..kiDBiiiDDBhk..
     ...khhhhchBhk...
     ....kkkkckkk....
     .......kck......`,
    'holz.2',
  ),
  setzling(
    'walnussbaum',
    `................
     ....kk....kk....
     ...kjjkkkkjjk...
     ..kjjijjjjijjk..
     .kjijtsiijjijik.
     .kiiissiiiitsik.
     .khiihhhiiisshk.
     ..khhhhhchhhhk..
     ...kkkkkckkkk...
     .......kck......`,
    'holz.2',
  ),
  blume('rot', 'feuer.2', 'feuer.1', 'feuer.0', 'feuer.4'),
  blume('blau', 'wasser.4', 'wasser.3', 'wasser.2', 'feuer.4'),
  blume('gelb', 'feuer.5', 'feuer.4', 'feuer.3', 'holz.1'),
];
