/**
 * Item-Icons der Jagdtrophäen des Grünhains (M6-30d; src/content/items/trophaeen.ts): die Sonderteile von Wolf und Keiler
 * und der Schmuck, der aus ihnen entsteht. Zahn und Hauer sind Elfenbein wie der Knochen der Jagdgüter (`sand` mit der
 * Glanzkante `eis.4` oben, `sand.3` unten), ihre Wurzel dunkler; Schnüre sind gedrehte Sehne (`haut`, wie das Icon
 * `sehnen`):
 * - Wolfszahn: ein Reißzahn, oben die breite Wurzel (`sand.2`), dann zur Spitze unten links gekrümmt und verjüngt.
 * - Keilerhauer: ein sichelförmiger Hauer, die Spitze oben links, die abgebrochene Wurzel braun (`erde`).
 * - Wolfszahnkette: eine Sehnenschnur im Bogen, drei Zähne hängen daran, der mittlere am längsten.
 * - Haueramulett: eine Sehnenschlaufe, an einem Knoten (`erde`) hängt ein Hauer wie ein liegender Halbmond.
 */
import { icon } from './_icon';

export default [
  icon(
    'wolfszahn',
    `................
     ..........kkk...
     .........kCCCk..
     ........kDEE#k..
     ........kDEE#k..
     ........kDEE#k..
     ........kDE#k...
     .......kDEE#k...
     .......kDE#k....
     ......kDE#k.....
     ......kDE#k.....
     .....kDE#k......
     ....kDE#k.......
     ...kD#k.........
     ...kkk..........
     ................`,
  ),
  icon(
    'keilerhauer',
    `................
     ................
     ..kk............
     ..k#k...........
     ..kE#k..........
     ..kDE#k.........
     ..kDE#k.........
     ...kDE#k........
     ...kDEE#k.......
     ....kDEE#kk.....
     ....kDDEEE#kkk..
     .....kDDEEEE#rk.
     ......kkDDEEErk.
     ........kkkkkkk.
     ................
     ................`,
  ),
  icon(
    'wolfszahnkette',
    `................
     .kk..........kk.
     .kSk........kSk.
     ..kSk......kSk..
     ..kRSk....kSRk..
     ...kRSkkkkSRk...
     ..kkkRRSSRRkkk..
     .kE#kkkE#kkkE#k.
     .kE#k.kE#k.kE#k.
     .kDEk.kE#k.kDEk.
     ..kDk.kDEk.kDk..
     ..kk..kDEk..kk..
     ......kDDk......
     .......kk.......
     ................
     ................`,
    { einzelpixel: 'Die Spitzen der Zähne sind 1 px breit' },
  ),
  icon(
    'haueramulett',
    `................
     .....kkkkkk.....
     ....kSRRRRSk....
     ...kSk....kSk...
     ...kRk....kRk...
     ....kRk..kRk....
     .....kSkkSk.....
     ..kk..kppk..kk..
     .k#k.krrrrk.k#k.
     .kE#kkkrrkkkE#k.
     ..kDEE#kk#EEDk..
     ...kDDEEEEEDDk..
     ....kkDDDDDDk...
     ......kkkkkk....
     ................
     ................`,
  ),
];
