/**
 * Item-Icons der Verarbeitungsprodukte T0–T1 (docs/SPIEL.md §8 „Verarbeitungsprodukte“, M4-10): Holzkohle,
 * Brett, Balken, Dachschindel, Steinblock, Strohbündel, Rohziegel, Ziegel, Keramiktopf, Glas, Lehmputz,
 * Kupfer-, Zinn- und Bronzebarren, Garn, Bronzenagel.
 *
 * Jedes Produkt zeigt, woraus es gemacht ist: Holzkohle als verkohltes Scheit in der Form des Holz-Icons
 * (Stirn mit Schwundrissen, Mantel in Blöcke gesprungen, grauer Glanz auf den Oberseiten) mit einem Brocken
 * davor, Bretter gestapelt, der Balken als Kantholz in Schrägansicht mit Stirnholz, drei gespaltene
 * Schindeln gefächert, der Steinblock als behauener Quader (Rampe `stein` wie der Stein), das Strohbündel
 * als Garbe mit Schnur, Roh- und Brandziegel als zwei gestapelte Ziegel derselben Form (Lehm matt, gebrannt
 * ziegelrot), der Topf aus Terrakotta mit Ritzband, Glas als grünlich-türkise Scheibe mit Bläschen
 * (Glanzflag), Lehmputz im Holztrog mit Strohhäcksel und Holzkelle, Garn als Leinenknäuel auf der Spindel
 * (dieselben Garnfarben wie die Griffwicklung der Bronzesichel), zwei Bronzenägel. Die drei Barren teilen
 * die Barrenform und unterscheiden sich im Metall: Kupfer rot, Zinn bläulich-silbern, Bronze goldbraun (mit
 * Metallflag, Rampen in `METALL_RAMPEN`). Konvention und Legende: `_icon.ts`.
 */
import type { Sprite } from '../../lib/sprite';
import { icon } from './_icon';

/**
 * Metallrampen der Barren, Nägel und Bronzewerkzeuge: `Q` Tiefe · `W` Schatten · `X` Grundton · `T` Licht ·
 * `P` Glanz. Bronze ist goldbraun mit Honiggold und hellem Glanz – wärmer und gelber als das rote Kupfer,
 * brauner als Gold; Zinn bläulich-silbern, heller und kühler als der Stein.
 */
export const METALL_RAMPEN = {
  bronze: { Q: 'erde.1', W: 'holz.2', X: 'holz.3', T: 'laub.4', P: 'sand.4' },
  kupfer: { Q: 'laub.0', W: 'laub.1', X: 'laub.2', T: 'haut.3', P: 'haut.4' },
  zinn: { Q: 'stein.1', W: 'stein.2', X: 'stein.3', T: 'eis.2', P: 'eis.4' },
} as const;

/** Zeichen der Metallrampe (bekommen das Materialflag `metall`). */
export const METALL_ZEICHEN = 'QWXTP';

/** Barren: flache Oberseite (Licht), schräge Stirnseiten, Vorderseite im Grundton, Fußkante in der Tiefe. */
const BARREN = `................
     ................
     ................
     ................
     ...kkkkkkkkkk...
     ..kWPPTTTTTTWk..
     .kWWTTTTTTTTWWk.
     .kQXXXXXXXXXXQk.
     .kQXXXXXXXXXXQk.
     .kQWWWWWWWWWWQk.
     ..kkkkkkkkkkkk..
     ................
     ................
     ................
     ................
     ................`;

const barren = (id: string, metall: keyof typeof METALL_RAMPEN): Sprite => icon(id, BARREN, { legende: METALL_RAMPEN[metall], material: { metall: METALL_ZEICHEN } });

/** Ziegelform (Roh- und Brandziegel): zwei Ziegel, der hintere versetzt auf dem vorderen. */
const ZIEGEL = `................
     ................
     ................
     .....kkkkkkkkk..
     ....kEEEEEEEEDk.
     ....kDDDDDDDDCk.
     ....kCCCCCCCCBk.
     .kkkkCCCCCCCCBk.
     .kEEkBBBBBBBBAk.
     .kDDDkkkkkkkkkk.
     .kCCCCCCCCCCBk..
     .kCCCCCCCCCCBk..
     .kBBBBBBBBBBAk..
     ..kkkkkkkkkkkk..
     ................
     ................`;

export default [
  icon(
    'holzkohle',
    `................
     ................
     ................
     ...kkkkkkkkkk...
     ..kN~~Nk3~3K~k..
     .kN~NN~kN~NKNNk.
     .k~NKN~knnnKnnk.
     .k~KnK~kKK3~3~k.
     .kN~N~Nk~3KNN~k.
     .kNN~NNkNnKnnNk.
     ..knnnkkkkkkkk..
     .....kk~33kk....
     ....k3~~NNnnk...
     ....kNnKnnKnk...
     .....kkkkkkk....
     ................`,
  ),
  icon(
    'brett',
    `................
     ................
     ................
     ....kkkkkkkkkk..
     ...keeeeeeeeddk.
     ...kdddcdddddck.
     ..kkcccccccccbk.
     .keeeeeeeeeddkk.
     .kdddcddddddck..
     .kccccccccccbk..
     .kbbbbbbbbbbbk..
     ..kkkkkkkkkkk...
     ................
     ................
     ................
     ................`,
  ),
  icon(
    'balken',
    `................
     ................
     ................
     ....kkkkkkkkkk..
     ...keeeeeeeekdk.
     ..keeeeeeeekddk.
     .kkkkkkkkkkdcdk.
     .kdddcddddkcbdk.
     .kcccccbcckdcdk.
     .kbbbbbbbbkcdk..
     .kkkkkkkkkkkk...
     ................
     ................
     ................
     ................
     ................`,
  ),
  icon(
    'dachschindel',
    `................
     ......kkk.......
     ..kk.keedk.kk...
     .kedkkeddkkedk..
     .kedkkeddkkedk..
     .kdckkeddkkdck..
     ..kedkeddkedk...
     ..kedkeddkedk...
     ..kdckeddkdck...
     ...kdkeddkdk....
     ...kbkdddkbk....
     ....kkdcckk.....
     .....kbbbk......
     .....kkkkk......
     ................
     ................`,
  ),
  icon(
    'steinblock',
    `................
     ................
     ................
     ...kkkkkkkkkk...
     ..k6656666565k..
     ..k5666655666k..
     ..k5555555555k..
     ..k4443444434k..
     ..k4344444344k..
     ..k4434443444k..
     ..k3333233333k..
     ..k2222222222k..
     ...kkkkkkkkkk...
     ................
     ................
     ................`,
  ),
  icon(
    'strohbuendel',
    `................
     ...k.kk.kk.k....
     ..kEkEDkDEkEk...
     ..kDEDEEDEDDk...
     ...kDEDDEDDk....
     ....kDDEDDk.....
     ....kbbbbbk.....
     ....kaabaak.....
     ....kCDDCDk.....
     ...kDCDDCDDk....
     ..kCDCCDCCDCk...
     ..kCCBCCBCCBk...
     ..kEEkEEkEEkk...
     ...kk.kk.kk.....
     ................
     ................`,
  ),
  icon('ziegel_roh', ZIEGEL, { legende: { E: 'sand.2', D: 'sand.1', C: 'sand.0', B: 'erde.2', A: 'erde.1' } }),
  icon('ziegel', ZIEGEL, { legende: { E: 'laub.3', D: 'laub.2', C: 'laub.2', B: 'laub.1', A: 'laub.0' } }),
  icon(
    'keramik_topf',
    `................
     ................
     ....kkkkkkkk....
     ...kSRRRRRRSk...
     ...kRKKKKKKRk...
     ....kRRRRRRk....
     ...kRSSRRRRRk...
     ..kRSRRRRRROOk..
     ..kRRRRRRROOOk..
     ..kqrqrqrqrqqk..
     ..kOOOOOOOOIIk..
     ...kOOOOOIIIk...
     ....kIIIIIIk....
     .....kkkkkk.....
     ................
     ................`,
  ),
  icon(
    'glas',
    `................
     ................
     ...kkkkkkkkkk...
     ..kzZZZZZZZZzk..
     ..kZ#YYYYZYYZk..
     ..kZ#YYYYYYYZk..
     ..kZY#YYZYYYZk..
     ..kZYY#YYYYYZk..
     ..kZYYY#YYZYZk..
     ..kZYZYY#YYYZk..
     ..kZYYYYY#YYZk..
     ..kzZZZZZZZZzk..
     ..kxzzzzzzzzxk..
     ...kkkkkkkkkk...
     ................
     ................`,
    { material: { nass: 'xzZY#' } },
  ),
  icon(
    'lehmputz',
    `................
     ............kk..
     ...........kdbk.
     ..........kdbk..
     .........kdbk...
     ..kkkkkkkeekkkk.
     .kttsttskddssrk.
     .ksDssDsrkcsDsk.
     .kkkkkkkkkkkkkk.
     .keeeeeeeeeeeek.
     .kdcddcdddcddck.
     ..kcccbcccbcck..
     ..kbbbabbbabbk..
     ...kkkkkkkkkk...
     ................
     ................`,
  ),
  barren('kupferbarren', 'kupfer'),
  barren('zinnbarren', 'zinn'),
  barren('bronzebarren', 'bronze'),
  icon(
    'garn',
    `................
     ............kk..
     ...........kdbk.
     ......kkkkkdbk..
     ....kk6646kbkk..
     ...k66466466k...
     ...k64664664k...
     ..k664664663k...
     ..k646646633k...
     ..k466466433k...
     ...k6466433k....
     ..kkk33333kk....
     .kdbkkkkkk......
     .kbk............
     ..k.............
     ................`,
  ),
  icon(
    'nagel_bronze',
    `................
     .kkkkkk.........
     .kPTTXk.........
     .kWXXWk.kkkkkk..
     .kkXWkk.kPTTXk..
     ..kXWk..kWXXWk..
     ..kXWk..kkXWkk..
     ..kXWk...kXWk...
     ..kXWk...kXWk...
     ..kXWk...kXWk...
     ..kXWk...kXWk...
     ..kXWk...kXWk...
     ..kWk....kXWk...
     ...k.....kWk....
     ..........k.....
     ................`,
    { legende: METALL_RAMPEN.bronze, material: { metall: METALL_ZEICHEN } },
  ),
];
