/**
 * Stücke des Erbauer-Friedhofs (M7-09; docs/SPIEL.md §18): Grabsteine in drei Varianten (Rundstein mit Erbauer-Sonne und
 * Inschrift, Steinkreuz, zerbrochene Platte – der Renderer wählt je Kachel eine), der Grabobelisk (die Inschrift des Orts, Tafel
 * `tafel`; verjüngter Schaft auf Sockel, Glyphenreihe, Efeu) und der rostige Eisenzaun in zwei Stücken: `ort_eisenzaun` läuft
 * quer (Spitzstäbe, zwei Riegel; zweite Variante mit verbogenem und fehlendem Stab), `ort_eisenzaun_senkrecht` läuft in die
 * Tiefe – in der Draufsicht fallen Stäbe und Riegel in eine Spalte, oben die Spitzen. Anker auf der Vorderkante.
 */
import { ort } from './_ort';

const GRAB_RUND = `................
                   ................
                   ................
                   ................
                   ................
                   .....11111......
                   ....1555551.....
                   ...1544444411...
                   ..154444444451..
                   ..154412214431..
                   ..154421124431..
                   ..154421324431..
                   ..144412224431..
                   ..144444424431..
                   ..144444442431..
                   ..144222222431..
                   ..144444444431..
                   ..14hh22224431..
                   ..14hhh4444431..
                   ..133333333331..
                   .1h1111111111h1.
                   .1hh1.....1h1h1.
                   ..kk.......k.k..
                   ................`;

const GRAB_KREUZ = `................
                    ................
                    ................
                    ................
                    ................
                    ......1111......
                    .....155551.....
                    ...1115443111...
                    ..155544445551..
                    ..154442244431..
                    ..154442344431..
                    ...1115443111...
                    .....144431.....
                    .....144431.....
                    .....144431.....
                    .....144431.....
                    ...11144431.....
                    ..1hh544445111..
                    ..1hhh333333331.
                    ..111111111111..
                    .1h1.......11h1.
                    .1hh1.....1h1h1.
                    ..kk.......k.k..
                    ................`;

const GRAB_BRUCH = `................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    .........11.....
                    .......11551....
                    .....1155431....
                    ...1155444451...
                    ..155444444451..
                    ..154444444431..
                    ..154222222431..
                    ..144444444431..
                    ..144222224431..
                    ..14hh44444431..
                    .114hhh4444431..
                    15554111111111..
                    34h11......11h1.
                    13hh1.....1h1h1.
                    .kkk.......k.k..
                    ................`;

const OBELISK = `................
                 .......1........
                 ......151.......
                 ......1551......
                 ......15451.....
                 .....154431.....
                 ......1111......
                 .....154431.....
                 .....154431.....
                 .....154431.....
                 .....152131.....
                 .....152431.....
                 .....154431.....
                 ....15422431....
                 ....15444431....
                 ....15444431....
                 ....15412431....
                 ....15444431....
                 ....15444431....
                 ....15424431....
                 ....15444431....
                 ....15444431....
                 ....15421431....
                 ...1544444431...
                 ...1544444431...
                 ...1544224431...
                 ...15h4444431...
                 ...15hi444431...
                 ...151h124431...
                 ...15hh444431...
                 ...15ih441h31...
                 ...154444hi31...
                 ..1154444h1311..
                 .15555555555551.
                 1355555555555521
                 13hhi1111111111.
                 131h111111111h21
                 1344444444444421
                 13444444444hh421
                 13333333333ih321
                 1322222222222221
                 .kkkkkkkkkkkkkk.
                 ................
                 ................`;

const EISENZAUN = `................
                   ................
                   ................
                   ................
                   .~...~...~...~..
                   ~N~.~N~.~N~.~N~.
                   .N...N...N...N..
                   .nk..nk..nk..nk.
                   .Nk..Nk..Nk..Nk.
                   .Nk..Nk..Nk..Nk.
                   .Nk..Nk..Nk..Nl.
                   .Nk..Nk..Nk..Nk.
                   NNkNNNkNNlkNNNkN
                   KNkKKNkKKNkKKNkK
                   .Nk..Nk..Nk..Nm.
                   .Nl..Nk..Nk..Nk.
                   .Nk..Nk..Nk..Nk.
                   .Nk..Nk..Nk..Nk.
                   .Nk..Nk..Nl..Nk.
                   .Nk..Nk..Nk..Nk.
                   NNkNNNkNNNkNNNkN
                   KlkKKNkKKNkKKlkK
                   .Nk..Nk..Nk..Nk.
                   h...h......h..h.
                   hh.hih...h.hh.hh
                   kk.kkk...k.kk.kk
                   ................
                   ................`;

const EISENZAUN_LUECKE = `................
                          ................
                          ................
                          ................
                          .~.........~.~..
                          ~N~.......~N~N~.
                          .N.........N.N..
                          .nk........nknk.
                          .Nk........NkNk.
                          .Nk.......Nk.Nk.
                          .Nk.......Nk.Nl.
                          .Nk......Nk..Nk.
                          NNkN.....lkNNNkN
                          KNkKNNN..NkKKNkK
                          .Nk..KKNNNk..Nm.
                          .Nl....KKNk..Nk.
                          .Nk......Nk..Nk.
                          .Nk......Nk..Nk.
                          .Nk......Nl..Nk.
                          .Nk......Nk..Nk.
                          NNkNNlNNNNkNNNkN
                          KlkKKKmKKNkKKlkK
                          .Nk......Nk..Nk.
                          h...h......h..h.
                          hh.hih...h.hh.hh
                          kk.kkk...k.kk.kk
                          ................
                          ................`;

const EISENZAUN_TIEFE = `................
                         ................
                         .......~........
                         ......~N~.......
                         .......Nk.......
                         .......Nk.......
                         .......~........
                         ......~N~.......
                         .......Nk.......
                         .......Nk.......
                         .......l........
                         ......~N~.......
                         .......Nk.......
                         .......nk.......
                         .......~........
                         ......~N~.......
                         .......Nk.......
                         .......Nk.......
                         .......Nl.......
                         .......Nk.......
                         .......Nk.......
                         .......nk.......
                         .......Nk.......
                         .......lk.......
                         .......Nk.......
                         .......Nk.......
                         .......Nk.......
                         ....h....h......
                         ....hi..ih......
                         .......kk.......
                         ................
                         ................`;

export default [
  ort({ id: 'grabstein', size: [16, 24], anchor: [8, 22], hoehe: 'block', frames: [GRAB_RUND, GRAB_KREUZ, GRAB_BRUCH], occluder: { kind: 'rect', x: 3, y: 9, w: 10, h: 13 } }),
  ort({ id: 'obelisk', size: [16, 44], anchor: [8, 42], hoehe: 'block', frames: [OBELISK], occluder: { kind: 'rect', x: 1, y: 6, w: 14, h: 36 } }),
  ort({ id: 'eisenzaun', size: [16, 28], anchor: [8, 26], hoehe: 'block', frames: [EISENZAUN, EISENZAUN_LUECKE], occluder: { kind: 'rect', x: 0, y: 5, w: 16, h: 20 }, material: { metall: 'KknN~' }, einzelpixel: 'Rostpunkte auf dem Eisen und die Steinfüße der Stäbe' }),
  ort({ id: 'eisenzaun_senkrecht', size: [16, 32], anchor: [8, 30], hoehe: 'block', frames: [EISENZAUN_TIEFE], occluder: { kind: 'rect', x: 5, y: 1, w: 6, h: 28 }, material: { metall: 'KknN~' } }),
];
