/**
 * Stücke des verlassenen Gehöfts (M7-08; docs/SPIEL.md §18): der zerbrochene Karren (2×1, Achse gebrochen, ein Rad liegt am
 * Wagenkasten, ein Sack ist herausgefallen), der alte Brunnen (Steinring, Pfosten mit Walze, Seil und Eimer), der faulige
 * Heuballen (nasse Stellen, Gras keimt obenauf), der morsche Zaun (zwei Varianten: heil, oberer Riegel gebrochen; die Riegel
 * laufen bis an den Kachelrand, damit gereihte Stücke einen Zaun ergeben) und der Pfahl mit der Notiz des Bauern (die
 * Tafel `tafel` des Orts). Anker auf der Vorderkante, Höhen-Hinweis `block`.
 */
import { ort } from './_ort';

const KARREN = `................................
                ................................
                ................................
                ..aaaaa.........................
                .adceeeaaa.aaaa.................
                .adcddaCDDaeeeea....aaaaa.......
                .adcKKCDEECddddcaaaaeeeeeaaaaa..
                .adcKKCCDDCKKKKKccccdddddeeebca.
                .adckkkKKKKKKKKKKKKKKKKKKdddbca.
                .adckakkkkkkkkkkKKKKKKKKKKKKbca.
                .adckakkkakkkakkkkkkkkkkkKKKbca.
                .adceeekkakkkakkkakkkakkkkkkbca.
                .adcddddddeeeeeekakkkakkkakkbca.
                .a33ccccccccddddeeeeeeeeeakkbca.
                ..aaccaaaaacccccdddddadddeeebca.
                .acccacbbbbaccbbcccccacccdddbca.
                .abcabbcbcbaacccbbbbbabbbccc33a.
                .accabbb3bbaaccbcccccacccabbaa..
                .abbabb333bbabbbbbbbbabbbacccca.
                .abbaaab3baaabbabbbbaaabbbbbaa..
                ..abaabababaaba.aaaaabbcaaacbba.
                ..abbaaabaaabbaaaa.abcaaa3aaacba
                ...abbaaaaabbddddca.abbcaaacbba.
                ....abbbbbbbabbbaa...aabbbbbaa..
                .....kkbbbkk.kkk.......kkkkk....
                .......aaa......................`;

const BRUNNEN = `................
                 ......1111......
                 .11111bccb11111.
                 1dddddcddcddddd1
                 1cccccbccbccccc1
                 1bbbbbbbbbbbbbb1
                 .1bd1111d111bd1.
                 .1bd1..1d1.1bd1.
                 .1bd1..1d1.1bd1.
                 .1bd1..1d1.1bd1.
                 .1bd1.11d1.1bd1.
                 .1bd11bccb11bd1.
                 .1bd11cddc11bd1.
                 .1bd15b33b51bd1.
                 .1bd55bccb55bd1.
                 .1bd44KKKK44bd1.
                 .1bdKKkkkkKKbd1.
                 .154KKKkkKKK451.
                 .11544KKKK44511.
                 1235555555552321
                 1234244424442321
                 12hh222222222221
                 12hhh55552555221
                 121h244442444221
                 1222222222hh2221
                 1235255552hhh321
                 1234244442444321
                 1222222222222221
                 1232555255525321
                 1222222222222221
                 k22222222222222k
                 .11111111111111.`;

const HEUBALLEN = `................
                   ................
                   ................
                   ................
                   ..AAAAAAAAA.AA..
                   .ADDcDDEDDcAhhA.
                   ADDhcDEDDEchhhhA
                   ADEhhEDDEDcEDDEA
                   AEDDcDDEDDcDDEDA
                   ACCCcCCCCCcCCCCA
                   ADDDbDDDDDbDDDDA
                   ACDBbCCBDCbDCCCA
                   ACCDbCCDBrqCBCCA
                   ABqDbBCCCqqrCBCA
                   ACrqbCBCDCrCCCBA
                   ACCDbCCBCCbBCCCA
                   AAAAbAAAAAbAAAA.
                   Bk..k.....kCk...
                   ACA........A....
                   .A..............`;

const ZAUN_HEIL = `................
                   ................
                   ................
                   .......aa.......
                   ......acda......
                   .....abcdba.....
                   .....abcdba.....
                   .....abcdba.....
                   .....abcdba.....
                   .....abbdba.....
                   aaaaaabcdbaaaaaa
                   ddddddbcdbdddddd
                   bbbbbbbc3bbbbbbb
                   aaaaaabcdbaaaaaa
                   .....abcdba.....
                   aaaaaabccbaaaaaa
                   ddddddbcdbdddddd
                   bbbbbbbc3bbbbbbb
                   aaaaaabcdbaaaaaa
                   ....ahaaaha.....
                   ....ahhhhha.....
                   .....ahahha.....
                   ......k.kk......
                   ................`;

const ZAUN_GEBROCHEN = `................
                        ................
                        ................
                        ........aa......
                        .......abca.....
                        ......abcdba....
                        ......abcdba....
                        ......abcdba....
                        ......abcdba....
                        ......abcdba....
                        aaaaaaabcdba....
                        dddddddbcdbba...
                        bbbbbbbc3baaa...
                        aaaaaabcdbaddaa.
                        .....abcdbabbdda
                        aaaaaabccbaaabbd
                        ddddddbcdbdddddb
                        bbbbbbbc3bbbbbbb
                        aaaaaabcdbaaaaaa
                        ....ahaaaha.....
                        ....ahhhhha.....
                        .....ahahha.....
                        ......k.kk......
                        ................`;

const NOTIZPFAHL = `................
                    .......aa.......
                    ......acca......
                    .....abcdba.....
                    .....abcdba.....
                    .....abcdba.....
                    ...aaabcdba.....
                    ..aEEEE3EEEa....
                    ..aEBBBBBBEEa...
                    ..aEEEEEEEEDa...
                    ..aEBBBBBEEDa...
                    ..aEEEEEEEEDa...
                    ..aEBBBBBBEDa...
                    ..aEEEEEEDDa....
                    ..aEBBBEDDa.....
                    ..aDDDDDdba.....
                    ...aaabcdba.....
                    .....abcdba.....
                    .....abcdba.....
                    .....abcdba.....
                    .....abcdba.....
                    ....aabcdba.....
                    ...ahaaaahaaa...
                    ...ahhaahha33a..
                    ....ahaahh2332a.
                    .....a..aaaaaa..
                    ................
                    ................`;

export default [
  ort({ id: 'karren', size: [32, 26], anchor: [16, 24], hoehe: 'block', frames: [KARREN], occluder: { kind: 'rect', x: 3, y: 12, w: 26, h: 12 }, material: { metall: '3' } }),
  ort({ id: 'brunnen', size: [16, 32], anchor: [8, 30], hoehe: 'block', frames: [BRUNNEN], occluder: { kind: 'rect', x: 1, y: 19, w: 14, h: 11 } }),
  ort({ id: 'heuballen', size: [16, 20], anchor: [8, 18], hoehe: 'block', frames: [HEUBALLEN], occluder: { kind: 'rect', x: 1, y: 10, w: 14, h: 8 } }),
  ort({ id: 'zaun', size: [16, 24], anchor: [8, 22], hoehe: 'block', frames: [ZAUN_HEIL, ZAUN_GEBROCHEN], occluder: { kind: 'rect', x: 0, y: 11, w: 16, h: 11 } }),
  ort({ id: 'notizpfahl', size: [16, 28], anchor: [8, 26], hoehe: 'block', frames: [NOTIZPFAHL], occluder: { kind: 'rect', x: 5, y: 4, w: 6, h: 22 } }),
];
