/**
 * Der Meteorit im Krater (M7-09; docs/SPIEL.md §18 "krater"): ein narbiger, schwarzvioletter Brocken (Nachtrampe, Licht von
 * oben, Pockennarben), durchzogen von verästelten Adern kalten Sternenlichts (emissiv, Wasser- und Eisstufen) – das Sternenerz,
 * das um ihn herum liegt. Stellfläche 2×2, Zelle 32×36, Anker Zeile 33, Höhen-Hinweis `kugel`.
 */
import { ort } from './_ort';

const METEORIT = `................................
                  ................................
                  ................................
                  ................................
                  ................................
                  ................................
                  ................................
                  ................................
                  ................................
                  ................................
                  ................................
                  .......KKKKK.......KKKK.........
                  ......KNNNNNK.....KN~NNK........
                  .....KNNN~NNNKKKKKNk~NNNKK......
                  .....KNNk>NNNNNNNNNkNNNN<NKKKK..
                  ....KNnnNN<NNNNNNNNNNNN<nnnNNnKK
                  ..KKnnnnNN<NNNNNNNNNNNk>nNnnnnnn
                  .KnnnnNnNnN>NNNNNNNNNN<Nnnnnnnnn
                  .KnnnnnnnNn<nNNNNNNnN<NnNnnnnnnK
                  .KknnnnnnNnN<NNN~Nkn^NnnnnnnnkK.
                  ..KkknknnnnN^NnkNN<>N<<nnnnnkkK.
                  .Kkkkknnnnn<n<<~<<nnnnn<nnknKK..
                  .Kkkkknkkk<nnnk^nnnnknnk>nkkK...
                  ..KKKKkkkn<nnnnn<nnnnnnnk<kK....
                  ......KKk>kkkkkk<nnnnnkkkk<kK...
                  .......Kk<kkkkkk<kkkkkkkkkkkK...
                  .......K<kkkkkkkk>kkkkkkkkKK....
                  .......K<kKkkkkkk<kkkkKKKK......
                  .......KKKKKKKKkKK<KKKK.........
                  .........KKKKKKKKK<KKKK.........
                  ............KKKKKKKKKK..........
                  ..............KKKKKKKK..........
                  ................................
                  ................................
                  ................................
                  ................................`;

export default [
  ort({ id: 'meteorit', size: [32, 36], anchor: [16, 33], hoehe: 'kugel', frames: [METEORIT], occluder: { kind: 'rect', x: 4, y: 12, w: 24, h: 21 }, material: { metall: '<>^' } }),
];
