/**
 * Natürliche Ortsstücke (M7-08, M7-09; docs/SPIEL.md §18): die uralte Wurzel um den Uraltbaum (zwei Varianten, ein Bogen,
 * der aus der Erde steigt und wieder eintaucht; flach, nicht blockierend) und die Buddelmarke – ein Hügel lockerer Erde mit
 * einem Kreuz aus hellen Kieseln, der Hinweis auf die Stelle, an der die Schaufel fündig wird. Zelle 16×16, Anker Zeile 14.
 */
import { ort } from './_ort';

const WURZEL_BOGEN = `................
                      ................
                      ................
                      ................
                      ................
                      ......aaaa......
                      ....aahhddaaa...
                      ...addhhhcddda..
                      ..aacbcbbbcbda..
                      .addbbbbbbbbdda.
                      .abcbbbaaabbccda
                      adbbbaa...aabbda
                      acbbba.....abbca
                      pqqaa.......aqqp
                      apba.........apa
                      .aa...........a.`;

const WURZEL_FLACH = `................
                      ................
                      ................
                      ................
                      ................
                      ................
                      ..aaaaa.........
                      .adhhdda........
                      adbhhhdda.aaa...
                      acbbbbccdaddda..
                      abbbbbbbbdcbcda.
                      abbaaabbbcbbbcda
                      aaa...aabbbbbbca
                      pqqa....abbaaqqp
                      apa......aa..apa
                      .a............a.`;

const BUDDELMARKE = `................
                     ................
                     ................
                     ................
                     ................
                     ................
                     ....pppppppp....
                     ..pprrrrrrrrpp..
                     .prrs5sssss5rrpp
                     prsss35ttt53ssrs
                     prsstttt6ttsssqp
                     pqrsss5sss5srrqp
                     rpqqr5rrrrr5qqp.
                     p.ppp3ppppp3pp..
                     .....p.....p....
                     ................`;

export default [
  ort({ id: 'wurzel', size: [16, 16], anchor: [8, 14], hoehe: 'flach', frames: [WURZEL_BOGEN, WURZEL_FLACH], occluder: { kind: 'none' }, spiegelbar: true }),
  ort({ id: 'buddelmarke', size: [16, 16], anchor: [8, 14], hoehe: 'flach', frames: [BUDDELMARKE], occluder: { kind: 'none' }, einzelpixel: 'heller Mittelkiesel des Steinkreuzes' }),
];
