/**
 * Funke comments and context hints of strand D (docs/SPIEL.md §20, §23; M7-19 … M7-24): the first field and the seed, watering,
 * the soil worn by the harvest and the compost box, the pests (crows, hares, mildew), frost and the greenhouse, the sapling,
 * the bite and the fight on the line, bait, the fish trap and the ice hole.
 */
import type { GuideHintInput } from './schema';

export const GUIDE_HINTS_D: readonly GuideHintInput[] = [
  {
    id: 'hinweis_feld_saeen',
    kanal: 'hinweis',
    text: { de: 'Acker angelegt: Nimm Saat in die Hand und säe mit E. Mehr Saat bringt jede Ernte.', en: 'Field tilled: take seeds in your hand and sow with E. Every harvest brings more seeds.' },
    ausloeser: { art: 'ereignis', ereignis: 'plotCreated' },
    prioritaet: 1,
    einmalig: true,
  },
  {
    id: 'hinweis_feld_giessen',
    kanal: 'hinweis',
    text: { de: 'Gesät! Unter 20 Feuchte wächst nichts – gieß mit der Gießkanne, Regen gießt mit.', en: 'Sown! Below 20 moisture nothing grows – water with the can, rain waters too.' },
    ausloeser: { art: 'ereignis', ereignis: 'cropPlanted' },
    prioritaet: 1,
    einmalig: true,
  },
  {
    id: 'funke_feld_frost',
    kanal: 'funke',
    text: { de: 'Der Frost hat die Pflanze erwischt! Nur Winterharte überstehen ihn draußen.', en: 'The frost got the plant! Only hardy crops survive it outdoors.' },
    ausloeser: { art: 'ereignis', ereignis: 'cropDied', wo: { grund: 'frost' } },
    prioritaet: 2,
    einmalig: true,
  },
  {
    id: 'hinweis_feld_duenger',
    kanal: 'hinweis',
    text: { de: 'Jede Ernte zehrt am Boden. Kompost und Knochenmehl geben ihm Kraft – für Silber und Gold.', en: 'Every harvest wears the soil. Compost and bone meal restore it – for silver and gold.' },
    ausloeser: { art: 'ereignis', ereignis: 'cropHarvested' },
    prioritaet: 1,
    einmalig: true,
  },
  {
    id: 'hinweis_kompostkiste',
    kanal: 'hinweis',
    text: { de: 'Stell die Kompostkiste auf: Laub, Fasern und Tang werden in einem Tag zu Kompost.', en: 'Set up the compost box: leaves, fibres and seaweed turn into compost in a day.' },
    ausloeser: { art: 'besitz', item: 'kompostkiste', anzahl: 1 },
    prioritaet: 1,
    einmalig: true,
  },
  {
    id: 'funke_feld_kraehen',
    kanal: 'funke',
    text: { de: 'Krähen picken deine Saat! Eine Vogelscheuche hält sie vom Beet fern.', en: 'Crows peck at your seeds! A scarecrow keeps them off the bed.' },
    ausloeser: { art: 'ereignis', ereignis: 'pestAppeared', wo: { art: 'kraehen' } },
    prioritaet: 2,
    einmalig: true,
  },
  {
    id: 'funke_feld_hasen',
    kanal: 'funke',
    text: { de: 'Ein Hase knabbert am Beet! Ein Zaun ringsum hält ihn draußen.', en: 'A hare nibbles at the bed! A fence all around keeps it out.' },
    ausloeser: { art: 'ereignis', ereignis: 'pestAppeared', wo: { art: 'hasen' } },
    prioritaet: 2,
    einmalig: true,
  },
  {
    id: 'funke_feld_mehltau',
    kanal: 'funke',
    text: { de: 'Mehltau nach all dem Regen! Kräuterbrühe heilt die Pflanze.', en: 'Mildew after all that rain! Herb brew heals the plant.' },
    ausloeser: { art: 'ereignis', ereignis: 'pestAppeared', wo: { art: 'mehltau' } },
    prioritaet: 2,
    einmalig: true,
  },
  {
    id: 'hinweis_gewaechshaus',
    kanal: 'hinweis',
    text: { de: 'Ein Gewächshaus: Beete unter Glas wachsen das ganze Jahr, Frost erreicht sie nicht.', en: 'A greenhouse: beds under glass grow all year round, frost cannot reach them.' },
    ausloeser: { art: 'raum', raumtyp: 'gewaechshaus' },
    prioritaet: 1,
    einmalig: true,
  },
  {
    id: 'hinweis_setzling',
    kanal: 'hinweis',
    text: { de: 'Gepflanzt! Der Setzling wächst jeden Morgen ein Stück, bis er ein Baum ist.', en: 'Planted! The sapling grows a little every morning until it is a tree.' },
    ausloeser: { art: 'ereignis', ereignis: 'saplingPlanted' },
    prioritaet: 1,
    einmalig: true,
  },
  {
    id: 'funke_angeln_biss',
    kanal: 'funke',
    text: { de: 'Biss! Halte E und hol ihn ein – aber nicht zu straff, sonst reißt die Schnur!', en: 'A bite! Hold E and reel it in – but not too tight, or the line snaps!' },
    ausloeser: { art: 'ereignis', ereignis: 'fishBite' },
    prioritaet: 3,
    einmalig: true,
  },
  {
    id: 'hinweis_angeln_koeder',
    kanal: 'hinweis',
    text: { de: 'Mit Köder beißen manche Fische lieber. Regenwürmer findet die Hacke in der Erde.', en: 'With bait some fish bite more readily. The hoe turns up earthworms in the soil.' },
    ausloeser: { art: 'ereignis', ereignis: 'fishCast' },
    prioritaet: 1,
    einmalig: true,
  },
  {
    id: 'hinweis_reuse',
    kanal: 'hinweis',
    text: { de: 'Setz die Reuse ins Wasser – jeden Morgen kann ein Fisch darin sitzen.', en: 'Set the fish trap in the water – every morning a fish may be inside.' },
    ausloeser: { art: 'besitz', item: 'reuse', anzahl: 1 },
    prioritaet: 1,
    einmalig: true,
  },
  {
    id: 'hinweis_eisangeln',
    kanal: 'hinweis',
    text: { de: 'Ein Eisloch! Hier fängst du auch im Winter – die Quappe beißt gern unter dem Eis.', en: 'An ice hole! You can fish here in winter too – the burbot likes to bite under the ice.' },
    ausloeser: { art: 'ereignis', ereignis: 'iceHoleCut' },
    prioritaet: 1,
    einmalig: true,
  },
];
